### ISSUE TITLE
[FEATURE] Implement SfAvatar 

### ISSUE THREAD

**Issue by martaradziszewska** [vuestorefront/storefront-ui#1002]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 
This component will be needed in MyAccount page or e.g in Header as a logged-in guest.
![image](https://user-images.githubusercontent.com/34887212/78672134-8655d180-78e0-11ea-9ea1-03534c52e407.png)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-25) by [Unito](https://www.unito.io)

**Comment by peoray** [comment]
Is there a design for this @martaradziszewska

**Comment by mayashavin** [comment]
@filrak is there a design ready?
@peoray what is the status? Can I reassign or are you still on this?

**Comment by peoray** [comment]
If there is a design to implement, I can actively jump on this

**Comment by aniamusial** [comment]
Updated designs: 
https://www.figma.com/file/RwtFNOcNyrnV74BGKAUUcq/Storefront-UI-%7C-Design-System---v21?node-id=14745%3A18820
https://www.figma.com/file/RwtFNOcNyrnV74BGKAUUcq/Storefront-UI-%7C-Design-System---v21?node-id=14744%3A18073

**Comment by justyna-13** [comment]
@peoray are you still interested in this task? :)

**Comment by peoray** [comment]
Yes. I just saw that it got updated with the design link. I'll get to it ASAP

**Comment by justyna-13** [comment]
Hi @peoray :) how is it going with this feature? Do you need any help?

**Comment by peoray** [comment]
> Hi @peoray :) how is it going with this feature? Do you need any help?

Hey Justyna. I'll reach out to you on Discord with my questions :)

**Comment by AdamPawlinski** [comment]
@peoray Hi, would you mind if I close this issue? We have no plans for further developing SFUI1 in favor of the new version of our library [SFUI2](https://docs.storefrontui.io/v2/) as it is described in our [docs](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page) . If you are interested in further contributing to our library please do so following [contributing guide](https://github.com/vuestorefront/storefront-ui/blob/v2/CONTRIBUTING.md). 
Many thanks for your effort  :+1:

**Comment by AdamPawlinski** [comment]
I'm closing the issue as there are no further actions here.
