### ISSUE TITLE
[REFACTOR] Glide.js at Storefront UI

### ISSUE THREAD

**Issue by pspaczek** [vuestorefront/storefront-ui#1023]
**Describe how this feature will help us improve**
In Storefront UI we are using [Glide.js](https://glidejs.com/) for sliders. It's a dependency in SfCarousel, SfHero, SfGrouperProduct, and SfGallery. Glide.js required a few fixe's / extending functionality

1. #651 slide perPage: we have a few implementations of perPage scrolling functionality, but to be DRY friendly we want to use [Extending Components](https://glidejs.com/docs/extending-components/) to add this feature.
 
2. #545  Glide.js doesn't support the lazy loading of the image. It created a clone before images were loading and we get a broken image.

**Comment by Baroshem** [comment]
@justyna-13 I think we can close this issue as all sub issues has been resolved. What do you think?

**Comment by justyna-13** [comment]
sure :)
