### ISSUE TITLE
[FEATURE] More options in bottom navigation

### ISSUE THREAD

**Issue by patzick** [vuestorefront/storefront-ui#1031]
## Concept
Bottom navigation provides native app mobile experience which is great. We should somehow be able to extend its functionality by adding more options to it without taking more space from the screen.

### Proposed solution
Create something like "drag me" functionality, which would extend the existing functionality of the theme, like on fast mobile settings, where you can see more options.

My gorgeous paint of proposed solution:
![image](https://user-images.githubusercontent.com/13100280/79222530-fa9bf200-7e57-11ea-9d8c-966da601048d.png)

And it would pull off something like this 
![image](https://user-images.githubusercontent.com/13100280/79223147-0fc55080-7e59-11ea-903a-7f82744affb4.png)

This would allow themes to contain things like
- currency switcher 
- language selector
- other some custom platform functionalities
with just a click/swipe of bottom navigation

**Comment by mbaran-dvnt** [comment]
I think that this solution is really risky. The arrow to drag will be in really close contact with the wishlist button and anything that it's on the page, which can cause missed clicking and frustration. 

I've recently added currency switcher and language selection to the top bar.

Other options should be available from Menu.

**Comment by rmakara** [comment]
@mbaran-dvnt do we have some example of a mobile menu with +/- 8 things in there? Like store locator, about us, reviews, testimonials, contact us, delivery terms, purchase terms, returns, claims, customer service, style guide?

**Comment by patzick** [comment]
@mbaran-dvnt another proposition from me is to have the "up" button instead of "wishlist" here or around Account.
This functionality is important for plugins and systems to be able to add functionalities which are easily accessible on mobile with bottom navigation.

**Comment by mbaran-dvnt** [comment]
I understand I think that the main menu view would be nice to have in our conversation cause it seems it was missing from the SFUI.

Adding the view below, and you can see it in Figma. I strongly suggest keeping the bottom nav as it is.

![Zrzut ekranu 2020-04-25 o 15 15 24](https://user-images.githubusercontent.com/62093203/80280910-97d41180-8707-11ea-9fab-ff6fe32a1084.png)

**Comment by filrak** [comment]
How about making bottom bar srollable horizontally? I've seen this solution in few places

**Comment by mbaran-dvnt** [comment]
Yeah, I think that using "more" is much more efficient. It will open an extended menu the same way as a burger. Let me know what do you think and if that's ok I will proceed with designs:)

**Comment by Baroshem** [comment]
Hey @mbaran-dvnt 

Are you still working on the design part? :)

**Comment by mbaran-dvnt** [comment]
Unfortunately not. Please reach out @filrak to ask who is taking care of it now.

**Comment by patzick** [comment]
@Baroshem we resolved that by using the bottom modal, same as with the menu view
![image](https://user-images.githubusercontent.com/13100280/113127272-dd069a80-9218-11eb-999d-20466561d4db.png)

so inside can be anything
![image](https://user-images.githubusercontent.com/13100280/113127326-ed1e7a00-9218-11eb-9cc7-f7c83b8afd83.png)


not perfect, but doing what supposed to. If you're not planning to make the solution natively in bottom navigation, than I think we can safely close this issue then :)

**Comment by Baroshem** [comment]
Thanks guys for the fast reply! :)

Summon @filrak

**Comment by Baroshem** [comment]
Closing this issue as it can be handled differently.
