### ISSUE TITLE
[FEATURE] Add color picker to SfProductCard

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#1086]
**Describe how this feature will help us improve**
According to designs, we should have a color picker on SfProductCard. It is a common case in e-commerce as well.

![Screenshot from 2020-04-20 11-44-40](https://user-images.githubusercontent.com/41487496/79738072-8e5c3b00-82fc-11ea-8367-e9df6c59e90f.png)

**Comment by pspaczek** [comment]
related #881

**Comment by EduardDopler** [comment]
@aniamusial Isn't this a duplicate of #881? If there is new info maybe we can add it to the previous issue?
