### ISSUE TITLE
[FEATURE] SfInput should be more generic

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#1104]
**Describe how this feature will help us improve**
- Currently SfInput has features that is blocking the component from full customization. We need to make it more generic.

**Describe the solution you'd considered**
- `hasShowPassword` -> `hasIcon` 
- slot for icon
- `errorMessage` -> `helperText`
helperText shouldn't be binded to `valid` prop - the logic should be handled by the user.

----task modification----

- create hasIcon and helperText as seperate props leaving hasShowPassword and errorMessage as they are currently
- add deafult text for required prop
![image](https://user-images.githubusercontent.com/32042425/80513445-59e12280-897f-11ea-8bac-5560dbd264ed.png)

**Comment by filrak** [comment]
Agree except the last one -> displaying error message is a common pattern for every Input in every UI lib and the way its implemented makes it easy to use with libs like Vuelidate. Suggestion could be another prop as it's holding different value (ad sometimes can be displayed along with error) wdyt?

**Comment by AdamPawlinski** [comment]
Yes, that is what were our conclusions. We leave original behaviour and add this changes as new features.
