### ISSUE TITLE
[BUG] unnecessary image load when slide is changed

### ISSUE THREAD

**Issue by gibkigonzo** [vuestorefront/storefront-ui#1105]
**Describe the bug**
When I have disabled cache and slide is changed in `SfHero` then image is loaded with every change. It shouldn't and it's probably related somehow with custom variables. When I've changed to inline style then slider load image only once.

**How to reproduce**
1. Go to https://storybook.storefrontui.io/?path=/story/organisms-hero--common
2. disable cache in Network Tab 
3. wait for image change

**Expected behavior**
In disable cache image should be loaded only once

**Actual behavior**
What actual happened.
In disable cache image is loaded every time when slider is changed

**Screenshots**
![Peek 2020-04-24 15-40](https://user-images.githubusercontent.com/42383376/80219013-401fa280-8642-11ea-813c-f6d4c178913d.gif)

**Devices (please complete the following information):**
 - Device: Desktop
 - OS: Ubuntu 18
 - Browser: Chrome newest

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)
on https://capybara.storefrontcloud.io/ it not only load after image is changed but also while image is changing. So this results in multiple requests

**Comment by pspaczek** [comment]
@gibkigonzo @AdamPawlinski is a native problem with CSS Custom Properties. When you update anything in style attr and you disable cache then the picture is reloaded.

**Comment by psmyrek** [comment]
@pspaczek @AdamPawlinski @gibkigonzo Very similar issue concerning CSS variables and continuous image loading while cache is disabled has been recently reported in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1073904

I hope that it will be resolved there soon...  🙂
