### ISSUE TITLE
[FEATURE]Mobile -popup with information after adding product to the cart

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/storefront-ui#1196]
Related to the issues: #394 

**Describe the solution you'd considered**
The popup window with information 'Size ... was added to your shopping bag View cart' appears each time user is adding product to the cart with selected size as below:
![SizePopUp](https://user-images.githubusercontent.com/57936972/74606083-cad9a380-50cd-11ea-9809-c031276c4c41.gif)

**Acceptance criteria**

- [ ] the popup window with information 'Size ... was added to your shopping bag View cart' appears each time user is adding product to the cart with selected size on product page
- [ ] after pressing View cart on the popup user is redirected to the cart

**Comment by pspaczek** [comment]
probably you can use https://storybook.storefrontui.io/?path=/story/molecules-bottommodal--common to do it :)
