### ISSUE TITLE
[FEATURE] Add possibility to use mask on input

### ISSUE THREAD

**Issue by martaradziszewska** [vuestorefront/storefront-ui#1271]
**Describe how this feature will help us improve**
It's common to use input mask as a helper for user to fill the form - it improves UX and it's a common usage in any address forms.
Is it possible that SFUI can provide such a feature? Using libraries for this can cause problems and unnecessary hacks as a workarounds.

**Comment by Baroshem** [comment]
I think we are already providing masking on inputs. Closing the issue as there was no interest for more than a year.
