### ISSUE TITLE
[BUG] [MOBILE] Active category cover buttons in bottom navigation

### ISSUE THREAD

**Issue by Malwurf** [vuestorefront/storefront-ui#1298]
**Describe the bug**
On mobile after selecting category from bottom navigation the name of the category overlaps with the icons from bottom navigation. It was happened after update SFUI to 0.7.18

**How to reproduce**
1. Go to bottom nav on mobile device
2. Click on 'Menu'
3. Choose category

**Expected behavior**
Active category name doesn't cover any nav items

**Actual behavior**
Category name cover menu button

**Screenshots**
![Bottom mobile nav](https://user-images.githubusercontent.com/57936972/86757111-30113f80-c043-11ea-905a-6738d5fc839e.gif)

**Devices (please complete the following information):**
 - Device: Desktop (mobile look), Mobile
 - OS: iOS, MacOS, Ubuntu
 - Browser: [Chrome, Wersja 83.0.4103.116]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-27) by [Unito](https://www.unito.io)

**Comment by Baroshem** [comment]
@Malwurf 

Could you please check if the problem still exists? This issue was created long time ago
