### ISSUE TITLE
[FEATURE] SfProductCard - add extra slot for additional content

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1302]
**Describe how this feature will help us improve**
When you need to add additional line of text styled differently than product title you have to use extra styling.  

**Is your proposal related to a problem?**
I tried to add category of product in SfProductCard, which is styled differently above title. I had to use :before psedoelement.  

**Describe the solution you'd considered**
Add additional empty slot above title slot. It can be named 'subtile', 'additional-content' or 'product category' , wdyt?
```
<slot name="subtitle" v-bind="{ subtitle, link }">
      <SfLink :link="link" class="sf-product-card__link">
        <h4 class="sf-product-card__subtitle">
          {{ subtitle }}
        </h4>
      </SfLink>
 </slot>
```

**Comment by filrak** [comment]
For such stuff we should have a naming convention like `extra-top` `extra-bottom`(feel free to propose sth different). I see that useful in many components.
