### ISSUE TITLE
[FEATURE] SfComponentSelect add modifiers to change label position

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1306]
**Describe how this feature will help us improve**
Label in SfSelect is by default placed above options according our designs, but there should be possibility to place it to the left of options or above. It is common use case, I think.
![image](https://user-images.githubusercontent.com/32042425/87657635-6180be00-c75b-11ea-8412-22274e66e4aa.png)

**Is your proposal related to a problem?**
To place label in other position you need to prepare some extra styling, but instead it should be easily done.  

**Describe the solution you'd considered**
I would propose to add css-modifiers like '--label-left' and '--label-top' to modify position of label before or on top of options, it can be done like this:
'''&--label-left {
--select-label-top: 50%;
--select-label-left: calc(var(--spacer-2xl) * -1);
--select-padding: 0 0 calc(var(--font-xs) * 1.2) var(--spacer-2xl);
--select-label-padding: var(--spacer-xs) 0 0 0;
--select-label-font-size: var(--font-lg);
.sf-select__label::after {
content: ":";
color: inherit;
}
}''' 
and add --select-label-padding to  .sf-select__label class.

--label-top should be prepared similarly.

**Comment by AdamPawlinski** [comment]
Blocked by https://github.com/DivanteLtd/storefront-ui/issues/1321 issue

**Comment by Ziomeka** [comment]
@AdamPawlinski I'm looking into SfSelect and I think we should not add this to SfSelect. This component is based on native <select> and <options> which can have only plain text inside (there are mistakes in stories) and cannot be styled the way You suggested. If we give support for safari we could make a hack with text-align-last (https://caniuse.com/css-text-align-last, https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last). This however looks like a good feature for SfComponentSelect.

**Comment by AdamPawlinski** [comment]
@Ziomeka You are right. This issue was created long ago before SfSelect was created so it can be confusing as it consider SfComponentSelect in fact and not SfSelect. Exactly as you mentioned :) So I change the title.
