### ISSUE TITLE
[REFACTOR] SfSelect Refactor

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#1321]
**WHY**
Currently, SfSelect and SfComponentSelect is very buggy and most of all - not accessible as it is not semantically correct. 

1) Add class modifiers to change position of content. #1306 
2) Add possibility to add default value for SfSelect and SfComponentSelect #1456 
3) SfSelect does not update label in the main div #1335

**Comment by Ziomeka** [comment]
As I was looking for a11y problems in storybook in general I stopped at SfSelect and gathered a refactor proposition as for now its accessibility is easy to be destroed by semantic errors. Things i recommend to be done:

1. Fix stories so putting value works. Remove SfProductOption from SfSelect as option from cannot take other html tags inside. This bug #1735 caused by breaking this rule. Probably will cause nuxt errors too.
2. Change all examples where something different than text is inside SfSelectOption to SfComponentSelect as this is not allowed
3. Prevent developers from putting html tags into SfSelectOption - probably there is no solution with backwards compatibility. I suggest removing the slot and add prop text. Or maybe add a prop with text to pass, and leave a slot with a comment that using it may break the app.
4. Add prop for default selected option and make attribute selected be put in proper option: It can be done by: 

- rewriting component to render function
- reference to component children (bad pattern)
- or by getting rid of SfSelectOption and passing a list of options as array (no backward compatibility but it prevents from putting html tags inside option, solves problem nr 3).
Render function or getting rid of SfSelectOption will help get rid of this bug #1335

5. Improve disabled handling as in this issue #1847 for a11y
