### ISSUE TITLE
[BUG] SfSelect does not update label displayed in main div

### ISSUE THREAD

**Issue by psmyrek** [vuestorefront/storefront-ui#1335]
**Describe the bug**
SfSelect does not update label from selected option from computed property `html` displayed in `<div ref="sfSelect>`, because it is generated once after mounting the component or if number of options has changed. This should also be changed after changing the label of an option.

**How to reproduce**
1. Create `SfSelect` component with couple of options.
2. Change label for selected options in reactive way.
3. Error: label in dropdown list has changed but label displayed in `<div ref="sfSelect>` is old one.

**Expected behavior**
SfSelect should update selected label after changing it programatically.

**Actual behavior**
SfSelect does not update label from selected option from computed property `html` displayed in `<div ref="sfSelect>`.

**Devices (please complete the following information):**
 - Device: Desktop
 - OS: Win
 - Browser: FF

**Comment by runyasak** [comment]
Hi, @psmyrek 
I have seen that `SfSelect` that have not taken `options` prop but it gathered from default slot, such as `SfSelectOption`.
So, I will provide some urgent solution, not the best practice, using `:key` to force rendering `SfSelect` by `value` and assign with new `options`.

You can see my example code below:

```vue
<template>
  <div>
    <SfSelect
      :key="selected"
      v-model="selected"
      :label="label"
      :size="size"
      :required="required"
      :valid="valid"
      :disabled="disabled"
      :error-message="errorMessage"
      :persistent="persistent"
      style="max-width: 30rem;"
    >
      <SfSelectOption
        v-for="(option, key) in options"
        :key="key"
        :value="option.value"
      >
        <SfProductOption
          :key="option.value"
          :color="option.color"
          :label="option.label"
        ></SfProductOption>
      </SfSelectOption>
    </SfSelect>
    <button @click="toggleOptions">Toggle</button>
  </div>
</template>
<script>
import SfSelect from "./components/molecules/SfSelect/SfSelect";
import SfProductOption from "./components/molecules/SfProductOption/SfProductOption";
export default {
  components: {
    SfSelect,
    SfProductOption,
  },
  data() {
    return {
      selected: "",
      options: [
        { value: "amaranth", color: "#E52B50", label: "Amaranth" },
        { value: "amber", color: "#FFBF00", label: "Amber" },
        { value: "arctic-lime", color: "#D0FF14", label: "Arctic lime" },
        { value: "bluetiful", color: "#3C69E7", label: "Bluetiful" },
        { value: "buff", color: "#F0DC82", label: "Buff" },
      ],
      options2: [
        { value: "amaranth2", color: "#E52B50", label: "Amaranth 2" },
        { value: "amberhaha2", color: "#FFBF00", label: "Amber 2" },
        { value: "arctic-lime2", color: "#D0FF14", label: "Arctic limeWorld 2" },
        { value: "bluetiful2", color: "#3C69E7", label: "Bluetiful 2" },
        { value: "buff2", color: "#F0DC82", label: "Buffal 2" },
      ],
      label: "Color",
      size: 5,
      required: false,
      valid: true,
      disabled: false,
      errorMessage: "Color",
      persistent: false,
      isToggle: false
    };
  },
  methods: {
    toggleOptions () {
      // Provide new selected that you want
      this.selected = this.options2[0].value;
      this.options = [...this.options2];
    }
  }
};
</script>
<style lang="scss">
@import "./css/all.scss";
</style>
```

This is not the best practice. However, you can use this approach to dynamic options for waiting core team to provide the best solution. 😁

**Comment by fchienvuhoang** [comment]
I got same error!
<img width="421" alt="Screen Shot 2020-07-29 at 13 44 18" src="https://user-images.githubusercontent.com/4451749/88766084-a23bf680-d1a1-11ea-9802-a155aee9bdcb.png">

**Comment by mayashavin** [comment]
Will be part of refactor SfSelect #1321

**Comment by AdamPawlinski** [comment]
I think that this is solved. Looks like the value from the selected option gets updated when it is chosen. Previously changes were made by provide inject communication betweeen SfComponentSelect and SfComponentSelectOption components, but now its updated by directly by $parent in internal component. I suppose that it can be closed, but please verify if I'm not wrong @justyna-13 @aniamusial. 
 
![component-select](https://user-images.githubusercontent.com/32042425/149963747-30e38bbb-0e74-4d3e-9ba1-609f7e2895c7.gif)
