### ISSUE TITLE
[BUG] Position of SFModal is based on the dynamic viewport.

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/storefront-ui#1340]
**Describe the bug**
The position of SFModal is based on the dynamic viewport. 
Its postion is defined as, 
    --modal-top: 50%;
    --modal-left: 50%;
    --modal-bottom: none;
    --modal-right: none;
Which results in fluctuation of its position, if viewport's size is changed. 

**How to reproduce**
1. Go to capybara.storefrontcloud.io
2. Click on login
3. resize your viewport(maybe by opening the console)
4. See fluctuating modal of login

**Expected behavior**
It should not fluctuate and stay as it is.

**Actual behavior**
It's position fluctuate with the view port

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**
https://cdn.discordapp.com/attachments/581361263804678166/729622864973791262/SFModal.mp4

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]: Desktop
 - OS: [e.g. iOS8.1] : Linux
 - Browser: [e.g chrome, safari][version]: Mozilla Firefox

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)
https://discordapp.com/channels/581361263804678164/581361263804678166/729622865728503839

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-28) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I wonder if it can be classified as bug. @AishwaryShrivastav could you please show some use case when it is wrong behaviour? Wdyt @filrak?

**Comment by AishwaryShrivastav** [comment]
Hello @AdamPawlinski, its an improvement, we should not classify it as bug, while creating issue I only had option to choose it as a bug or feature request.

I don't have any specific use case for this behavior, but most of the [standard modals](https://getbootstrap.com/docs/4.0/components/modal/) don't fluctuate with the view port. 

current behavior : https://cdn.discordapp.com/attachments/581361263804678166/729622864973791262/SFModal.mp4
