### ISSUE TITLE
[FEATURE] Create developers guide

### ISSUE THREAD

**Issue by filrak** [vuestorefront/storefront-ui#1361]
Write down all conventions that we have in a project, release pipeline, acceptance rules, used 3rd parties (important) etc.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-30) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I close this issue as it is no longer needed. Support for SFUI1 is limited to maintenance and bugfixes.
