### ISSUE TITLE
[FEATURE] Design SfHorizontalNavigation

### ISSUE THREAD

**Issue by filrak** [vuestorefront/storefront-ui#1366]
Desktop
![image](https://user-images.githubusercontent.com/15185752/89928844-b273bd00-dc08-11ea-9178-af8374ce639d.png)

Mobile
![image](https://user-images.githubusercontent.com/15185752/89994224-1d180d80-dc88-11ea-8b1a-910053b6d5e6.png)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-32) by [Unito](https://www.unito.io)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-09-18 o 11 32 13](https://user-images.githubusercontent.com/62093203/93582327-9a7b2000-f9a2-11ea-96b8-09e3a9776100.png)

It's already in place :)
