### ISSUE TITLE
[FEATURE] Possibility to display <img> tag in SfHeroItem component

### ISSUE THREAD

**Issue by qiqqq** [vuestorefront/storefront-ui#1372]
**Describe how this feature will help us improve**
Currently, we can pass image to the SfHeroItem component as prop and this image is displayed as background-image. There should be a possibility to display it as <img> tag. This solution allows to control slide height and set it as image height (currently it is not possible and the height of slide must be defined in the CSS as static value).

**Describe the solution you'd considered**
I think, there should be additional <slot> to allow pass additional content to the slide (or overwrite all slide content)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-33) by [Unito](https://www.unito.io)

**Comment by mayashavin** [comment]
Related to #1105
