### ISSUE TITLE
[ANALYZE] Clear CSS

### ISSUE THREAD

**Issue by filrak** [vuestorefront/storefront-ui#1407]
**Describe how this feature will help us improve**

our current CSS setup is messy. To be more exact
- hard to understand how it works and how to customize it at a first glance (which mixins are generating which variables and what they are for) - we should **just** have a set of global CSS variables that are used to customize the project on the high-level and other customizations should be component-specific
-  its not obvious which mixins and variables are generated, which we can override, which are public and which private, both are in the docs
- makes it impossible to have precompiled version of SFUI that can still be customized

We should come up with a plan of removing the redundant complexity that will lead to these action points:
- We have strictly defined public API for global customization containing **only** CSS variables
- CSS modifiers are using the global CSS variables
- component-specific CSS is using global variables and does not declare any compoennt-specific ones
- we don't have any dependency on runtime SCSS (so when there is no SCSS we can still customize the project with CSS vars)

**Comment by mayashavin** [comment]
In addition, as discussed:
* Define a solid public API layer to stabilise for v.1.0.0 usage
* Map the old API to the new one.
* Continue to refactor and remove the old one based on this.
* Adding PurgeCSS to remove unused CSS on compiling/building.
* Develop new feature based on this API layer

An example of the pattern is shown as below:
![1Iil4E2y_Zae-x3SLt6DOrw](https://user-images.githubusercontent.com/6650139/93852861-7a59a280-fcbb-11ea-8938-65e8f6f983b6.png)
