### ISSUE TITLE
[FEATURE] Improve z-index of SfSiderbar such that it always remain top of the stack when open

### ISSUE THREAD

**Issue by mohammad-k8** [vuestorefront/storefront-ui#1411]
**Describe how this feature will help us improve**
I would like to propose an improvement in SfSidebar regarding it's z-index. IMO, the sidebar should be top-most element in the stack when it is opened. So it's z-index should be the highest of all the other elements in the page. Most of the websites/apps has such behaviour like twitter's pwa. This will also fix the issue in capybara theme where the bottom navigation hides the bottom elements of the sidebar in safari mobile. 

**Is your proposal related to a problem?**
Sticky bottom elements of sidebar are hidden by the bottom navigation:
![Screenshot 2020-09-22 at 7 11 41 PM](https://user-images.githubusercontent.com/34086621/93894166-0bf10080-fd0c-11ea-8ebb-6844c49454a1.png)

**Describe the solution you'd considered**

I am aware that working with z-index is quite tricky. I would like to propose a simple solution here of keeping the z-index value of siderbar to be some large number so that it will always be on top of every other element of the page.

If anyone has some better solution, then please feel free to jump in.
**Additional context**
Anything you would like to add but was not sure which section it fits.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-34) by [Unito](https://www.unito.io)

**Comment by dt2patel** [comment]
This would be a great addition. I know in Capybara there is some CSS written to calculate a safe height for the sidebar but unfortunately the way viewport height is calculated on iPhone means the sidebar still overlaps with the bottom navigation a lot of the time.
