### ISSUE TITLE
[BUG] SfModal 'no preview'  shows after clicking on button

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1423]
**Describe the bug**
On SfModal in Storybook: when clicking on 'hello' button 'no preview' message shows

**How to reproduce**
Go to SfModal on Storybook and click on 'hello' button.

**Expected behavior**
Clicking on button should have no effect or should show alert on the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/94204184-156f9980-fec1-11ea-9689-b49c49edaceb.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by hansfelix** [comment]
@AdamPawlinski  I want to contribute to fix this Issue. I'll send a PR.

**Comment by AdamPawlinski** [comment]
@hansfelix Thank you for your participation. It's assigned to you :)
