### ISSUE TITLE
Stage Image is left aligned in SfGallery  [BUG]

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/storefront-ui#1445]
**Describe the bug**

SFUI provides a variable to modify the width of stage image (main image ) in SfGallery  "--gallery-stage-width".

When we're trying to reduce the width using this variable, we see that the stage image is aligned to left.

To align it in center horizontally we can use align-item : center, or maybe margin:auto, and it should work fine.

But after compiling when we reloads the page. 
Main image( __stage ) from SfGallery vanishes. 

**How to reproduce**

Here is a quick video on reproducing this issue 
https://drive.google.com/file/d/1KZ1sfOwCRWQsNQ4LVPxfpZdDcgW4Cjxf/view?usp=sharing

**Expected behavior**

Main Image (Stage) should be center align horizontally.

**Actual behavior**

It is left align

**Code examples**

![center align hides the stage](https://user-images.githubusercontent.com/8766155/94653086-a2c74980-0318-11eb-9410-7e8022329ddc.png)

**Screenshots**

![Screenshot from 2020-09-30 12-33-11](https://user-images.githubusercontent.com/8766155/94653388-1ff2be80-0319-11eb-850e-6b7631011c03.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop] Mobile devices
 - OS: [e.g. iOS8.1] All
 - Browser: [e.g chrome, safari][version] All, firefox for sure

**Additional context**

Created this issue as per the discussion on slack channel https://discordapp.com/channels/581361263804678164/581361425444896768/760718064924229683

**Comment by Baroshem** [comment]
@mayashavin 
Are you working on this task?
