### ISSUE TITLE
[FEATURE] SfSelect should be able to have its default selected option specified

### ISSUE THREAD

**Issue by loongluangkhot** [vuestorefront/storefront-ui#1456]
**Describe how this feature will help us improve**
Currently, SfSelect takes in placeholder, but not default selected option. This feature could lead to a better UX, e.g. for example, if a product is wildly popular in a particular colour, we could use that as the default option, so an average user (who falls into the majority) don't need to do the clicking to choose the colour.

**Is your proposal related to a problem?**
N.A.

**Describe the solution you'd considered**
The solution I can on top of my head is to have SfSelect take in a prop of `defaultSelectedKey` (or something better named), which corresponds to one of the keys of the SfSelectOptions (children of SfSelect). What I described is similar to the way it is implemented in [Ant Design](https://ant.design/components/select/) (the prop is named `defaultValue`). We could use that as reference. Feel free to propose different solutions though!

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by loongluangkhot** [comment]
Please assign this to me! Thx!

**Comment by mayashavin** [comment]
@loongluangkhot once I finish reviewing the feature request, I will assign you if it is a valid one for implementation :)

**Comment by mayashavin** [comment]
related to #1321

**Comment by Baroshem** [comment]
@loongluangkhot 
Are you still interested in this task? If so, we could give you some hints :)

**Comment by Baroshem** [comment]
@loongluangkhot 

Great news! In terms of a development, your proposed solution looks good. Apart from developing the functionality it would be good if you could also update the changelog accordingly to other features (please take a look at the other pull requests). If you have any questions please do not hesitate to contact us :)

**Comment by Baroshem** [comment]
@loongluangkhot 

Sorry for not answering. Last few days were very busy for us. Your proposed solution looks very good to me. I think you can create a pull request with this change :) 

Just remember to also update the changelog for version 0.11.0 (packages/vue/src/stories/releases/v0.11.0/v0.11.0.stories.mdx) and add it in a `features` section. 

If you have any questions do not hesitate to contact me.

**Comment by loongluangkhot** [comment]
@Baroshem hmmm upon closer look, I feel that we could achieve the default selected option by using the value props that's already available now. Looks like this feature is unnecessary. What do you think?

**Comment by DavidGolodetsky** [comment]
@loongluangkhot I think it's a valid feature!
I tried to use the `value` prop for this purpose and it results in blinking select on page refresh. It selects the first option in the list first and then rewrites it to my option.

Here is the code:
![image](https://user-images.githubusercontent.com/32278933/122549484-340f5500-d03b-11eb-8c7b-697d4d726de6.png)

The same applies if I use the regular `option` tag instead of `SFSelectOption`

I managed to resolve this issue by adding `selected` attribute to the option, but I'd rather have a `selected` prop on the `SFSelect` component instead.


![image](https://user-images.githubusercontent.com/32278933/122549895-ac761600-d03b-11eb-9131-1470185f9771.png)

**Comment by Ziomeka** [comment]
Hi. I'm struggling with selecting the default value in a very similar component. In my opinion SfSelect definitely should interact with SfSelectOption so the chosen option will have set the selected attribute. This is important for accessibility and it will make possible @DavidGolodetsky request. I would go for a render function to pass the selected attribute to the slots. I can help with an example.

**Comment by antonioglass** [comment]
Hi! I would be also interested in this feature. Will it be released?
