### ISSUE TITLE
Responsive Menu items in header.vue

### ISSUE THREAD

**Issue by davevh** [vuestorefront/storefront-ui#1469]
**Describe the bug**
When there are more menu items the items are not responsive on the o-header.vue in the capybara theme

![image](https://user-images.githubusercontent.com/6746508/95578267-e6fecc00-0a33-11eb-95cc-cf3e45f079c0.png)
Multiline:
![image](https://user-images.githubusercontent.com/6746508/95578366-11508980-0a34-11eb-8a9b-a2419056135f.png)

Also submenus are not responsive 
![image](https://user-images.githubusercontent.com/6746508/95578464-35ac6600-0a34-11eb-91df-2974648847cb.png)

**Expected behavior**
Responsive headers also on multiline

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
It would be nice that you can order the logo and menu items

**Comment by davevh** [comment]
Any news on this subject ?

**Comment by Baroshem** [comment]
Hi @davevh 

If I understand correctly, you want menu to scale well for all menu sizes? Like the menu items should get smaller so that the whole menu would fit the screen size?

**Comment by Baroshem** [comment]
Closing as there was no follow up for a few months
