### ISSUE TITLE
Redundant props - hasBadge and badgeLabel

### ISSUE THREAD

**Issue by mayashavin** [vuestorefront/storefront-ui#1473]
Saw we have `badgeLabel` and `hasBadge` in Icon. We don't need both, if there is a badge, a label must be presented, else, there is no label needed. We only need `badge` as a prop, and render only if it has value.

**Comment by daksamit** [comment]
Anyone is assigned to this?
I may try to solve this if don't.

It will affects Capybara also, am I right?

**Comment by mayashavin** [comment]
@daksamit 
Hi Dominik,

Currently no one is assigned to this one. You can take this, but we want to remove the use of `SfBadge` inside this component completely since it is the wrong implementation in the first place. You can refer here: #1474 

LMK if you wish to go ahead. I will assign you accordingly.

**Comment by daksamit** [comment]
Ok, I see. it's not only replacing `badgeLabel` and `hasBadge` with single `badge` and checking for string length to display badge.
It's more complex refactor including removing SfBadge component from SfIcon?

**Comment by mayashavin** [comment]
It's not exactly complex. Just remove the implementation of sfBadge inside
SfIcon and any props/css related :). That's all.

Let me know if you need anything.

Best regards,
*Maya Shavin*
Senior FrontEnd Developer
📱*:* +972-54-9445592 <+972%2054-9445592>
www.cloudinary.com

**Comment by daksamit** [comment]
Ok, please assign it to me :)
