### ISSUE TITLE
SfSelect not working properly and the ui is bad[BUG]

### ISSUE THREAD

**Issue by davevh** [vuestorefront/storefront-ui#1480]
**Describe the bug**
When opening a dropdown of sfselect the items are not scrollable and postion is to bad

**How to reproduce**
example in the capybara theme when you want to modify your country in shippiding details. Long list but goes over all items and not working on mobile

**Expected behavior**
Be a list that is scrollable

**Actual behavior**
All items are listed on screen without scrolling area and covers more than you expected

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
//Write code here
```
<SfSelect`
              v-model="rank"
              name="rank"
              :label="$t('Rank')"
              required
              :error-message="$t('Field is required.')"
              class="form__element"
            >
              <SfSelectOption
                v-for="rank in Ranks()"
                :key="rank.value"
                :value="rank.label"
              >
                {{ rank.label }}
              </SfSelectOption>
            </SfSelect>
```
Or add code snippets (Code sandbox)

**Screenshots**
![image](https://user-images.githubusercontent.com/6746508/96450245-3acc9a80-1216-11eb-82d5-1598b7d03264.png)

**Devices (please complete the following information):**
All
**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by daksamit** [comment]
Another bug with SfSelect is missing focus state.
How to reproduce ?
https://storybook.storefrontui.io/?path=/story/molecules-select--common
1. Click select component
2. Press Tab
3. Press shift + Tab

The same but with [input](https://storybook.storefrontui.io/?path=/story/atoms-input--common) - focus works correctly.

**Comment by AdamPawlinski** [comment]
@davevh Hi, the bug you mentioned is already fixed in the 0.9.0 version (however it is better to use newest one 0.9.2 as it has many other bugs fixed). The capybara theme uses older version of SFUI. However, in the current version SfSelect is native <select> element so you need to style it. You can also use SfComponentSelect as it keeps older API of the select component.

**Comment by AdamPawlinski** [comment]
@daksamit Hi, thanks for noticing this bug. I'll prepare the issue for that. There is unnecessary outline:none property in the component so need to be removed.

**Comment by AdamPawlinski** [comment]
https://github.com/DivanteLtd/storefront-ui/issues/1531 issue for outline created

**Comment by mayashavin** [comment]
UI is fixed but still have scrollable problem @AdamPawlinski

**Comment by Baroshem** [comment]
@AdamPawlinski could you please check if all problems have been resolved and if this issue can be closed? :)

**Comment by aniamusial** [comment]
Closing as scroll is working fine in the newest 0.11.5 version
