### ISSUE TITLE
[BUG] If I set any properties image-witdh or image-height on ProductCard alignment internal components will be broken

### ISSUE THREAD

**Issue by VMescheryakov** [vuestorefront/storefront-ui#1483]
If I set any value to image-width or image-height   internal components alignment  will be broken

![image](https://user-images.githubusercontent.com/3495337/96547995-82aafa80-12c6-11eb-8982-a8a319c1b273.png)

**Comment by justyna-13** [comment]
Hi @VMescheryakov, I tried to change image-width and image-height in SfProductCard and there was no bug. The first one is set with image-width and the second one is with image-height. Can you check it again? 
1)
![Zrzut ekranu z 2020-10-29 14-26-47](https://user-images.githubusercontent.com/46591755/97580268-5f352d80-19f3-11eb-8c32-0fda758d6474.png)
2)
![Zrzut ekranu z 2020-10-29 14-27-39](https://user-images.githubusercontent.com/46591755/97580295-678d6880-19f3-11eb-8658-ec45a3e5db37.png)

**Comment by AdamPawlinski** [comment]
@VMescheryakov could you please check if it bug still appears? If not I will close this issue. Thanks.
