### ISSUE TITLE
[FEATURE] Apply new design for table mobile view

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1496]
**Describe how this feature will help us improve**
Our design for table mobile view has changed.

**Is your proposal related to a problem?**
The current table doesn't look good on small mobile devices 

The new designs are in figma - molecules 

![Zrzut ekranu z 2020-10-23 13-22-32](https://user-images.githubusercontent.com/46591755/96997982-0f59f080-1533-11eb-8891-93aca18763c2.png)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-35) by [Unito](https://www.unito.io)

**Comment by jakubmakielkowski** [comment]
Current table structure has one <thead> and multiple <tbody> for every row which is still valid according to https://html.spec.whatwg.org/multipage/tables.html#the-table-element
Mobile table has separated heading for every row. This demands creating multiple tables or multiple <thead> (not valid) in one table.
Maybe we could put <tbody> and <thead> tags outside SfTableHeading and SfTableRow components?
