### ISSUE TITLE
[BUG] Auto complete preview doesnt trigger labels to go away from the SfInput

### ISSUE THREAD

**Issue by EugeneHlushko** [vuestorefront/storefront-ui#1516]
**Describe the bug**

When hovering into autocomplete options in Chrome latest

<img width="663" alt="Screenshot 2020-11-05 at 12 32 21" src="https://user-images.githubusercontent.com/10549495/98229826-120d0a80-1f63-11eb-9d19-33d1e661b905.png">

Is there an approach you can take to be aware that pre-filling is going on?

**How to reproduce**
1. Have address in browser autocomplete
2. click into one of the form inputs
3. observe how the clicked field has label traveling to the top right
4. hover (dont select just hover) over one of the autocomplete options you have
5. observe all other fields labels overlapping the pre-filled values

**Expected behavior**
No overlapping happening when previewing auto complete

**Actual behavior**
....it happens

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by AdamPawlinski** [comment]
@EugeneHlushko Hi, I couldn't reproduce this error. Can you please provide me with the SFUI version you are using? And also if you use it along with VSF theme?
