### ISSUE TITLE
[BUG] badgeLabel Prop of SfIcon expects String but gets String OR Number from SfHeader

### ISSUE THREAD

**Issue by ChrisClsg** [vuestorefront/storefront-ui#1520]
**Describe the bug**
`SfIcon` prop `badgeLabel` expects a String whereas `SfHeader` accepts Strings **and** Numbers for `wishlistItemsQty` and `cartItemsQty` which are binded to `SfIcon`'s `badgeLabel`. Also the `SfHeader` docs promote the usage of either a String or a Number for `wishlistItemsQty` and `cartItemsQty`.

**Expected behavior**
`wishlistItemsQty` and `cartItemsQty` should only accept types that don't cause an error when binded to `SfIcon` since it's their only purpose.

**Actual behaviour**
`wishlistItemsQty` and `cartItemsQty` accept types that cause an prop type error when binded to `SfIcon`.

**Possible feature request instead of a bug fix?**
Personally I see no reason why `SfIcon` should not accept a Number for `badgeLabel`. And it would be a faster fix than changing the `SfHeader` prop check and the `SfHeader` docs. But then again I'm not really deep into the code of this project yet and don't know whether this would cause any problems in another place.

**Code examples**
```
export default {
  name: "SfIcon",
  ...
  props: {
   ...
    badgeLabel: {
      type: String,
      default: "",
    },
    ...
  },
};
</script>
```
```
export default {
  name: "SfHeader",
  ...
  props: {
    ...
    wishlistItemsQty: {
      type: [String, Number],
      default: "0",
    },
    ...
    cartItemsQty: {
      type: [String, Number],
      default: "0",
    },
    ...
  },
  ...
};
```

**Screenshots**
![image](https://user-images.githubusercontent.com/48719308/98400241-fc333e80-2063-11eb-9a1f-7f6426102e8b.png)

PS:
This is my first bug report ever. So please let me know, if there's something wrong with it.
And thanks for your work! (:

**Comment by AdamPawlinski** [comment]
@ChrisClsg Thanks for reporting this bug and regarding this issue it is defined perfectly fine. 
As you suggested, I think it will be fine to add Number type for badgeLabel prop in SfIcon. So thank you once again :)

**Comment by mayashavin** [comment]
@AdamPawlinski we need to remove using the label inside SfIcon since that's bad practice and go against Atomic Design.

**Comment by mayashavin** [comment]
`badgeLabel` is removed from SfIcon
