### ISSUE TITLE
[BUG] SfSelect no outline when focused with keyboard

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1531]
**Describe the bug**
SfSelect has no outline on focus.

**How to reproduce**
Go to sfselect on storybook and try to focus on select using keyboard. There is no outline.

**Expected behavior**
There should be outline appearing when focused with keyboard.

**Actual behavior**
What actual happened.

**Code examples**
The outline:none property should be removed from component style. 

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by daksamit** [comment]
Another bug, maybe easy to fix, default font for select inside SfSelect wrapper is Arial.
Noticed on capybara theme and docs: https://docs.storefrontui.io/components/select.html
