### ISSUE TITLE
[FEATURE] impement new design for SfFooter

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1536]
**Describe how this feature will help us improve**
There is a new design for SfFooter to implement 
![Zrzut ekranu z 2020-11-17 15-16-16](https://user-images.githubusercontent.com/46591755/99401078-0b2db280-28e8-11eb-9e73-6a0863e492d7.png)

**Is your proposal related to a problem?**
No

**Comment by filrak** [comment]
Please make it all black on mobile
