### ISSUE TITLE
[FEATURE] More readable default font properties in components

### ISSUE THREAD

**Issue by daksamit** [vuestorefront/storefront-ui#1543]
Currently, if we developing with sfui, in most cases font rules looks like:
![image](https://user-images.githubusercontent.com/7165997/100217532-d9ce6b80-2f13-11eb-8578-925bc0c00890.png)
For newcomers who don't know sfui's custom properties well it's hard to understand.

I think solution like this, could be more readable:
![image](https://user-images.githubusercontent.com/7165997/100218012-6b3ddd80-2f14-11eb-9813-78d218a7c698.png)

What do you think about this?

**Comment by Baroshem** [comment]
@mayashavin 

What do you think about it? For me, proposed solution is more readable :)

**Comment by Baroshem** [comment]
@daksamit 

As a creator of this idea, maybe you would like to start a pull request? I would be happy to review your code and give you some hints if needed ;)
