### ISSUE TITLE
[BUG] Mobile category tile differs from the designs

### ISSUE THREAD

**Issue by filrak** [vuestorefront/storefront-ui#1547]
![image](https://user-images.githubusercontent.com/15185752/100352969-1373a500-2fee-11eb-9d6c-87bb311c5a9e.png)
The spacings are different (its visible especialy on mobile category page) + multiline is allowed in components while its not on designs

**Comment by jakubmakielkowski** [comment]
https://github.com/DivanteLtd/storefront-ui/pull/1555
