### ISSUE TITLE
[BUG] SfCarousel doesn't look good when there are less than 4 products

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1548]
**Describe the bug**
SfCarousel doesn't look good when there are less than 4 products

![Zrzut ekranu z 2020-11-26 16-26-54](https://user-images.githubusercontent.com/46591755/100368962-8a1b9d00-3004-11eb-919c-7b6588c9cb06.png)

**How to reproduce**
1. Have less than 4 products in SfCarousel

**Expected behavior**
SfCarousel looks good with less than 4 products

**Comment by filrak** [comment]
To discuss.

Maybe if there is less than X (items per row) items we shouldn't display the carousel and just center the items
