### ISSUE TITLE
[BUG] Incoherent variable naming in SfTable

### ISSUE THREAD

**Issue by jakubmakielkowski** [vuestorefront/storefront-ui#1554]
**Describe the bug**
https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/shared/styles/components/organisms/SfTable.scss

Variables:
```
--table-border-heading
--table-border-heading-width
```
propably should be have word order like other variables:
```
--table-heading-border
--table-heading-border-width
```

Also `--_table-column-order` should be without underscore (typo).

If this issue will be accepted You could **assign me** for this.

**How to reproduce**
Visible in:
https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/shared/styles/components/organisms/SfTable.scss
and the docs:
https://docs.storefrontui.io/components/table.html#css-custom-properties-variables

**Comment by filrak** [comment]
Thanks for catching this issue! Fortunately we plan to remove most of the component-specific vars anyway so I'm closing it ;)

Thanks for taking the time to report this!
