### ISSUE TITLE
[BUG] SfMegaMenu typo in name of class inside scss for stories file

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1556]
**Describe the bug**
There is a typo bug in class name in SfMegaMenu scss file for stories.

**How to reproduce**
See it in code.

**Expected behavior**
Fix the typo, should be ".sf-mega-menu"

Other files should also be checked for typos.

**Actual behavior**

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by justyna-13** [comment]
@AdamPawlinski as far as I know the different class names were done on purpose. These styles aren't considered as a part of a whole component and that's why their names have different suffix and are outside styles of a particular component. MegaMenu isn't the only one component with such a case :)

**Comment by AdamPawlinski** [comment]
@justyna-13 what a shame... You are completely right :) I'm closing it.
