### ISSUE TITLE
[BUG] Add imports of scss to the stories and correct stories names in Storybook

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1579]
**Describe the bug**

After upgrading to new version of Storybook in few components imports odf stories scss should be added and the names of stories in Storybook created automatically should be corrected to the previous standard. 

**How to reproduce**
Check it in the Storybook e.g. SfFooter (has no import) and SfHeader.

**Expected behavior**
Proper imports and names of stories.

**Actual behavior**

**Code examples**

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by mayashavin** [comment]
@AdamPawlinski the scss is imported automatically. You don't need to do it. If you run localhost, you will see it's already included the scss stylings. If there isn't, clear your node_modules and run `yarn` again. LMK if you can't have it working
