### ISSUE TITLE
[BUG] SfRadio - bug in older browsers 

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1604]
**Describe the bug**
A lot of older browsers don’t support input events on radio buttons.

https://caniuse.com/input-event - note 4

Probably should be changed to a change event

**Comment by AdamPawlinski** [comment]
It is already merged to develop but to include in release earlier I added it to 0.10.4 hotfix.

**Comment by Baroshem** [comment]
@AdamPawlinski @justyna-13 

Can this issue be closed now? I think both Pull Requests are merged now.

**Comment by AdamPawlinski** [comment]
Yes it can be closed. Thx.
