### ISSUE TITLE
[BUG] get rid of all warinings in unit tests

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1609]
**Describe the bug**
There are warnings appearing after running unit tests. 

**How to reproduce**
Run yarn test:unit on your locale to see the warnings.

**Expected behavior**
There should be no warnings appearing.

**Actual behavior**
What actual happened.

**Code examples**

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/104430095-8e852080-5586-11eb-88bb-98058277f468.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Baroshem** [comment]
Merged
