### ISSUE TITLE
[BUG] SfReview date input bug

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1623]
**Describe the bug**
On SfReview story when changing date false value appears.

**How to reproduce**
When on SfReview change date value and see wrong value appearing.

**Expected behavior**
Properly showing date.

**Actual behavior**

**Code examples**

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/104716997-f7a49980-5728-11eb-9615-0f8c62cf23ab.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by mayashavin** [comment]
@AdamPawlinski This bug is related to the way we define date prop, which accept string as date, instead of parsing it from a datetime string. It requires changing the current design of our SfReview props.

**Comment by AdamPawlinski** [comment]
I think we should allow users to decide which date format they use and prop in SfReview should stay in string format. So I just changed the display format for this particular prop to text and now everything you pass is displayed as it is.
