### ISSUE TITLE
[FEATURE] SfStep CanGoForward

### ISSUE THREAD

**Issue by MildConcussion** [vuestorefront/storefront-ui#1629]
Right now we can only use canGoBack, but there is no canGoForward for steps. 
I would have to build some additional check using the "change" event, which is a pain and not sure if it's the best. 
Would be helpful to be able to only go back, but right now can skip steps.

PS. I see your docs have updated and the links on Github to start contributing are invalid.

**Comment by Baroshem** [comment]
Hi @MildConcussion 

Could you explain how do you see that feature to work? I have not seen other users having problem with that so I am not sure whether this is a very requested feature. Maybe you could also create a pull request with your desired solution? It would be easier to decide when we will see the proposed feature :)

**Comment by Baroshem** [comment]
Closing as there was no response from the author
