### ISSUE TITLE
[FEATURE] Storefront UI - Package Composition

### ISSUE THREAD

**Issue by Stevie-Ray** [vuestorefront/storefront-ui#1659]
Scaling component libraries is tough.

Mature companies maintain hundreds of components scattered across separate Storybooks. Different teams build their own libraries with custom requirements and dependencies.
Storybook 6.0 introduces Composition, a new feature that allows you to browse components from any Storybook inside your local Storybook.

https://medium.com/storybookjs/storybook-composition-af0da9084fba

This feature would make it easy to use Storefront UI with our companies custom components:

Implementation: 
https://github.com/storybookjs/design-system/blob/6b44d6efdf061a3f249df90b56eab5869d7da261/package.json#L109

**Comment by mayashavin** [comment]
What do you think @filrak ?

**Comment by Stevie-Ray** [comment]
@mayashavin @filrak any update on this?

**Comment by AdamPawlinski** [comment]
I add this issue to next hotfix, as it is also mentioned by other contributors and will be utilized.

**Comment by filrak** [comment]
@Stevie-Ray sorry for late response, we're working on this as @AdamPawlinski suggested!

**Comment by Stevie-Ray** [comment]
@AdamPawlinski I'm not sure if it works.. I've added the following and only seeing the "Storybook Design System" demo.

Does it work for you?

```
refs: {
    'storefront-ui': {
      title: 'Storefront UI',
      url: 'https://docs.storefrontui.io'
    },
    'design-system': {
      title: "Storybook Design System",
      url: "https://5ccbc373887ca40020446347-yldsqjoxzb.chromatic.com"
    }
  }
```

**Comment by K3vinF** [comment]
Hmmm... It looks like this doesn't work.
->https://storybook.js.org/docs/react/sharing/publish-storybook#cpp-level-1
https://docs.storefrontui.io/stories.json & https://docs.storefrontui.io/metadata.json return a 404 instead of a valid json

I guess this has to do with the hosting?

**Comment by Stevie-Ray** [comment]
@AdamPawlinski can you look into this?

**Comment by AdamPawlinski** [comment]
Sure I will tak a look at this tomorrow :)

**Comment by K3vinF** [comment]
Might it be as simple as running 
`npx sb extract` before deploying the storybook?

https://storybook.js.org/docs/react/sharing/storybook-composition#improve-your-storybook-composition

But this does not generate the metadata.json ?

**Comment by AdamPawlinski** [comment]
You are right, it doesn't work, right now. It could be related with our deploying process, so I will take a closer look. For now you can copy our repo and after running Storefront UI Storybook locally add it to your own. 
![Screenshot from 2022-01-27 08-44-18](https://user-images.githubusercontent.com/32042425/151313770-cd629677-16cc-4834-91a5-c3358c327ac7.png)
