### ISSUE TITLE
CND Version

### ISSUE THREAD

**Issue by Mashiane** [vuestorefront/storefront-ui#1661]
Good day

Thanks for your wonderful library. Is it possible to have a CDN version for the storefront-ui?

Thanks a lot.

**Comment by mayashavin** [comment]
@Mashiane Thank you for submitting an issue. At the moment we don't have a CDN version, since we want to leave the control of bundling to user entirely :). Please provide your use case so we can consider if we should provide a CDN in addition :). Have a nice day

**Comment by mayashavin** [comment]
cc @filrak

**Comment by Baroshem** [comment]
Closing as there was no response from the issue author. If there will be more interest in the topic we can reopen the issue.

**Comment by Mashiane** [comment]
Hi there, sorry for not responding, been a hectic time.

Yes, if possible, please. For the past year or so I started using Vuetify via CDN and I love it. This has been my exposure to VueJS as some of the tools I am using at the moment support CDN.

I want to create ecommerce apps using your wonderful framework, however have to work around these limitations which are something like a two edged sword for me. I like your framework because its strength is just this, ecommerce related content and does not purport to do everything else.

Thanks in advance.
