### ISSUE TITLE
[BUG] storybook 6 fixes 

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1663]
**Describe the bug**
List of bugs to be resolved in component stories:

- SfHeader add background color to story like it was before 
![image](https://user-images.githubusercontent.com/32042425/105475611-d4856700-5c9f-11eb-9e4b-6342957e05d2.png)

- SfColorPicker too large viewport in docs
![image](https://user-images.githubusercontent.com/32042425/105475900-3ba31b80-5ca0-11eb-9beb-572c88a24910.png)

- clickable elements show events in action element, but don't have any results:

1. SfStep - clicking on steps have no effect 
2. SfSidebar - click on close button has no result
3. SfBottomModal - click on close button has no result
6. SfColorPicker - button click event not seen on action   
7. SfComponentSelect  - button click event not seen on action   
8. SfFilter - checkbox click has no effect 
9. SfModal - click on close button has no result 
10. SfScrollable - click on show/hide buttons have no effect 
11. SfSearchbar - icon should be seen as default 
15. SfCollectedProduct - click event on quantity selector  not seen on action   
16. SfGroupedProduct - click event on quantity selector  not seen on action    
17. SfProductCardHorizontal - click event on quantity selector  not seen on action  

- events showed in action addon not destroyed when changing components, E.g. go to dropdown and click close button and then go to modal and click close you will see two actions emitted even if you click clear button.   
![image](https://user-images.githubusercontent.com/32042425/105486925-9ee87a00-5caf-11eb-9a18-d9dbdadebe8b.png)

- SfHeader has no implementation of new SfIcon/SfBadge API so adding items to cart and wishlist doesn't show aby number by the icon.

**Comment by mayashavin** [comment]
@AdamPawlinski All the click events should only emit the events but won't do anything, as a demonstration only. We have separate story for each use case if needed (such as Modal or Overlay). I don't think we need to handle the actual event, since it will affect the display code to copy.

**Comment by Baroshem** [comment]
I agree with Maya. Storybook is not a real application, it is just a presentation layer for people who would like to try SFUI. I think this issue can be closed then. Let me know what you think @AdamPawlinski :)

**Comment by Baroshem** [comment]
Closing the issue. If it will be needed, we can reopen it.
