### ISSUE TITLE
[BUG] SfFooter not working without JS

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1667]
**Describe the bug**
Without JS SfFooter has closed items. 

**How to reproduce**
On your project add SfFooter and turn off js in devtools then reload. See the effect. 

**Expected behavior**
There should be open items seen when JS is turned off. 

**Actual behavior**
SfFooter doesn't work without JS. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/105758768-edb43f00-5f4f-11eb-8f2a-609829d4439a.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Mavevolyn** [comment]
I have the same issue, but JS is activated. If I change the viewport to mobile and then back to desktop the navigation appears as it should.

**Comment by Baroshem** [comment]
Hey @Mavevolyn,

I wasn't able to reproduce it with JS enabled. Could you please provide some screenshots and screen recordings with reproduction steps? :)
