### ISSUE TITLE
[FEATURE] Add Cypress end-to-end tests

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1670]
**Describe how this feature will help us improve**
Add end-to-end tests using Cypress. 
As the first step it should cover basic behaviour of Checkout, Form, MyAccount and Log-in/Sign-in example pages.

**Is your proposal related to a problem?**
it's needed to have bug information before releases. Correcting components sometimes have an impact on other components which re higher in the hierarchy or even in whole pages. Checking everything manually is time-consuming so it's better to do it automatically. 

**Describe the solution you'd considered**

Probably we can use branch with nuxt generated pages  (https://github.com/vuestorefront/storefront-ui/tree/nuxt) and use them as the testing instance.

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by Baroshem** [comment]
MErged
