### ISSUE TITLE
Remove SfComponentSelect

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1682]
**Describe the bug**
Our `SfComponentSelect` (former `SfSelect`) can be removed - it's been replaced by a new `SfSelect` (the native one) and it's not recommended to use the old one anymore. Moreover, it uses `v-html` that is also not recommended.

**Comment by Mavevolyn** [comment]
I am against removing it. `SfComponentSelect` is a visuell styled component and `SfSelect` not. I preffer to use the `SfComponentSelect`. Maybe you could find a solution to make `SfSelect` styleable via a class or prop?

**Comment by justyna-13** [comment]
Unfortunately, there's no way to do this with native select so I think we can leave SfComponentSelect if it's still needed :)
