### ISSUE TITLE
[BUG] Typo in docs

### ISSUE THREAD

**Issue by ymaheshwari1** [vuestorefront/storefront-ui#1683]
**Describe the bug**
There are some typos in the documentation.

**How to reproduce**

**Expected behavior**

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Baroshem** [comment]
PR looks good to me! Rebase your branch so we could merge it ;)
