### ISSUE TITLE
[BUG] SfInput label and user text overlaps (checkout example)

### ISSUE THREAD

**Issue by Mavevolyn** [vuestorefront/storefront-ui#1691]
**Describe the bug**
The label and user input text overlaps at example pages. .form__element produces this problem in a form.

**How to reproduce**
1. Go to https://docs.storefrontui.io/?path=/story/pages-checkout--common
2. Click on input and write something
3. Click outside the input
4. See the overlap

**Expected behavior**
The label should placed above the input

**Actual behavior**
The label overlaps the user text

**Screenshots**
![image](https://user-images.githubusercontent.com/3956317/107618076-432b6400-6c51-11eb-91a5-bc9dcac294c3.png)

**Devices (please complete the following information):**
 - Device: [Desktop]
 - Browser: [chrome][88]

**Comment by Baroshem** [comment]
@justyna-13  @Mavevolyn 

PR (https://github.com/vuestorefront/storefront-ui/pull/1707) was merged. I am closing the issue.
