### ISSUE TITLE
[BUG] images now are not shown on ssr

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1699]
**Describe the bug**

All images now are not shown on ssr. Before refactor of SfImage there was noscript tag. 

**How to reproduce**
1. Go to demo page
2. Disable JS
3. See error

**Expected behavior**
Images are shown on ssr

**Actual behavior**
No images on ssr

**Comment by Baroshem** [comment]
Pull request was merged. Closing the issue.
