### ISSUE TITLE
[BUG] Product page -  gallery image overlaps part of product info

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1700]
**Describe the bug**
Image overlaps part of info on product page. 
 
![image](https://user-images.githubusercontent.com/32042425/107800484-1b2a2680-6d5f-11eb-8e20-18ec67e6bb72.png)

**How to reproduce**
1. On vsf demo site go to product page
2. change screen size below 1100px width, but more than mobile
3. see image overlapping product info (price and description). 

**Expected behavior**
Image should not overlap product info.

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Baroshem** [comment]
@AdamPawlinski 
Could you confirm that the problem still exists? I checked https://vsf-next-demo.storefrontcloud.io/p/38143c0c-c9b0-448c-93cd-60eb90d8da57/aspesi-shirt-h805-white but could not reproduce the issue 
![image](https://user-images.githubusercontent.com/37120330/114071183-200fe000-98a1-11eb-9354-40b53831929f.png)

**Comment by aniamusial** [comment]
Could not reproduce - possibly solved.
