### ISSUE TITLE
[BUG] Polish characters in custom font error

### ISSUE THREAD

**Issue by Malwurf** [vuestorefront/storefront-ui#1702]
### Describe the bug
Bug exist when I want to use a custom font on project.
I have a problem with `New Atten` from Typekit but I tested that bug with `Potta One` from Google Fonts.
Font is attached to the project correctly but polish diacritic marks not working correctly.
I have built `shopware-pwa project` with `yarn dev` and `yarn build` too and the result is the same.

### Steps
- Choose font e.g. from google fonts which include polish characters ęółśćź
- Attach to project on nuxt.config.js file
- Build project

### Additional context
- font for testing -> [Potta One](https://fonts.google.com/specimen/Potta+One?subset=latin-ext&preview.text_type=custom&preview.text=i%C5%9B%C4%87%20na%20&sidebar.open=true&selection.family=Potta+One)
- font for testing -> [New Atten](https://fonts.adobe.com/fonts/new-atten)
- System - Ubuntu 20.04.2 LTS
- shopware-pwa v. 0.6.1
- storefront-ui v. 0.7.18

### added link to nux.config.js
`    link: [
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Potta+One&display=swap'}
    ]`

**Comment by Baroshem** [comment]
Hi @Malwurf 

Have you tried to create your own component in Nuxt (something like Test.vue) with a simple div where you could check whether the polish characters work there? If they won't work, this problem is not related to Storefront UI. 
If the problem still occurs, please provide some simple reproduction repository :)

**Comment by Baroshem** [comment]
Closing as there was no response
