### ISSUE TITLE
[REFACTOR] SfFootrer - SfFooterColumn shouldn't use $parent

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1703]
**Describe the bug**

SfFooter (SfFooterColumn) needs to be refactored. 

```  computed: {
    open() {
      return this.$parent.isOpen.includes(this.title);
    },
  },
  mounted() {
    this.$parent.items.push(this.title);
  },
  methods: {
    toggle(payload) {
      this.$parent.toggle(payload);
    },
  },
```

we shouldn't assume $parent will be the component we are looking for

**Comment by Baroshem** [comment]
@justyna-13 

In https://github.com/vuestorefront/storefront-ui/pull/1737 I have refactored the logic of SfFooter to not use `$parent`. Instead I have use `provide/inject` syntax. I think it also solves this issue right?

**Comment by justyna-13** [comment]
@Baroshem that's right :)
