### ISSUE TITLE
[BUG] SfProductCard - picture and title shouldn't be only links

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1706]
**Describe the bug**
Now picture and title in SfProductCard are as SfLinks. There should be a possibility to have them also as SfButtons

**Comment by dt2patel** [comment]
Just out of curiosity, what is the advantage of using an SFButton-Pure vs SFLink? Is this just a semantic thing?

**Comment by AdamPawlinski** [comment]
I think listening for events is main advantage, also button can be a link if you pass a link prop to it so it's more elastic.

**Comment by Baroshem** [comment]
@AdamPawlinski @justyna-13 

PR was merged. I am closing the issue :)
