### ISSUE TITLE
[BUG] sf-button--full-width is not full-width with a link

### ISSUE THREAD

**Issue by rain2o** [vuestorefront/storefront-ui#1715]
**Describe the bug**
When using the `SfButton` component with the class `sf-button-full-width`, the `width: 100%` is getting overwritten by the `.sf-link` styles in the same component. This only happens if you use a link in the button component.

I have tested on the docs canvas, and I was able to reproduce the issue.

**How to reproduce**
1. Use `<SfButton>` with class `sf-button--full-width` and provide a value in the `link` prop
2. View the button.

**Expected behavior**
Button should be full-width

**Actual behavior**
Button has a width set to `var(--spacer-3xl)`

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```vue
<SfButton class="sf-button--full-width" link="https://google.com">
  Shop now
</SfButton>
```

**Additional context**
It looks like in `SfButton.scss`, the `&--full-width` styles come before all of the styles for `.sf-link`.  The following css is winning priority
```scss
.sf-link {
  --button-width: var(--spacer-3xl);
}
```

**Comment by justyna-13** [comment]
Thanks @rain2o! Would you like to fix this and open a PR? :slightly_smiling_face:
