### ISSUE TITLE
[BUG] Build failed error when added in a vuestorefront project

### ISSUE THREAD

**Issue by FbPalmabit** [vuestorefront/storefront-ui#1722]
**Describe the bug**
I can't add package "@storefront-ui/vue" in a project cloned from "vuestorefront"

**How to reproduce**
1. clone project https://github.com/vuestorefront/vue-storefront
2. yarn add @storefront-ui/vue -W
3. Import a SfComponent in some page (eg: `import { SfButton } from '@storefront-ui/vue'`)
4. yarn dev

**Expected behavior**
Project starts

**Actual behavior**
Build fails

**Error shown**

```
ERROR in ./node_modules/@storefront-ui/vue/src/components/organisms/SfHeader/SfHeader.vue?vue&type=style&index=0&lang=scss& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@storefront-ui/vue/src/components/organisms/SfHeader/SfHeader.vue?vue&type=style&index=0&lang=scss&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/stylePostLoader.js):
CssSyntaxError: /Users/**/Repositories/vuestorefront/node_modules/@storefront-ui/vue/src/components/organisms/SfHeader/SfHeader.vue:162:34: Unclosed bracket
    at Input.error (/Users/**/Repositories/vuestorefront/node_modules/postcss/lib/input.es6:104:16)
....
```

**Devices:**
 - Node 10

**Comment by Baroshem** [comment]
Hi @FbPalmabit,

The best way to add Storefront UI to the Vue Storefront project is by adding a theme to it.

Right after running `yarn dev` in vue storefront project you should get an error similar to this one:

`The theme you want to use does not exist. Please check theme installation: https://docs.vuestorefront.io/guide/installation/theme.html`

If you follow the steps mentioned in the link below, it should correctly add the Capybara theme (which is built using Storefront UI) to your project.

https://docs.vuestorefront.io/v1/guide/installation/theme.html#install-official-theme
