### ISSUE TITLE
[RFC] web performance analysis and improvement

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1726]
**Describe how this feature will help us improve**
SFUI should be analyzed to find opportunity to boost web performance according to Lighthouse scores and to make the whole library lighter according to bundlephobia/packagephobia. 

Lighthouse:

analyzed on branch nuxt with @storefront-ui/vue@0.10.3 version installed, on home page:
![image](https://user-images.githubusercontent.com/32042425/109937495-43a6a000-7ccf-11eb-9e16-cbb92608ba96.png)

Bundlephobia:

There is a build error when checking storefront-ui/vue package:

![image](https://user-images.githubusercontent.com/32042425/109932125-17d4eb80-7cca-11eb-93fb-6b593d8aa226.png)

package.json analysis from bundlephobia: 

![image](https://user-images.githubusercontent.com/32042425/109932097-0be92980-7cca-11eb-9584-2bbbe956a8c9.png)

packagephobia analysis:

![image](https://user-images.githubusercontent.com/32042425/109932070-025fc180-7cca-11eb-923b-eb4815cae1ba.png)

Webpack bundle analyzer:

![image](https://user-images.githubusercontent.com/32042425/109932044-fa078680-7cc9-11eb-9520-70e0ea46d3c4.png)

To consider: 
- using performance.measureUserAgentSpecificMemory() method available in Chrome 89 version to analyze memory consumption of web page,
- using application tab in devTools for analyzing disk usage and/or using StorageManager.estimate() method  
- anlayze CPU usage in performance monitor tab https://developers.google.com/web/updates/2017/11/devtools-release-notes#perf-monitor 
- removing third-party packages like: vue-leaflet (hard because store locator is based on it), vue-drag-and-drop, simplebar (used for styling scrollbar in SfScrollable),  glidejs (already problematic, because of sending requests on every slide change)

More about performance analysis in this article https://nolanlawson.com/2021/02/23/javascript-performance-beyond-bundle-size/.

**Is your proposal related to a problem?**
Web performance is crucial for ecommerce applications so it is needed to make an improvement also in SFUI library

**Describe the solution you'd considered**
The first part is to identify bottlenecks and possible ways for improvement.
The second is to find solutions and add issues connected to this issue.

The below list should expand as we find new issues concerning performance.
Currently we have identified following issues:
- [accordion should work without js #1668](https://github.com/vuestorefront/storefront-ui/issues/1668)
- [footer also should work properly without js #1667](https://github.com/vuestorefront/storefront-ui/issues/1667)
- [adapting header to better performance #1552](https://github.com/vuestorefront/storefront-ui/issues/1552)
- [reducing package size  #1717](https://github.com/vuestorefront/storefront-ui/issues/1717)
- [adding SfSkeleton component to reduce cumulative layout shift #1607  ](https://github.com/vuestorefront/storefront-ui/issues/1607)

**Additional context**
Anything you would like to add but was not sure which section it fits.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-42) by [Unito](https://www.unito.io)

**Comment by bensinca** [comment]
Leaflet is starting to cause problems https://github.com/vuestorefront/storefront-ui/issues/2499

**Comment by AdamPawlinski** [comment]
I'm closing the issue as it is not in the scope of[ the LTS](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
