### ISSUE TITLE
[BUG] Product image not appearing in Mozilla Firefox

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1732]
**Describe the bug**

On Mozilla Firefox browser, main product images is not appearing correctly. Also I noticed that the select for size has default styling.

**How to reproduce**

**Expected behavior**

I expect it to work the same as in other browsers like Google Chrome 
![image](https://user-images.githubusercontent.com/37120330/110017789-e4747a00-7d26-11eb-8b78-a3177626de8f.png)

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

![image](https://user-images.githubusercontent.com/37120330/110017681-c60e7e80-7d26-11eb-893f-3e873b7ad801.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by AdamPawlinski** [comment]
@Baroshem  Could you please write down in what envirnonment did you find this bugs (storybook, next theme, local etc.)?  Maybe this two things could be in two different tasks, wdyt? :) Thanks.

**Comment by Baroshem** [comment]
About the environment, I tested it on Vue Storefront Next project with the up to date `next` branch. For some strange reason image has classess `sf-image` and `false`. Please see attached screenshot.
![image](https://user-images.githubusercontent.com/37120330/110236317-633f0200-7f35-11eb-839c-2104c4ff408d.png)
It disappears (adds correct class) when you interact with the page source, i.e. edit styles or add classess.

For the second problem, yes you are right. It should be a separate issue. I will create it right away :) 
https://github.com/vuestorefront/storefront-ui/issues/1736

**Comment by AdamPawlinski** [comment]
Great thank you :)

**Comment by sagital** [comment]
I think the problem might be in `@storefront-ui/vue/src/components/molecules/SfGallery/SfGallery.vue` 

`SFImage` is passed in an attribute, `:lazy="false"` but looking at the accepted props it should be `:loading="eager"`

**Comment by Baroshem** [comment]
Issue was merged
