### ISSUE TITLE
[BUG] Possible to open SfSelect when it is disabled

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/storefront-ui#1734]
**Describe the bug**
Possible to open SfSelect while it has `disabled` props equal `true`

**How to reproduce**
1. Go to https://docs.storefrontui.io/?path=/story/components-molecules-select--common
2. Set `disabled` to the `true`
3. Click on the Select on the preview
4. It is disabled but opened

**Expected behavior**
Impossible to open select while it has `disabled` equal `true`

**Actual behavior**
Possible to open select while it has `disabled` equal `true`

**Devices (please complete the following information):**
 - Device: Desktop
 - OS: Ubuntu 20.04
 - Browser: Chrome 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
I am pretty sure it is all about forwarding `disabled` props and applying it to the `select`.

**Comment by Baroshem** [comment]
@justyna-13 @Fifciu 
Pull request was merged. I am closing this issue
