### ISSUE TITLE
[BUG] Images sides are cropped

### ISSUE THREAD

**Issue by sagital** [vuestorefront/storefront-ui#1746]
**Describe the bug**
Images are cropped.

**How to reproduce**
1. Go to [](https://docs.storefrontui.io/?path=/story/pages-product--common)
2. Click on 'the second or fourth image' 

**Expected behavior**
I want to see the whole picture because I might have important details on the sides of the picture

**Actual behavior**
The sides are cropped

**Screenshots**

![Screenshot 2021-03-18 at 20 41 45](https://user-images.githubusercontent.com/45870752/111680004-6d60da80-882a-11eb-8ab2-79a67a987f0f.png)

**Devices (please complete the following information):**
 - Device: [ Desktop]
 - OS: [e.g. MacOs]
 - Browser: [e.g chrome ][latest]

**Comment by Baroshem** [comment]
Hi @sagital 
SfImage accepts a prop of `width` and also you can add your own CSS styling to adjust SfImage to correctly display the image so that it won't be cropped (add a class to SfImage that will target image tag inside it).

**Comment by Baroshem** [comment]
Closing the issue as there was no follow up
