### ISSUE TITLE
[BUG] Some links in the docs are not working

### ISSUE THREAD

**Issue by ymaheshwari1** [vuestorefront/storefront-ui#1749]
**Describe the bug**
Link to some part of the docs are not working as expected.

**How to reproduce**
1. Go to https://docs.storefrontui.io/?path=/story/setup-installation--page#customization
2. Click on the link in the section (`here`)

**Expected behavior**
We should get redirected to the specific page in the doc

**Actual behavior**
Currently getting a blank page.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Baroshem** [comment]
@ymaheshwari1 
I left a comment in your PR as I am not sure if it's ready for review :)
