### ISSUE TITLE
[BUG] SfMegaMenu - bar shows on desktop when in production mode

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1751]
**Describe the bug**
When in production mode SfMegamenu shows the bar in the desktop view but it should be visible only in mobile view.

**How to reproduce**
1. run in production mode
2. go to header with SfMegamenu
3. see the bar showing in desktop mode. 

**Expected behavior**
Bar shoudl be hidden in desktop view. 

**Actual behavior**

**Code examples**
Bug appears because SfBar classes has greater specifity than custom properties in SfMegamenu, so this could help:
``` 
.sf-mega-menu__bar.sf-bar {
  display: flex;
  @include for-desktop {
    display:  none;
  }
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/32042425/111968080-15132c80-8af9-11eb-83d3-3437ee845ac7.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Baroshem** [comment]
Issue was merged
