### ISSUE TITLE
[BUG] SfStoreLocator: unable to use locale in the SfStoreLocator

### ISSUE THREAD

**Issue by ymaheshwari1** [vuestorefront/storefront-ui#1752]
**Describe the bug**
Unable to update the label `Stores Found` as per the locale in the store locator component.
https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.vue#L6

**How to reproduce**

**Expected behavior**
We should be able to update the label.

**Actual behavior**
When changing the locale, the label `Stores Found` does not update as per the locale.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

Related issue: https://github.com/vuestorefront/storefront-ui/issues/226

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-46) by [Unito](https://www.unito.io)

**Comment by Baroshem** [comment]
hi @ymaheshwari1 

The label Stores found is not updated because it is hardcoded. If you think it should be a reactive prop, please create a pull request. We will be happy to review it :)

**Comment by AdamPawlinski** [comment]
Hi @ymaheshwari1, would you mind if I close the issue? I suppose it is no longer valid, as @Baroshem mentioned, wdyt?

**Comment by ymaheshwari1** [comment]
> Hi @ymaheshwari1, would you mind if I close the issue? I suppose it is no longer valid, as @Baroshem mentioned, wdyt?

Sure, we can close this.

**Comment by AdamPawlinski** [comment]
Thanks, @ymaheshwari1. Have you already tried the[ new SFUI](https://docs.storefrontui.io/v2/)? Would you like to share some feedback? I know that you contribute to SFUI1 a lot and we appreciate that, so if you will be interested in participating also in the new version it would be great :+1:

**Comment by ymaheshwari1** [comment]
@AdamPawlinski Thanks.

Just looked around the basic components of the new SFUI version, SFUI2 looks good to me. I would love to contribute to the new version and will explore the code in upcoming days.

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 Thanks very much. It would be great if you could add some ideas for new features or if you find bugs just add issues. Great to have you working with us :+1:
