### ISSUE TITLE
[BUG] SfCircleIcon - remove unused code

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1754]
**Describe the bug**
SfCircleIcon component has SfIcon component inside. SfIcon doesn't have badge props anymore. These props should be deleted 

**How to reproduce**
1. Go to SfCircleIcon code
2. See badge props  for SfIcon: `badge-label` and `has-badge` that aren't part of SfIcon

**Comment by VanessaKeeton** [comment]
Hey all,

I wanted to pick this up, and it's my first time contributing. Two things:

When pushing the linter ran and a ton of unrelated files were updated by the linter. I didn't expect that it would lint files I didn't edit, so I am hesitant to push that up to my fork. Should I just go with it or push --no-verify it so it only adds my change?

Secondly, there is a formatting error. I didn't see the commit formatting requirements in the dev getting started docs. How should I format the commit message?

Thanks!

**Comment by justyna-13** [comment]
Hi @VanessaKeeton! Thanks for your help :) Regarding unrelated files, it's better to not include them in your PR. Recently we had a lot going on and soon linting will be fixed by our team. When it comes to formatting errors for commit, we use Conventional Commits - you can read more in our docs-  https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-branching-guidelines--page

**Comment by VanessaKeeton** [comment]
Awesome! Thank you :)
