### ISSUE TITLE
[FEATURE] Progressive Loading of Components/Pages

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1759]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

To make the user experience better, we could implement a functionality of progressive loading.

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
A concise description of your preferred solution. Things to address include:

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Loading

  - Details of the technical implementation
  - Tradeoffs made in design decisions
  - Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by AdamPawlinski** [comment]
After research I have folowing thoughts to discuss: 

- obviously we cannot use lazy loading on route level (per page), but it should be considered by users, similarly like for components 
- we can use components lazy loading with intersection observer (implemented in most of browsers with 93% users globally) to know when it becomes visible and load them. Proposed solution: 
```js
export default function lazyLoadComponent({
  componentFactory,
  loading,
  loadingData,
}) {
  let resolveComponent;

  return () => ({
    component: new Promise((resolve) => {
      resolveComponent = resolve;
    }),
    loading: {
      mounted() {
        if (!('IntersectionObserver' in window)) {
          componentFactory().then(resolveComponent);
          return;
        }

        const observer = new IntersectionObserver((entries) => {
          observer.unobserve(this.$el);
          componentFactory().then(resolveComponent);
        });
        observer.observe(this.$el);
      },
      render(createElement) {
        return createElement(loading, loadingData);
      },
    },
  });
}
``` 
and this function can be used as helper, like this: 
```vue
import SkeletonBox from './components/SkeletonBox.vue';

export default {
  name: 'App',
  components: {
    MediaObject: lazyLoadComponent({
      componentFactory: () => import('./components/MediaObject.vue'),
      loading: SkeletonBox,
    }),
  },
};
```
_I used examples from this article https://markus.oberlehner.net/blog/lazy-load-vue-components-when-they-become-visible/._ 
I would also conside adding error component to display sth when it goes wrong.
This helper function can be applied only for components that is needed to be lazy load (not critical ones).
Probably we should implement some kind of skeleton for whole components (currently it is prepared for html elements).

- I would also try using webpack prefetching(loaded in browser idle time)/preload(loaded in parallel with parent chunk) for lazy loaded components: 
`import(/* webpackPrefetch: true */ "DashboardPage")` 
but it should be configurable by the user, who must decide which component to preload or prefetch, there can be even prefetching order added  e.g. `webpackPrefetch: 42` will be prefetched before `webpackPrefetch: 1`
Even if we use rollup as our librabry prefetching/preloading chunks will be applied depending on what user utilize in his project with SFUI. 

- lazy loading of nested elements/components needs to be further investigated on every molecule/organism component - it can be useful when sth is not showed in first rendering e.g. items in SfCarousel.

**Comment by AdamPawlinski** [comment]
As agreed during team meeting this task should be redefined to adapt components to progressive enhancement. So we should focus on refactor components to be available without js and then add features making them fully usable. There should be Sidebar or modal components adapted for sure.

**Comment by AdamPawlinski** [comment]
I'm closing the issue as it is not in the scope of[ the LTS](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
