### ISSUE TITLE
[FEATURE] Provide an option to exclude closing button for SfNotification component

### ISSUE THREAD

**Issue by DavidGolodetsky** [vuestorefront/storefront-ui#1765]
**Describe how this feature will help us improve**
I find it useful to have an option to exclude the closing button for SfNotification component, in case if it's a static notification, or it couldn't be dismissed. 

**Is your proposal related to a problem?**
In order to avoid showing the closing button with the current component, I had to pass an empty `div` to the `close` slot, which doesn't look nice. 

**Describe the solution you'd considered**
I think it would be nice to have a prop e.g. "Persistent", which would be a switcher for the closing button. An example code attached.

![photo_2021-04-10_17-51-42](https://user-images.githubusercontent.com/32278933/114274422-fb457500-9a26-11eb-9d54-45f273eb724f.jpg)

**Comment by Baroshem** [comment]
Hi @DavidGolodetsky 
Thanks for reaching!

I can see potential use cases of this change. 
@justyna-13 @AdamPawlinski what do you think?

**Comment by Baroshem** [comment]
@DavidGolodetsky 

Would you like to create a pull request with this change? I think it will be useful to have this functionality in SFUI :)

**Comment by DavidGolodetsky** [comment]
Yes, I'll try:)

**Comment by Baroshem** [comment]
Cool! Later today I will create a branch 0.10.9 so you can create your branch from it. I will add your issue to 0.10.9 roadmap as well.
