### ISSUE TITLE
[BUG] SfIcon div wrapping element causes ssr hydration problems

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1766]
**Describe the bug**
It's connected with [#5745](https://github.com/vuestorefront/vue-storefront/pull/5745) Next issue.
SfIcon when used in SfMenuItem creates wrong HTML syntax: div inside a button what causes the mismatch error during hydration. So this should be replaced by other element e.g. <Fragment>. 

**How to reproduce**
1. run Next CT theme 
2. go to category page 
3. refresh and see the error in console 

**Expected behavior**
There should be proper syntax and therefore hydration without error. 

**Actual behavior**
Hydration error appears in console and blocks whole page from rendering properly. 

**Code examples**

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Baroshem** [comment]
Issue was merged
