### ISSUE TITLE
[FEATURE] SfQuantitySelector emit blur event 

### ISSUE THREAD

**Issue by badz0** [vuestorefront/storefront-ui#1770]
**Describe how this feature will help us improve**
If a user leaves an empty input it would allow developers to handle it

**Is your proposal related to a problem?**
I want to handle a blur event on input.

**Comment by Baroshem** [comment]
I think it is a good idea to have this blur functionality so that we can react to it if needed. Also, very good that ypu have already created a pull request with that feature 😉

**Comment by Baroshem** [comment]
Well done @badz0! If you have any more improvement ideas let us know, or just create an issue and start PR right away 😃

**Comment by badz0** [comment]
Thank you guys for a quick merge 🙂
