### ISSUE TITLE
[BUG] SfQuantitySelector let parent component handle '' and 0 input

### ISSUE THREAD

**Issue by badz0** [vuestorefront/storefront-ui#1772]
**Describe the bug**
I don't want SfQuantitySelector to emit `1` when a user inputs `''` or `0`.

**How to reproduce**
1. Go to vsf demo https://vsf-next-demo.storefrontcloud.io/
2. Add an item to the basket
3. Open basket
4. Set slow network mode in dev tools to reproduce the issue easier
5. Clear quantity input
6. Enter number 5 (for example) to trigger cart update and look into the network to see if the request was sent
7. Before you get a response from the server clear quantity input
8. Wait till you get the response and see that your input is `5` instead of `''`

**Expected behavior**
I expect the input to remain empty when it's empty. 

**Actual behavior**
After getting the response the input displays the last entered number because the response triggers rerendering. 
To handle this I need to set `qty` prop to `''` but doing this would trigger [watcher](https://github.com/vuestorefront/storefront-ui/blob/52a5b108337dbd124ae0d434b145b09f0a608bc5/packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue#L55) inside QuantitySelector and it would emit `1`. 

**Additional context**
There are other inconveniences if I want to handle `0` input.
I think you need to allow developers to handle `NaN` inputs on their own 🙂

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-48) by [Unito](https://www.unito.io)

**Comment by Baroshem** [comment]
Hi again @badz0 ;)

Your reasoning and issue description makes sense however I would like to first get the opinion of @justyna-13 or/and @AdamPawlinski.

**Comment by AdamPawlinski** [comment]
I think it was created with SfAddToCart in mind and in this use case there is no sense in adding 0 items to cart. But SfQuantitySelector can be used different way, so getting rid of this watcher makes sense. However I would keep some way of setting default value for developers to choose, maybe by adding new prop `defaultQty`, wdyt?

**Comment by justyna-13** [comment]
There was this possibility before but it was considered as a bug - as Adam says there's no reason to send 0 or ' '. However, if it's really needed for some reasons we can think about overriding this default behavior. Also if there is a good reason to change this please share it with us

**Comment by AdamPawlinski** [comment]
Maybe adding min and max values will solve this as mentioned in this issue [#1824](https://github.com/vuestorefront/storefront-ui/issues/1824)

**Comment by badz0** [comment]
I think min max won't solve my issue :(
I see that you removed watcher, but I still would like to be able to set `0` and some empty value to input. Maybe lets add prop to pass custom `handleInput `?
