### ISSUE TITLE
[BUG] SfGallery - missing alt for an image

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1782]
**Describe the bug**
There is no alt for an image in SfGallery with outsize zoom 

**How to reproduce**
1. Go to SfGallery
2. Click on With Outside zoom
3. Move your mouse on an image to zoom and see red lines (missing alt)

**Expected behavior**
Zoomed image without red lines

**Comment by loongluangkhot** [comment]
Hi! Could you assign this to me?

**Comment by justyna-13** [comment]
Hi @loongluangkhot :slightly_smiling_face: sure, this task is yours now. Thanks for helping!
