### ISSUE TITLE
[FEATURE] SfSidebar refactor to follow progressive enhancement pattern

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1783]
**Describe how this feature will help us improve**
This issue is subtask to #1759 
Refactor SfSidebar to be adjusted to progressive enhancement design pattern.

**Is your proposal related to a problem?**
Component should be accesible for user with slow machines and older browsers and allow for better web performance experience.

**Describe the solution you'd considered**
Replace js with css solutions when possible. Simplify scripts used. 

**Additional context**
Anything you would like to add but was not sure which section it fits.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-49) by [Unito](https://www.unito.io)

**Comment by Baroshem** [comment]
https://codepen.io/MacTavish--0101/pen/mdexGOv

**Comment by AdamPawlinski** [comment]
I'm closing the issue as it is not in the scope of[ the LTS](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page). I
