### ISSUE TITLE
[BUG] Update Docs - Node 14+ incompatible (node-sass 4.13.1), Vue 3 incompatible

### ISSUE THREAD

**Issue by RikkiMasters** [vuestorefront/storefront-ui#1802]
**Describe the bug**
I don't know if this is something I'm doing, but I can't find any info. 
Install is failing using Node v16 or Vue 3. Downgrading to Node v12 and Vue v2 works fine. Does this sound right? I've found nothing in the docs except "Storefront UI is working out of the box with Nuxt and Vue CLI 2 & 3".

**NPM 16 Issue**
Storefront UI depends on node-sass 4.13.1 which is not compatible with Node 14+.  I get the following:
`$ npm install --save @storefront-ui/vue --legacy-peer-deps`
`npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.`
`npm ERR! code 1`
`npm ERR! path /hello-world/node_modules/node-sass`
`npm ERR! command failed`

**VUE 3**
Storefront UI depends on Vue 2.6.x
`npm ERR! While resolving: hello-world@0.1.0`
`npm ERR! Found: vue@3.0.11`
`npm ERR! node_modules/vue`
`npm ERR!   vue@"^3.0.0" from the root project`
`npm ERR! `
`npm ERR! Could not resolve dependency:`
`npm ERR! peer vue@"^2.6.x" from @storefront-ui/vue@0.10.5`
`npm ERR! node_modules/@storefront-ui/vue`
`npm ERR!   @storefront-ui/vue@"*" from the root project`

**How to reproduce**
1. Install Node 16
2. Install Vue 3
3. run `npm install --save @storefront-ui/vue`

**Expected behavior**
Vue storefront installs

**Actual behavior**
Could not resolve dependency for Vue 2.6.
Fails when downloading node-sass

**Devices (please complete the following information):**
 - OS: MacOS Big Sur

**Comment by Baroshem** [comment]
Hi @RikkiMasters 

Storefront UI is written in Vue 2. We are currently not planning to port it to Vue 3 as this requires a lot of work. We will think about it later. In the version 0.10.8 we have updated a version of Sass and that should enable to work with Storefront UI in Node 16. Let us know if that fixed the issue.
