### ISSUE TITLE
[BUG] SfRadio - can't get @click.native event

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1803]
**Describe the bug**
Now it's impossible to get @click.native event in SfRadio component

**Comment by Baroshem** [comment]
@justyna-13 

Could you provide more details? I started a project in nuxt branch and added a @click.native event to SfRadio component in Shipping and it is working correctly. 

```js
<SfRadio
  v-for="item in shippingMethods"
  :key="item.value"
  v-model="shippingMethod"
  :label="item.label"
  :value="item.value"
  name="shippingMethod"
  :description="item.description"
  class="form__radio shipping"
  @input="updateField('shippingMethod', $event)"
  @click.native="handleClick"
>
```

```js
methods: {
  handleClick() {
    console.log('click')
  }
}
```

![image](https://user-images.githubusercontent.com/37120330/120538589-fe396200-c3e6-11eb-8e98-2c0b67b2b7f9.png)
