### ISSUE TITLE
[FEATURE] Integration with TailwindCSS

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1807]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

There is an increasing demand from the community for working example of integration with TailwindCSS.

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
A concise description of your preferred solution. Things to address include:

  - Details of the technical implementation
  - Tradeoffs made in design decisions
  - Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.

https://tailwindcss.nuxtjs.org/

**Additional context**
Anything you would like to add but was not sure which section it fits.

Comments from the community about using TailwindCSS:
```
Hi, I did exactly that, but unfortunately Vue Storefront 2 doesn't work with  newest  https://tailwindcss.nuxtjs.org/ module because of vuestorefront ui errors during build time. 

But when I installed older tailwindcss nuxt module version and install postcss 7 then error disappeared. 

My gues is that storefront ui is not compatible with newest postcss version
```

```
working if disabled 'postcss-custom-properties'
```
![image](https://user-images.githubusercontent.com/37120330/118825348-e3310300-b8ba-11eb-828c-4f897b158dd0.png)

https://docs.storefrontui.io/?path=/docs/setup-css-customization--page#tailwind-customization

**Comment by fhaertig** [comment]
This saved my day, thanks a bunch!

**Comment by AndrewBogdanovTSS** [comment]
There will also be great to see an integration tutorial for WindiCSS - the workflow should be pretty similar to TailwindCSS
