### ISSUE TITLE
[BUG] Cart not scrolling on iOS12

### ISSUE THREAD

**Issue by michal-kwiatkowski** [vuestorefront/storefront-ui#1809]
**Describe the bug**
Cart view is not scrollable on Safari on old iOS versions - reported by BabyBunting on iPhone6 (iOS12) confirmed on https://demo-enterprise.europe-west1.gcp.storefrontcloud.io/ on old iPad (iOS10)

**How to reproduce**
1. Go to PLP
2. Add several >5 products to the basker
3. Click basket (overlay with basket items appears from the right side)

**Expected behavior**
User should be able to scroll in case there are more products in basket than are visible on the screen.

**Actual behavior**
User is not able to scroll

**Comment by justyna-13** [comment]
It works in Storybook so the problem isn't on the SFUI side
