### ISSUE TITLE
[BUG] SSR missmatch for SfHeaderNavigationItem and SfBanner on Mobile

### ISSUE THREAD

**Issue by RikkiMasters** [vuestorefront/storefront-ui#1813]
**Describe the bug**
Components using mapMobileObserver are triggering SSR missmatch when refreshing in mobile view. isMobile is returning false on the server and true on the client.

The header bar doesn't render correctly and sticks to the top of the screen.

**How to reproduce**
1. Go to Chrome mobile view
2. Reload page
3. See error in console

**Expected behavior**
SSR and Client match

**Actual behavior**
Missmatch of isMobile causing errors. Header bar not rendering correctly.

**Code examples**

```
//Write code here
```
```
<template>
  <SfHeader
    logo="https://www.svgrepo.com/show/9395/ribbon-banner-silhouette.svg"
    :title="title"
    :active-icon="activeIcon"
    :search-placeholder="searchPlaceholder"
    :search-value="searchValue"
    :cart-icon="cartIcon"
    :wishlist-icon="wishlistIcon"
    :is-sticky="isSticky"
    :account-icon="accountIcon"
    :cart-items-qty="cartItemsQty"
    :wishlist-items-qty="wishlistItemsQty"
    @click:cart="alert('@click:cart')"
    @click:wishlist="alert('@click:wishlist')"
    @click:account="alert('@click:account')"
    @change:search="searchValue = $event"
  >
    <template #navigation>
      <SfHeaderNavigationItem
        v-for="item in navigation"
        :key="item.title"
        :label="item.title"
        :link="item.link"
      />
    </template>
  </SfHeader>
</template>

<script>
import { SfHeader, SfLink } from "@storefront-ui/vue";

export default {
  name: "Header",
  components: {
    SfHeader,
    SfLink,
  },
  data() {
    return {
      navigation: [
        {title: "Cat1", link: "/cat1"},
        {title: "Cat2", link: "/cat2"},
        {title: "Cat3", link: "/cat3"}
      ],
      searchValue: "",
      title: "",
      activeIcon: "account",
      isSticky: false,
      searchPlaceholder: "Search for items",
      cartIcon: "empty_cart",
      wishlistIcon: "heart",
      accountIcon: "profile",
      cartItemsQty: "0",
      wishlistItemsQty: "0",
    };
  }
};
</script>
```

**Screenshots**
After adding `console.log('isMobile: ' + this.isMobile)` in SfHeaderNavigationItem isVisibleOnMobile computed.
![image](https://user-images.githubusercontent.com/11843864/119744801-acdc2080-be84-11eb-89fa-34b525d28ae0.png)

**Additional context**
Node: 12.22.1
Nuxt: 2.15.3
Storefront UI: 0.10.6

**Comment by Baroshem** [comment]
If we change `v-is` in the places where there is a problem with Missmatch to `v-show` the warning disappears but the error is still there. From what I have seen, it may be required to refactor mobile-observer from a helper function to a mixin. But there might be other ideas as well.
