### ISSUE TITLE
Megamenu

### ISSUE THREAD

**Issue by mananthnov** [vuestorefront/storefront-ui#1814]
Hi, I have been using "version": "1.1.3". Can someone please help me how to  use Megamenu?

**Comment by Baroshem** [comment]
Hi @mananthnov 

- Storybook with SfMegaMenu -> https://docs.storefrontui.io/?path=/story/components-organisms-megamenu--common
- Code of SfMegaMenu -> https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.vue

If you cannot find answers to your questions there, please provide more details on what you are looking for.

**Comment by mananthnov** [comment]
Hi Baroshem, 

Thanks for your response. Could you please help me how and where to place the megamenu code in AppHeader.vue. 

Please find the attachment, AppHeader.vue
[AppHeader.zip](https://github.com/vuestorefront/storefront-ui/files/6602205/AppHeader.zip)

**Comment by Baroshem** [comment]
You can follow a pull request created by one of our core members in Vue Storefront. It presents just that (MegaMenu in AppHeader). If you have any further questions, please let me know. If that's enough you can mark the issue as resolved. Thanks and happy coding!

**Comment by Baroshem** [comment]
Closing the issue as it probably explained the usage of Megamenu. If not, please reopen the issue.
