### ISSUE TITLE
[BUG] SfButton as a link - wrong color on hover 

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1816]
**Describe the bug**
Text in SfButton (as a link / with link prop) on hover state is black and should be white

How it is:
![Screenshot from 2021-05-31 12-36-03](https://user-images.githubusercontent.com/46591755/120181228-0b9af480-c20d-11eb-8515-fab33a28e63d.png)
 
How should be:
![Screenshot from 2021-05-31 12-44-33](https://user-images.githubusercontent.com/46591755/120181900-f83c5900-c20d-11eb-874e-fb684ef94b1c.png)

**How to reproduce**
1. Use SfButton as a link 

**Expected behavior**
SfButton as a link should look like regular SfButton

**Comment by Patil2099** [comment]
I would love to work on it @justyna-13.

**Comment by justyna-13** [comment]
@Patil2099 great! :) It would be great to have this fix for our newest hotfix-0.10.7 so please make your PR to `hotfix-0.10.7` branch.  Thanks for your help!

**Comment by Baroshem** [comment]
Hi @Patil2099,

Are you working on this issue?

**Comment by AdamPawlinski** [comment]
We can close this issue. SfButton layout is shows proper colors on hover.

**Comment by Baroshem** [comment]
@AdamPawlinski 

This problem is related to the SfButton as link.

**Comment by Baroshem** [comment]
Sorry @AdamPawlinski 

Closing the issue. I am dumb :D
