### ISSUE TITLE
[BUG] SfSelect Causing SSR Missmatch

### ISSUE THREAD

**Issue by RikkiMasters** [vuestorefront/storefront-ui#1822]
**Describe the bug**
SfSelect is causing an SSR missmatch and doesn't display correctly.

![image](https://user-images.githubusercontent.com/11843864/120943899-93ab5d80-c729-11eb-8257-2b3b18db2fe0.png)

I tried using SfComponentSelect as an alternative but performance is slow with approx 500 options.

**How to reproduce**
1. In a Nuxt project, use the example below, or use the "Product" page example which contains the element.

**Expected behavior**
Server and client match

**Actual behavior**
Errors in console and the element doesn't display correctly.

![image](https://user-images.githubusercontent.com/11843864/120944222-43cd9600-c72b-11eb-977e-18bb1eb10730.png)

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
<template>
  <SfSelect
    label="Test"
    class="sf-select--underlined product__select-size"
    :required="true"
  >
    <SfSelectOption key="1" value="1">
      <SfProductOption label="option 1"></SfProductOption>
    </SfSelectOption>

    <SfSelectOption key="2" value="2">
      <SfProductOption label="option 2"></SfProductOption>
    </SfSelectOption>
  </SfSelect>
</template>
<script>
import {
  SfSelect,
  SfProductOption,
} from "@storefront-ui/vue";
export default {
  components: {
    SfSelect,
    SfProductOption,
  }
};
</script>
```

**Additional context**
Node: 14.17.0
Nuxt: 2.15.3
Storefront UI: 0.10.6

**Comment by justyna-13** [comment]
Hi @RikkiMasters, thanks for reporting this issue. It came out there was a wrong example of how to use SfSelect in our stories. The right code should be without SfProductOption. Regarding correct displaying - there should be v-model for SfSelect so that it knows when an option is selected. Below is an example:
```
<template>
  <SfSelect
   v-model="selectedValue"
    label="Test"
    class="sf-select--underlined product__select-size"
    :required="true"
  >
    <SfSelectOption key="1" value="1">
      option 1
    </SfSelectOption>

    <SfSelectOption key="2" value="2">
      option 2
    </SfSelectOption>
  </SfSelect>
</template>
<script>
import {
  SfSelect,
  SfProductOption,
} from "@storefront-ui/vue";
export default {
  components: {
    SfSelect,
    SfProductOption,
  },
data() {
    return {
      selectedValue: '',
    }
  }
};
</script>

**Comment by RikkiMasters** [comment]
Thanks @justyna-13, this is working
