### ISSUE TITLE
[FEATURE] Create Grid system to be able to position elements on the page without writing CSS

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1829]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

![image](https://user-images.githubusercontent.com/37120330/121139342-f17a9b00-c838-11eb-8b0d-47d318784be1.png)

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
A concise description of your preferred solution. Things to address include:

  - Details of the technical implementation
  - Tradeoffs made in design decisions
  - Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.

**Additional context**
Anything you would like to add but was not sure which section it fits.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-52) by [Unito](https://www.unito.io)

**Comment by dt2patel** [comment]
This is an interesting feature. To improve the flex box half even system there are some PRs in Capybara that refactored this with CSS Grid. That allows users to customize the grid and layout in a fairly simple manner using grid-areas to explicitly place form items. Here is a link, let me know what you think:

https://github.com/vuestorefront/vsf-capybara/pull/607/files#diff-5ff6de4cbae727c9cca9ba15362e267330c0a4ee9a58564eeff4d8a36b880cf7R133
