### ISSUE TITLE
[BUG] SfComponentSelect size prop not used

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/storefront-ui#1835]
**Describe the bug**
Currently the size property of `SfComponentSelect` is not being used, so there is no way to restrict the height of the options list

**Expected behavior**
The value of the size prop is used to determine the height of the options list.

**Actual behavior**
The options list height is not restricted

**Additional context**
https://github.com/vuestorefront/storefront-ui/blob/dbb9b7a5e51cb9606b11335441bb1b707f83e98c/packages/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue#L116

**Comment by Baroshem** [comment]
Hi @niklaswolf 

Thanks for creating the issue. Would you like to also create a pull request for that and join our contributor family? 😃

**Comment by niklaswolf** [comment]
@Baroshem yeah I can do that ;)

**Comment by Baroshem** [comment]
@niklaswolf 

Your pull request has been merged. Thanks!
