### ISSUE TITLE
[BUG] Can't install on node 16 M1 mac

### ISSUE THREAD

**Issue by timbenniks** [vuestorefront/storefront-ui#1841]
**Describe the bug**
When trying to install `@storefront-ui/vue@0.10.6` on a Mac M1 running node v16.1.0 (first native arm64 build of node) the build of node-sass fails. This is due to the fact that `@storefront-ui/vue@0.10.6` is using `node-sass@4.14.1`. Node-sass needs to be at version ^6.0.0 at least to work. If I install `node-sass@6.0.0` locally in my 'package.json' as devDependency the build still fails as `node-gyp` still tries to build `node-sass@4.14.1` from `@storefront-ui/vue@0.10.6`.

**How to reproduce**
1. Have an M1 mac
2. Install node 16.x
3. run `yarn`
4. Observe build errors

**Expected behavior**
Build succeeded

**Actual behavior**
Build failed

**Devices**
 - Device: Desktop M1 Mac Mini
 - OS: MacOS Big Sur v11.3

I suggest updating `node-sass@4.14.1` to `node-sass@6.0.0` which is the latest release.

**Comment by Baroshem** [comment]
Hi @timbenniks thanks for letting us know about this issue. We will take a look at it next week and try to fix it right away. It will be included with next version (0.10.8).

**Comment by Baroshem** [comment]
@timbenniks 

We have released version 0.10.8 of Storefront UI with updated Sass. Could you please check if it works for you?

**Comment by timbenniks** [comment]
it works!
