### ISSUE TITLE
[RFC] StorefrontUI FAQ and Video Tutorials

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1848]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

The purpose of this RFC is to gather knowledge about what problems the Storefront UI Community and the clients are facing when using SFUI. The result of this would be the updated FAQ as well as video tutorials that could help software users to find solutions to their problems. 

Idea proposed by our core contributor Aditya Patel (cool idea BTW)

**Is your proposal related to a problem?**
Describe the issue or type its number

List of proposed topics to cover in FAQ or video tutorials:
1. Customizing colors in VSF (and in general)
2. Integrating SFUI with TailwindCSS
3. Using slots/props to customize default SFUI components

Let us know in the comments what other topics would you like us to explain in more depth.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-55) by [Unito](https://www.unito.io)

**Comment by dt2patel** [comment]
Thanks for making this issue. Here are a few issues that I think might be helpful for the community.

 - My CSS is being rendered differently in dev and production
 - Using custom/material icons in SFUI

**Comment by satavisha123** [comment]
Thanks for making this .
1.how to overwrite the color in scoped scss.
2.how to use slots in which is mention in the organisms docs.
3.how to manupilate the organisms by adding more eliment

**Comment by SkullyFM** [comment]
I second better tutorials on:
- how to change the default color scheme
- what are slots and how to use them

**Comment by Baroshem** [comment]
Thanks everyone for participating in this RFC. We now know better what knowledge is missing from the docs and we will record videos about these topics.

**Comment by frans-vectra** [comment]
One thing I've been struggling with is understanding the Figma project. I guess its mostly me just not being very familiar with Figma and the Vue Storefront UI project in general.
I do think it would be really helpful for newcomers to have an example of how to understand a customised version of the Figma project (_from the perspective of a develop_), and then how to implement those customisations on the code side.

**Comment by dt2patel** [comment]
@frans-vectra Good question/idea. There are two figma files out there right now for SFUI. Can you link which one you're referring to?

If you are using [this one](https://www.figma.com/community/file/883240116671776403/Mobile-PWA-eCommerce-Design-Kit). 

There is [this YouTube series](https://youtube.com/playlist?list=PL6JSOz3-TrFQzh0oiJIo3WqEUvxgobJwG) that might help.

But it's def not as thorough as it could be. We should work more on that.

**Comment by frans-vectra** [comment]
@dt2patel Hi, were using the Figma file linked in the [Working with Figma section](https://docs.storefrontui.io/?path=/story/introduction-design-principles--page#working-with-figma) of the docs: https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-%7C-Design-System?node-id=0%3A1

The one you linked does seem a bit more intuitive (more closely matches the code), thanks!

**Comment by RWave88** [comment]
It would be great to have a video tutorial for a migration guide of each breaking release, upgrading existing projects is always important and painful, especially taking into account how many sub-dependencies VSF has
