### ISSUE TITLE
[BUG] Navigating to the Modal Molecule breaks scrolling on entire Storybook documentation

### ISSUE THREAD

**Issue by davidrhoderick** [vuestorefront/storefront-ui#1857]
**Describe the bug**
When I navigate to the Modal Molecule in Storybook documentation, I'm unable to scroll the main content unless I revisit the site in a new window/tab (and not the Modal Molecule page).

**How to reproduce**

1. Open Storefront UI Storybook documentation.  You'll notice that scrolling works on the main content section.
2. Navigate to the Modal Molecule page.  You'll now notice that you cannot scroll the main content section to see further examples.
3. Navigate to any other page and experience that the scrolling no longer works anywhere.

**Expected behavior**
I expected to be able to scroll through the documentation to find what I need.

**Actual behavior**
After visiting the Modal Molecule page, I was no longer able to scroll the main content section on that page or any other subsequent page.

**Devices (please complete the following information):**
 - Device: Desktop
 - OS: Pop!_OS 20.04
 - Browser: Firefox 89.0.1

**Additional context**
My guess is that there is an un-closed element in the examples that breaks the scrolling and for some reason, only revisiting the documentation site will un-break this issue.

I'd say that this is related to #1827 only this is really a high priority because the modal molecule is almost undocumented with this bug happening.

**Comment by Baroshem** [comment]
Hi @davidrhoderick 
We noticed similar problems with our docs in general. Adding this issue to the next version release plan (0.10.8). If you are interested in helping us fixing this issue we would be very happy to review your pull request :)

**Comment by davidrhoderick** [comment]
Hey @Baroshem,
I would really love to help but I'm a bit strapped for time.  I'll see if I can carve some out these coming weeks.  If not, at least I can be letting you know what's up as I go through implementing Storefront UI etc. in our project.
