### ISSUE TITLE
[BUG] Cypress tests fail when push on gh repo 

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1870]
**Describe the bug**
Cypress tests fails on Home page during gh actions checks - on SfHero component or SfCarousel. 
But it doesn't appear locally so the tests need to be changed.   

**How to reproduce**
Push new commit to remote repo and see workflow fails. 
It doesn't happens on local machine. 

**Expected behavior**
The cypress test are working stably either on local machine or on github repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/123226755-3a3a8100-d4d4-11eb-9fc9-b3c0b9be1d47.png)

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by justyna-13** [comment]
will be fixed with https://github.com/vuestorefront/storefront-ui/issues/1885
