### ISSUE TITLE
[FEATURE] Allow setting height of SfModal

### ISSUE THREAD

**Issue by davidrhoderick** [vuestorefront/storefront-ui#1880]
**Describe how this feature will help us improve**
Sometimes, there are components that may be small but overflow the relatively short SfModal component.  It would be great to be able to set the modal's height.  For example, adding a select drop-down or a date-picker means that the user has to scroll the modal in order to interact with it fully, even though there is plenty of real estate on the screen.

**Is your proposal related to a problem?**
There is already a mechanism for setting modal height in the variable `--modal-height` but it doesn't seem to enable the modal to use all the space; it just sets the container's height and misses stretching the `.sf-modal__content` element to fill its parent.

**Describe the solution you'd considered**
In order to use the preexisting `--modal-height` variable, I found that the solution could simply be to set the `.sf-modal__content` class to have `height: 100%` though I haven't tested this responsively or across different browsers.

If a set height is necessary, I would also propose adding classes to the SfModal to determine height.  This is less flexible but could be safer responsively/browser-support-wise and will probably resolve the issue.

**Additional context**
Here's a screenshot of how it looks without setting `--modal-height` with a date-picker component:

![current](https://user-images.githubusercontent.com/2300366/123634132-57e05100-d81a-11eb-973b-9bb981931b60.jpg)

Here's a screenshot of how it looks when I set `--modal-height: 450px`:

![after-setting-height-variable](https://user-images.githubusercontent.com/2300366/123634177-6a5a8a80-d81a-11eb-89b8-749f4818b284.jpg)

And here's how I'd prefer it worked.  I styled the buttons with flex to bring them to the bottom of the parent:

![expected-behavior-plus-flex](https://user-images.githubusercontent.com/2300366/123634244-7cd4c400-d81a-11eb-9b59-0f98cc493d23.jpg)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-56) by [Unito](https://www.unito.io)

**Comment by Baroshem** [comment]
Hi @davidrhoderick 

Yes indeed, ability to set the height of SfModal would be very beneficial. What could also be cool to have such a date picker in SFUI. Would you be interested in creating a pull request with a date picker implementation?
