### ISSUE TITLE
[BUG] Since 0.10.7 SfLink does no longer generate <nuxt-link> instead of classic <a>

### ISSUE THREAD

**Issue by SkullyFM** [vuestorefront/storefront-ui#1881]
**Describe the bug**
I did create a homepage with a couple of SfProductCard with a link property but I don't get the benefits of nuxt-link (automatic routing for static generation or prefetch).
If I remove the link property and wrap the card between a NuxtLink everything is working as expected.

**How to reproduce**
1. Create a nuxt project
2. Add Storefront-UI
3. Add in pages/index.vue a SfProductCard or a SfCallToAction with a link property targeting another page on the site (an About page for instance)

**Expected behavior**
The created  website should prefetch the link from the above components. In the browser's developer tool we should see the lazy loading happening

**Actual behavior**
Instead it's a classic link with a full page load.

**Additional context**
If you add in your nuxt.config.js the following code
`router: {
    linkPrefetchedClass: 'preloaded'
  },
`
the generated link should display a "preloaded" class. Unfortunately it doesn't happen with StorefrontUI's components, only with NuxtLink

**Workaround**
Downgrading to 0.10.6 (before the refactor of atomic components to functional) has the correct behavior.

**Comment by Baroshem** [comment]
Hi @SkullyFM 

I added your issue to the issue that proposes to revert SfLink to stateful component (not functional). After a bit of testing we noticed that SfLink indeed works as is, but when included in other component like SfProductCard or SfPagination it always creates an <a> tag, not <nuxt-link>.

**Comment by Baroshem** [comment]
Will be resolved as a part of #1886
