### ISSUE TITLE
[FEATURE] refactor examples and pages to contain real source code in Storybook

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1887]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

Currently when we display code of examples and pages in the Storybook it is completely not usable. 
![image](https://user-images.githubusercontent.com/37120330/124090604-46cf5400-da55-11eb-82aa-94084a39c0ed.png)

I would recommend refactoring stories.js of these components to include all the source code that was used to create this componet (basically copy paste component structure to the stories.js instead of using `template: '<Category/>`.

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
A concise description of your preferred solution. Things to address include:

  - Details of the technical implementation
  - Tradeoffs made in design decisions
  - Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by AdamPawlinski** [comment]
The source code is appearing correctly in docs and there's also source tab in the panel to see the code. However there is still issue with highlighting whole syntax in source code (only template looks good). I had a look for the solution but didn't find working one. There is issue added in Storybook repo to add support for vue syntax highlighting https://github.com/storybookjs/storybook/pull/10198. So I will now concentrate on transfering all example pages docs and we can fix this later after realising this fix by Storybook, wdyt @Baroshem ?

**Comment by Baroshem** [comment]
Good idea @AdamPawlinski 
Please, go on.
