### ISSUE TITLE
[FEATURE] Add checkout pages to nuxt branch 

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1896]
There should be checkout pages on a nuxt branch for testing purposes. We should be able to test the whole process. It should look like it's on Storybook.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-58) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
Closing according [ to the new LTS policy](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
