### ISSUE TITLE
[FEATURE] add slot in all occurences of SfImage to allow developers to use different component than SfImage

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1905]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

In some cases developers might want to use their own components or components from other libraries (i.e. https://image.nuxtjs.org/components/nuxt-img) instead of SfImage. By adding a slot in every place where there is a SfImage we allow developers to achieve that.

**Comment by Baroshem** [comment]
@justyna-13 can you link here a pull request that has this functionality and was merged to develop?

**Comment by justyna-13** [comment]
#1655 - SfHero

**Comment by justyna-13** [comment]
#1602 - SfBanner (not developed yet)

**Comment by Baroshem** [comment]
This was released with latest version of SFUI
