### ISSUE TITLE
[ANALYZE] SfHero for Progressive Enhancement

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1910]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

Carousels are bad for performance. In SfHero we are using Glide.js and SfHero is used in homepage at the very top. So, a huge code block with requests for each image will be a part of the homepage in many cases. My proposition is to add a static SfBanner to the SfHero component that will look the same as SfHero carousel with only one image and without carousel working, and after load it will be replaced SfHero carousel.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-61) by [Unito](https://www.unito.io)

**Comment by dt2patel** [comment]
Page 26-27 of the Google eCom UX playbook explicitly states that carousels are a bad experience. I couldn't find any leading eCom retailer with a carousel as their hero banner.

https://services.google.com/fh/files/events/pdf_retail_ux_playbook.pdf
