### ISSUE TITLE
[BUG] SfRadio - disabled state in storybook

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1913]
**Describe the bug**
SfRadio has a disabled state in storybook. It should be turned off by default. 

**How to reproduce**
1. Go to SfRadio
2. See disabled state
3. Turn on disabled state
4. Turn off disabled state
4. See the right state for common SfRadio

**Expected behavior**
SfRadio with turned off disabled state

**Comment by Baroshem** [comment]
Done already
