### ISSUE TITLE
Customize Icons from icons.js

### ISSUE THREAD

**Issue by LorenzKa** [vuestorefront/storefront-ui#1914]
Hello,

I want to customize some icons that are used on molecules and organisms. Icons are pulled from icons.js but i cant customize it because its inside node_modules folder. Is there a way to customize the icons.js without chaning something in node_modules?

**Comment by Baroshem** [comment]
Hi @LorenzKa 

For now, we only have a functionality of pulling of components from Storefront UI to your local project (https://docs.storefrontui.io/?path=/story/setup-pull-off-components--page) If you need to use custom icons instead I would recommend creating your own icons and use them directly in the components. 

However if you are interested in the functionality of pulling of not just the components but also the icons.js file as well, you can create a pull request with such a script. It would have work similarly to https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/scripts/copy-components.js

Let me know if you need more help

**Comment by Baroshem** [comment]
Closing the issue as there is no further contact from the issue author. If needed, the issue can be reopened.
