### ISSUE TITLE
[BUG] SfCallToAction doesn't emit "click" event

### ISSUE THREAD

**Issue by RikkiMasters** [vuestorefront/storefront-ui#1915]
**Describe the bug**
Documents state SfCallToAction emits a click event but it doesn't seem to be a feature of the component.

**Expected behavior**
'click' event triggered

**Actual behavior**
Event not triggered

**Code examples**
```
<template>
  <SfCallToAction
    class="call-to-action"
    title="Test Title"
    description="Test description."
    button-text="click"
    background="#303231"
    @click="clickEvent()"
  />
</template>

<script>
import { SfCallToAction } from "@storefront-ui/vue";
export default {
  name: "CTA",
  components: {
    SfCallToAction,
  },
  methods: {
    clickEvent() {
      console.log("click");
    },
  },
};
</script>
```
Additional context
Node: 14.17.0
Nuxt: 2.15.7
Storefront UI: 0.10.8

**Comment by Baroshem** [comment]
Hi @RikkiMasters 

Thanks for reporting this issue. It is indeed a bug on our side that needs to be fixed. Added to the next release roadmap (0.10.10). 

Stay tuned!
