### ISSUE TITLE
[BUG] VueCompilerError: <template functional> is no longer supported in Vue 3

### ISSUE THREAD

**Issue by undercoverGod** [vuestorefront/storefront-ui#1919]
**Describe the bug**
When using storefront UI with Vue 3, we encounter this error due to apparent usage of functional component in  muiltiple components in storefront UI. Official Vue 3 reference at https://v3.vuejs.org/guide/migration/functional-components.html.

**How to reproduce**
1. Create a new project using vue cli
2. Choose vue version as 3, other options are not relevant
3. Add storefrontui as dependency and import the storefrontUI stylesheet as instructed in sfui docs at https://docs.storefrontui.io/?path=/story/setup-installation--page
4. Use component "SfSteps" in boilerplate code.
5. Do `npm run build`

**Expected behavior**
The build should complete successfully.

**Actual behavior**
We get the following error:

<details>
  <summary>
    Error
  </summary>

ERROR  Failed to compile with 18 errors                                                                             9:03:46 PM

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfArrow/SfArrow.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfArrow/SfArrow.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;component
3  |      :is=&quot;injections.components.SfButton&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 2:0-65 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfBadge/SfBadge.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfBadge/SfBadge.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :class=&quot;[data.class, data.staticClass, 'sf-badge']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 3:0-65 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfBreadcrumbs/SfBreadcrumbs.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfBreadcrumbs/SfBreadcrumbs.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;nav
3  |      :class=&quot;[data.class, data.staticClass, 'sf-breadcrumbs']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 4:0-83 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfBullets/SfBullets.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfBullets/SfBullets.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;ol
3  |      :class=&quot;[data.class, data.staticClass, 'sf-bullets']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 5:0-71 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfButton/SfButton.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfButton/SfButton.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;component
3  |      :is=&quot;props.link ? injections.components.SfLink : 'button'&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 6:0-68 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfChevron/SfChevron.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfChevron/SfChevron.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :class=&quot;[data.class, data.staticClass, 'sf-chevron']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 7:0-71 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfCircleIcon/SfCircleIcon.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfCircleIcon/SfCircleIcon.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;component
3  |      :is=&quot;injections.components.SfButton&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 9:0-80 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfColor/SfColor.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfColor/SfColor.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;component
3  |      :is=&quot;injections.components.SfButton&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 10:0-65 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfDivider/SfDivider.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfDivider/SfDivider.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;hr
3  |      :class=&quot;[data.class, data.staticClass, 'sf-divider']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 11:0-71 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfHeading/SfHeading.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfHeading/SfHeading.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :class=&quot;[data.class, data.staticClass, 'sf-heading']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 12:0-71 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfIcon/SfIcon.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfIcon/SfIcon.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;span
3  |      ref=&quot;icon&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 13:0-62 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfLoader/SfLoader.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfLoader/SfLoader.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :ref=&quot;data.ref&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 17:0-68 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfOverlay/SfOverlay.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfOverlay/SfOverlay.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;transition :name=&quot;props.transition&quot;&gt;
3  |      &lt;div

 @ ./node_modules/@storefront-ui/vue/index.js 18:0-71 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfPrice/SfPrice.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfPrice/SfPrice.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :class=&quot;[data.class, data.staticClass, 'sf-price']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 19:0-65 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfProperty/SfProperty.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfProperty/SfProperty.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :class=&quot;[data.class, data.staticClass, 'sf-property']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 20:0-74 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :class=&quot;[data.class, data.staticClass, 'sf-quantity-selector']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 21:0-98 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfRating/SfRating.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfRating/SfRating.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :class=&quot;[data.class, data.staticClass, 'sf-rating']&quot;

 @ ./node_modules/@storefront-ui/vue/index.js 22:0-68 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/@storefront-ui/vue/src/components/atoms/SfTexarea/SfTextarea.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):

VueCompilerError: &lt;template functional&gt; is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal &lt;template&gt; instead.
at /home/frodo/dev/sandbox-projects/rapp-sandbox-gen/rapp-sandbox-s2/node_modules/@storefront-ui/vue/src/components/atoms/SfTexarea/SfTextarea.vue:1:11
1  |  &lt;template functional&gt;
   |            ^^^^^^^^^^
2  |    &lt;div
3  |      :class=&quot;[

 @ ./node_modules/@storefront-ui/vue/index.js 23:0-73 76:0-150:2
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue?vue&amp;type=script&amp;lang=js
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue?vue&amp;type=script&amp;lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.

 
</details>

 
**Code examples**
src/components/HelloWorld.vue:.
```
<template>
  <div class="hello">
      <SfSteps :active="0" :steps='["Details","Shipping","Payment","Review"]'>
    <SfStep name="Details"><div>[#default slot content] Details</div></SfStep>
    <SfStep name="Shipping"><div>[#default slot content] Shipping</div></SfStep>
    <SfStep name="Payment"><div>[#default slot content] Payment</div></SfStep>
    <SfStep name="Review"><div>[#default slot content] Review</div></SfStep>
  </SfSteps>
  </div>
</template>

<script>
import { SfSteps } from "@storefront-ui/vue";
export default {
  name: "HelloWorld",
  props: {
    msg: String,
  },
  components:{
    SfSteps,
  }
};
</script>

```

**Screenshots**
NA

**Devices (please complete the following information):**
 - Device: [Desktop]
 - OS: [Ubuntu]
 - Browser: [NA]

**Additional context**
NA

**Comment by justyna-13** [comment]
Unfortunately, our current version isn't compatible with vue 3. We have it in our future plans but for now, we need to focus on more important issues. There was an audit regarding possible changes to make it compatible and it seems there's a lot to change - so one issue won't make it compatible. For sure we'll back to this. https://github.com/vuestorefront/storefront-ui/issues/966
