### ISSUE TITLE
[BUG] Font override incorrect docs

### ISSUE THREAD

**Issue by likelovewant** [vuestorefront/storefront-ui#1921]
**Describe the bug**

This is not bug actually , this might be a supplement for the document on customization  
lists here https://docs.storefrontui.io/?path=/story/setup-css-customization--page#customizing-styles

I follow the guide to replace the default font as guide on documents 
by 

```
/*
 * use id of DOM root element
 * vue-cli -> #app
 * nuxt-app -> __nuxt
 */
#app {
  --font-family--primary: "Raleway", serif;
}

As this is a nuxt projects , I used 
__nuxt {
  --font-family--primary: "Jost", serif;
}

```
in a custom.sass  file , however , it's not working  ,nothing change .

then I found on chrome console  no  matter how I change from the custome.sass , the font always fetch from the storefront ui package rather than custom.sass or  custom.css

the solution is   add  the following in custom sass 

```
@import "~@storefront-ui/shared/styles/helpers";
@import url("https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap")
```
and 
use```
 :root {
  // font-family
  --font-family--primary: 'Jost', sans-serif;
}

```
rather than 

```
__nuxt {
  --font-family--primary: "Jost", serif;
}
```

so the key should be" root: ", of  course this  depend on your projects 
just make sure check your console repose

this is it , hope it's can help others

**Comment by Baroshem** [comment]
Hi @likelovewant 

Thanks for rising this issue. Next week we will be recording a tutorial video on how to override colors and font in Storefront UI so we could also fix this bug in the docs. Would you be interested in creating a pull request for that? 🙂

**Comment by likelovewant** [comment]
hi ,  @Baroshem
 I do love to ,however , I am not familiar with pull request and update file process on github . I am not a professional developer .I think you can simply  update documents without extra pull request . 
thanks
