### ISSUE TITLE
[BUG] Gallery stage goes off-centered after navigating to another product

### ISSUE THREAD

**Issue by rain2o** [vuestorefront/storefront-ui#1926]
**Describe the bug**
When navigating from one product page to another, the gallery stage sometimes has invalid calculations as you navigate the images in the gallery, so that they are off-centered. 
There is actually a second bug, but not as critical, where the gallery stays on the same slide when you change products. So, if I am on image #4 on one product, and I go to another product page, it loads the gallery but stays on image number 4.

I was able to reproduce on https://capybara.storefrontcloud.io/

**How to reproduce**
1. Go to https://capybara.storefrontcloud.io/viktor-lumatech-trade-pant.html?childSku=MP02-32-Blue
2. Navigate through some of the images in the gallery
3. Scroll down to "Similar Products"
4. Click on "Mona Pullover Hoodlie"
5. You should see that the gallery is on the nth image, wherever you were on in the previous product, and that the image is not correctly centered.
6. Navigate through this gallery now, and see that some of the images are not correctly placed in the stage.

**Expected behavior**
The gallery should be reset on each product page so that it starts on the first slide (I suppose this part is debatable), and each slide should be correctly calculated to show in the center of the stage.

**Actual behavior**
The gallery stays on the same slide, and the slides are off-centered in the stage.

**Screenshots**
![Screen Shot 2021-07-26 at 16 28 58](https://user-images.githubusercontent.com/4626224/127117023-c07a3c29-f13b-4246-94b5-01da67f18f0d.png)

https://user-images.githubusercontent.com/4626224/127116969-b8405b01-afd5-4941-bf36-917d051a5fc4.mov

**Devices (please complete the following information):**
 - Device: Desktop (haven't tested mobile specifically for this bug)
 - OS: MacOS Big Sur Version 11.5
 - Browser: Chrome 92.0.4515.107 and Safari  14.1.2

**Additional context**
We are using it in Vue Storefront v1, and reproduced on Capybara running the same.

**Comment by dt2patel** [comment]
Hi @rain2o I think this PR might be helpful for you: https://github.com/vuestorefront/vsf-capybara/pull/552

**Comment by rain2o** [comment]
Thanks @dt2patel , that is useful. I originally tried adding a key to the parent component based on the product's sku, but even that didn't resolve the problem, so I didn't think putting a key on the gallery would either. I'll have to try that again.

**Comment by Baroshem** [comment]
@rain2o 

Have you tried a fix from @dt2patel ? Did it work?

**Comment by rain2o** [comment]
Hi @Baroshem . No I haven't had a chance to try it yet. When I opened this bug I implemented my own workaround in our components, though the workaround is a bit more messy than @dt2patel 's suggestion. I will try to test it out, but I'm not sure how soon I will be able to.

**Comment by dt2patel** [comment]
@Baroshem @rain2o if you want to see it in action, first used this fix on our demo site and then added it to capybara: https://demo.hotwax.io
