### ISSUE TITLE
[FEATURE] Add condition for SfSection heading

### ISSUE THREAD

**Issue by rain2o** [vuestorefront/storefront-ui#1927]
**Describe how this feature will help us improve**
Depending on how you look at this, it could be considered a bug or a feature request.

When using SfSection, the props `titleHeading` and `subtitleHeading` are optional (defaults to empty string). If no value is passed, the `heading` slot and the contained `SfHeading` component are still rendered, resulting in an empty `h2` tag by default. My understanding is that having empty heading tags isn't ideal for SEO.

The workaround is to add your own slot in sections where you don't want a heading, just providing an empty tag in the heading slot. However, I believe this should be built into the SfSection component, since the heading is optional.

**Is your proposal related to a problem?**
Using SfSection without a heading results in an empty H2 tag (plus extra spacing, but that's not as much of a concern).

**Describe the solution you'd considered**
Adding a `v-if="titleHeading || subtitleHeading"` on the `heading` slot should resolve this problem I believe (untested). Or the `v-if` could be on the SfHeading component.

This means that `SfHeading` should probably also have this type of condition on the `title` slot, since it could in theory receive only a `description`, resulting again in an empty `h2` tag.

**Comment by Baroshem** [comment]
Hi @rain2o 

This is indeed an issue and SEO is quite important for us. Would you be interested in creating a pull request for that?
If you need any help with that, please let me know 🙂

**Comment by rain2o** [comment]
Hi @Baroshem 

I can do that, though I don't know how soon I'll be able to. Currently working towards a couple deadlines. If someone else wants to take it in the meantime go for it.
