### ISSUE TITLE
[FEATURE]  Default enabling of Button for SfBanner on mobile devices

### ISSUE THREAD

**Issue by Cyoo9** [vuestorefront/storefront-ui#1934]
**Describe how this feature will help us improve**
I think users will be confused on certain aspects of the website. They will not be able to find features that they saw on their computer on their phone. 

**Is your proposal related to a problem?**
Button on SfBanner does not show up for mobile devices (smartphones and certain ipad models). 

**Describe the solution you'd considered**
Getting rid of !isMobileView condition for SfButton or setting condition to true (isMobileView: true)

**Comment by Baroshem** [comment]
Hi @Cyoo9 

Thanks for raising that issue. Would you be interested in creating pull request with that functionality?
I will then add it to our next release roadmap.

**Comment by Cyoo9** [comment]
Sure!

**Comment by Cyoo9** [comment]
Sorry it is more complicated than I thought. I just changed isMobileView button logic, but it did not work.
