### ISSUE TITLE
[BUG] Can't pass name attribute to SfSelect component, as it lends on div wrapper tag

### ISSUE THREAD

**Issue by DavidGolodetsky** [vuestorefront/storefront-ui#1941]
**Describe the bug**
Currently, I cannot pass a name attribute to the SfSelect inner `select` tag. I need it in order to have a non-js support form, but overall, I think it goes against semantic HTML principles.

**How to reproduce**
On a `SfSelect` SFui component add name attribute, check DOM tree, and see that it lends on `div` tag instead of `select`.

**Expected behavior**
Being able to pass the `name` attribute to the `select` tag

**Code examples**
It could be achieved by introducing a new prop, or adding `$attrs` to select tag, which I think is a better way:

![image](https://user-images.githubusercontent.com/32278933/128379197-1f5a1861-e748-483e-9b18-276ecabb9919.png)

**Comment by DavidGolodetsky** [comment]
If you don't mind, I can take it

**Comment by Baroshem** [comment]
Sure @DavidGolodetsky but please wait untill monday. On monday we will be releasing new version of SFUI so you could create a new branch with current changes
