### ISSUE TITLE
[BUG] SfQuantitySelector is broken after refactoring in 0.10.71

### ISSUE THREAD

**Issue by alexd3d** [vuestorefront/storefront-ui#1944]
**Describe the bug**
Seems like SfQuantitySelector is broken after refactoring in 0.10.71 if both  v-modal attribute is set for quantity and @input is set for additional logic (i.e @input="updateLineItemQuantity(item.id, item.quantity)" for component in a v-for loop of items) then we get exception n SfQuantitiySelector (because "listeners.input" becomes an array(2) and not a single function)
**How to reproduce**
dependencies: 
@storefront-ui/vue@0.10.8
@vue-storefront/nuxt@2.3.4
vue@2.6.14

This sample piece of code will throw exception on any + - changes:
`<SfQuantitySelector
      :qty="quantity"
      v-model="quantity"
      @input="updateLineItemQuantity(quantity)"
    />`

**Expected behavior**
It is expected to change the quantity and run function assigned to component in @input (behavior of 0.10.6 version)

**Actual behavior**
The code on click on + - throws an error "Exception: listeners.input is not a function (SfQuantitySelector.vue(64))"

**Screenshots**
![image](https://user-images.githubusercontent.com/7292927/128747711-2faf9522-c864-4bc8-be5b-13b2dec05120.png)

**Devices (please complete the following information):**
Chrome, Win10 x64 and MacOS the same

**Comment by Baroshem** [comment]
Hi @alexd3d 

I dont think it is related to release version 0.10.71 as it was a hotfix for sidebar not scrolling on IOS devices but rather due to changes in 0.10.7 where we have refactored atomic components (including SfQuantitySelector) to functional components.

**Comment by alexd-3d** [comment]
Hi @Baroshem , thanks for reply!
unfortunatelly I'm just learning Vue & Storefront UI and don't have enough exertise to fix this properly. But in project I work on - this component is used and we have to downgrade the lib due to this issue only... ( 
I alsosaw the announcement that SfQuantitySelector in v11rc1 now supports min max but I've seen the code change and it still expects that prop "listeners" will contain only 1 element - "input" and calls it. Unfortunately, if we use v-modal with additional handler, it hangs second event listener and converts it to Array with 2 listeners. Seems like they both should be called if it's and Array. Maybe this is not a bug and we're doing something wrong? The how can it be used with v-model + my eventHandler on change? 
Thanks in advance!

**Comment by Baroshem** [comment]
@AdamPawlinski Could you please take a look at that?

**Comment by AdamPawlinski** [comment]
Hi @alexd3d, I'm not sure if undestand the problem well, but in my opinion it should be possible just to pass down quantity value to the component via :qty prop and to receive the value from component by @input event without a need to add additional lisetners in QuantitySelector. Then you could use the function to update quantity value. If it's not working please share more of your code. I know that functional component syntax may be tricky.

**Comment by alexd3d** [comment]
Hi @AdamPawlinski ,
Thanks for reply! 
Yes - you are right. I've removed v-model, added passed qty property and used in @input my own handler. That required manually change ref of qty value so it will be shown in input as updated. After this I pass new qty value to the target function that handles other logic via "emit" (post api call). This works perfectly, thanks!
One thing that I did not understand that it seems like you can't use "v-model" in situation like mine - I wanted component to handle all the - + input updates ("v-model magic") and just call one more side-effect function (that api call) and used @input. It appears I can't do that as I get "TypeError: listeners.input is not a function" issue in console (2 events are assigned in array). Sorry, I'm just a beginner in Vue - is this issue expected even in regular input components with both v-modal and some @input function assigned?
Anyway thanks for guiding me in right direction - seems like issue is solved! )
