### ISSUE TITLE
[BUG] clear dynamic classes for organisms components

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1961]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by AdamPawlinski** [comment]
I made the overview of all organism components and can't see any classes that are created dynamically and need to be changed.
