### ISSUE TITLE
[BUG] SfGroupedProduct - differences between branches

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1979]
**Describe the bug**

SfGroupedProduct differs on develop branch. it should look like on master branch.

**How to reproduce**
1. Go to develop branch
2. Go to SfGroupedProduct
3. See differences 

**Screenshots**

![Screenshot from 2021-08-24 11-31-01](https://user-images.githubusercontent.com/46591755/130728739-18ebbcc6-d36f-4c38-88d4-2f0394b6f2bc.png)

**Comment by Baroshem** [comment]
Fixed already
