### ISSUE TITLE
[BUG] QuantitySelector.vue increment bug

### ISSUE THREAD

**Issue by Radek-Wawrzyk** [vuestorefront/storefront-ui#2011]
**Describe the bug**
Basically they are bugs in the code:

- The quantity button test references are revert, minus refers to the `data-testid="+"` and plus to the `data-testid="-"`
- When user is editing the field of the value of quantity, for example from 1 to 3, and after editing that value by selecting middle input and changing it qty value directly - eg 4, clicking  `+` button will occur an issue -> in that case the output instead of 5 would be 41

**How to reproduce**
1. Go to the product page (for example -> [QuantitySelector.vue](https://docs.storefrontui.io/?path=/story/components-atoms-quantityselector--common)) 
2. Click 3 times plus button
3. Select qty number by mouse and type 4 (replace)
4. Click `+` button and see what's happening

**Expected behavior**
Instead of `41`, result should be `5`

**Actual behavior**
The quantity selector is adding one to current number (like a string behaviour, instead of number calculation)

**Comment by AdamPawlinski** [comment]
@Radek-Wawrzyk Hi, this bug is already fixed. You probably use older version of SFUI. Please check ot once more and if it's okay I will close this issue.

**Comment by AdamPawlinski** [comment]
@Radek-Wawrzyk Please let me know if it works. I'm sure SfQuantitySelector was fixed. So if you use latest versions it should be okay. 
What is the release you are depending on? 
![sfQuantitySelector](https://user-images.githubusercontent.com/32042425/135094360-cf43cd2a-0502-4d3d-86e8-92b5c64d7b98.gif)
.
