### ISSUE TITLE
[BUG] Incorrect validation error message for email form input

### ISSUE THREAD

**Issue by flyfishwv** [vuestorefront/storefront-ui#2016]
**Describe the bug**
The email input for the Form story validation error message is a duplicate of the country input. It displays "Please choose your country".

**How to reproduce**
1. Go to https://docs.storefrontui.io/?path=/story/examples-form--form
2. Click in the Email input
3. Click out of the Email input
4. See incorrect validation error message

**Expected behavior**
This error message should notify the user to enter a valid email address

**Actual behavior**
The message is displaying a duplicate of the Country input validation error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/58954920/134670448-44970e16-5c8c-4a5f-94ef-bf4c448e6932.png)

**Comment by flyfishwv** [comment]
Yeah absolutely.

Gratefully,

Aaron

**Comment by AdamPawlinski** [comment]
It's yours, thanks :)
