### ISSUE TITLE
[nuxt] Module improvement suggestions

### ISSUE THREAD

**Issue by pi0** [vuestorefront/storefront-ui#2033]
Hi there! Here are few suggestions to improve nuxt module for adding to nuxt module listing (https://github.com/nuxt/modules/pull/187):

Checking [currnet version](https://github.com/vuestorefront/storefront-ui/blob/5dadd2bcb52fa8712f68f12fe265e05ce3c8cbf5/packages/nuxt-module/lib/module.js):

- Please try to migrate to ESM syntax and avoid CommonJS for future compatibility.
- You can use [defu](https://github.com/unjs/defu) and remove [1MB lodash dependency](https://packagephobia.com/result?p=lodash) for merging defaults that will also have consistent behavior with upcoming nuxt kit API
- Instead of using `extendBuild` + `config.resolve.alias` which is webpack-only, you can directly extend `this.options.build.alias`
- For using `require.resolve`, use [nuxt.options.rootDir, `__dirname`, process.cwd()] since `@storefront-ui/vue` is a dependency of your module not necessarily in the current working directory and same for rootDIr that is not always cwd.
- Add explicit depenency `@storefront-ui/shared` to module dependencies (or make it/both peedDependencies asking user to explicitly install). Implicitly depending on `node_modules` can break pnpm and plug-an-play behavior

cc @Baroshem

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-21) by [Unito](https://www.unito.io)

**Comment by aniamusial** [comment]
Moving to 11.3 as it requires some more complex testing and research on new options we can add
