### ISSUE TITLE
[FEATURE] SfAddToCart text

### ISSUE THREAD

**Issue by kadukr** [vuestorefront/storefront-ui#2037]
hello i'm using the ui with vuestorefront

we are translating the store to our country.

When I got no **SfAddToCart** component, it doesn't get any attribute to change the inner text

what do you suggest to me?

**Comment by Baroshem** [comment]
I am closing the issue as the answer was provided

**Comment by FabienWiboo** [comment]
Hi, when I use this slot, the button loses its behavior, the add to cart doesn't work anymore (isn't there something to manage around the v-on="$listeners" which is part of the original SfButton?)
