### ISSUE TITLE
[FEATURE] Refactor SfSkeleton to be Vue 2 functional

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2039]
**Describe how this feature will help us improve**
Refactor SfSkeleton component to be Vue 2 functional, like most other atom components.

**Is your proposal related to a problem?**
no

**Describe the solution you'd considered**

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by aniamusial** [comment]
Closing, as we gave up refactor to functional components in upcoming versions.
