### ISSUE TITLE
[BUG] Home page instagram feed layout is broken on mobile

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2080]
**Describe the bug**
Instagram Feed section images on Home page are too big and break the whole page layout.
There should be mobile versions of images implemented.

**How to reproduce**
1. go to Home page on storybook docs 
2. switch to mobile and scroll to the `Share your look` section.  

**Expected behavior**
Images in instagram feed should adjust its size to the mobile mode. There should be adjusted to our designs.

**Actual behavior**

**Screenshots**
![hom_page_instagram_feed](https://user-images.githubusercontent.com/32042425/139252653-d71fa0bf-4a8a-4e94-b1e0-134971fc397a.gif)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by farukSRKNT** [comment]
Hey @AdamPawlinski , I have tried to solve this. I think images should have `max-width: %100`. I've also realized that its working on [storybook](https://storybook.storefrontui.io/?path=/story/pages-home--common) but not on [docs](https://docs.storefrontui.io/?path=/story/components-pages-home--home). Why do these two have different codes?

**Comment by AdamPawlinski** [comment]
@farukSRKNT I'm sorry I didn't answer you before. in this case I wanted to add different images for mobile and desktop mode to adjust to our design. That is why I didn't consider your solution, but thanks for suggestion and if you have other ideas don't hesitate to mention them :) Thank you.
