### ISSUE TITLE
Review animations performance 

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2085]
**Describe how this feature will help us improve**
We should audit all the animations we have in the library and check if they align with performance guidelines: https://web.dev/animations-guide/

**Is your proposal related to a problem?**
No
**Additional context**
nope

**Comment by AdamPawlinski** [comment]
SfExpand transostion component utilizes `height` property transition which should be avoided, because it affects  layout of the page. It should be replaced with other solution.
![Screenshot from 2021-11-30 14-34-54](https://user-images.githubusercontent.com/32042425/144057899-d794b50d-5adc-461b-a151-e2df4261d787.png)

**Comment by AdamPawlinski** [comment]
Here is the list of components which have transitions applied other than opacity or transform (which are cheap for performance). Those which causes layout rebuilt like `height`, `width`, `top` or `font-size` may affect performance more so can be ones to look at. Generally after performance analysis all components separately don't affect performance significantly, but it may depend on the usage in particular project. 

- SfArrow - background-color
- SfButton - background, color
- SfCircleIcon - background
- ** SfInput - top, font-size, width, color**
- ** SfTextarea - font-size**
- SfAddressPicker - border, background 
- SfCheckbox, background, color 
- ** SfComponentSelect - top, font-size** 
- SfRadio - border 
- SfSearchbar - color 
- ** SfSelect- top, font-size** 
- ** SfSlidingSection - height** 
- SfTile - color, box-shadow  
- SfAccordion - color
- SfCollectedProduct - box-shadow
- SfHeader - border-color, color
- SfProductCard - box-shadow
- SfTabs - color, 
- SfShipping - color 

We can take a closer look on above marked components and try to replace these properties with transform or use `will-change` property which may be useful, but should be used with caution (to elements constantly changing or when there are small amount of such elements).

**Comment by AdamPawlinski** [comment]
Other things to investigate: 
- repainting issue that happens on nuxt project when hovers over the color component on PDP (repainted elements are marked in green)
![animations-color-affect-below-elements](https://user-images.githubusercontent.com/32042425/144494272-b9f5a0e7-bdf8-47f1-8b94-92c4e66683d2.gif)
- and issues found on VSF demo project - when accodion is causing repainting the header in one case and also the product list in when products card horizontal are showed 
 
![animations-accordion-affect-header](https://user-images.githubusercontent.com/32042425/144494784-ac90b21e-b586-4406-8213-4075647b1379.gif)
![animations-accordion-affect-header-and-prodct-list](https://user-images.githubusercontent.com/32042425/144494792-1ae96fef-32f2-4829-89a0-cd775e500ad5.gif)
