### ISSUE TITLE
[CHORE] Upgrade immer version

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2086]
**Describe how this feature will help us improve**
- Immer should be upgraded to 9.0.6 version for sake of stability 
- After upgrade the app should be tested across all envs

**Is your proposal related to a problem?**
No
**Additional context**
none

**Comment by justyna-13** [comment]
https://github.com/storybookjs/storybook/issues/16093 - this depends on react-dev-utils form storybook

**Comment by aniamusial** [comment]
@justyna-13 stuck for now, removing from 11.3 then
