### ISSUE TITLE
[BUG] color variant generation following storefrontui instructions is not working in production build

### ISSUE THREAD

**Issue by ricardo85** [vuestorefront/storefront-ui#2090]
**Describe the bug**
I am following the storefrontui tutorial for generating and overwriting colors in my project (https://www.youtube.com/watch?v=dwj2snJegYU&t=257s)

This works fine in development mode but doing a production build is overwriting the generated colors and also some custom css.

**How to reproduce**
1. In default.vue layout file:

```
<style lang="scss">
@import "~@storefront-ui/vue/styles";

:root {
  @include generate-color-variants(--_c-yade-primary, #889671);
  @include generate-color-variants(--_c-yade-secondary, #b8c4a5);
  @include assign-color-variants(--c-primary, --_c-yade-primary);
  @include assign-color-variants(--c-primary-variant, --_c-yade-secondary);
  @include generate-color-variants(--_c-link-primary, #57213c);
  @include assign-color-variants(--c-secondary, --_c-link-primary);
}

//...
```

2. Run `yarn dev` and see colors applying to e.g. buttons
3. Run `yarn build && yarn start` and see colors not applying 

**Expected behavior**
Production build should not behave different to development build.

**Devices (please complete the following information):**
 - Device: Macbook Pro
 - OS: MacOs Big Sur
 - Browser: All Browsers

**Additional context**
I was playing around a lot and added also some project scoped classes, overwrited some storefront ui css properties, added the styles in nuxt config to styleResources and css property and nothing helped.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-20) by [Unito](https://www.unito.io)

**Comment by ricardo85** [comment]
update:

using `#__nuxt` instead of `:root` makes it working also in production build

**Comment by aniamusial** [comment]
Thanks for the update @ricardo85, we'll investigate it further!

**Comment by AdamPawlinski** [comment]
It looks like everything works as expected. You can overwrite color values with `:root`, `html` or `$__nuxt` selectors. 
![Screenshot from 2022-02-10 00-02-40](https://user-images.githubusercontent.com/32042425/153305390-846a078a-ec2d-464c-a347-68e685240d62.png)
So I suppose we can close it now.
