### ISSUE TITLE
[BUG SfRating component icon color issue

### ISSUE THREAD

**Issue by DavidGolodetsky** [vuestorefront/storefront-ui#2096]
**Describe the bug**
When I overwrite icon color css var the component logic brakes

**How to reproduce**
1. Pass score of 3 to the component
2. Overwrite icon-color css variable

**Expected behavior**
A clear way to pass icon color. Possibly via prop.

**Actual behavior**
Icon color css variable is used as a fill value for the svg icon, so if it doesn't have a score, it's filled with this value.

**Screenshots**

1. Here I'm overwriting --icon-color variable in order to style svg icons

![image](https://user-images.githubusercontent.com/32278933/140958397-e1f40b23-75c5-4b1a-a7e9-097d0d39d854.png)

![image](https://user-images.githubusercontent.com/32278933/140958462-551782a7-f5a9-45fb-81d1-f9b9a32ad087.png)

2. If I disable this rule the component act as it should

![image](https://user-images.githubusercontent.com/32278933/140958576-c899b08a-d369-40e1-b4d6-16da24005141.png)

![image](https://user-images.githubusercontent.com/32278933/140958631-a628046c-17a0-4e0d-8e69-8b862d0242ce.png)

**Additional context**
Also, the documentation for SfRating component seems to be outdates, as in the code samples block you have a plain html, rather than component with props being passed.

![image](https://user-images.githubusercontent.com/32278933/140958952-2d0238fa-86c4-4e22-b072-deb9d3c60431.png)

**Comment by justyna-13** [comment]
Hi @DavidGolodetsky, Thanks for reporting this issue. Indeed there is a problem when you want to change only one color like in your case. A fast solution is to override the second color as well, for example: 
`.sf-rating__icon {
  --icon-color: yellow;
}
.sf-rating__icon--negative {
  --icon-color: blue;
}`

Let me know if this temporary solution works for you

Changes that will help with this problem seem to be BC so they have to wait until 0.12.0

When it comes to docs, unfortunately we don't have any influence on what Storybook shows. For such cases, we've added a special addon that shows our real code. It's called "Story" and it's in the canvas tab
![Screenshot from 2021-11-19 14-57-26](https://user-images.githubusercontent.com/46591755/142634463-17cf7043-4f0f-4ddd-9d3b-476ef931953e.png)

**Comment by DavidGolodetsky** [comment]
@justyna-13 Thank you for the reply. Yeah with your suggested changes it works for integers, but it doesn't work correctly for decimals: 
![image](https://user-images.githubusercontent.com/32278933/142652283-85d04f71-1be8-4ab5-965f-4af8f49c6dae.png)

Here I'm using your suggested CSS code with a score of 2.3

Regarding the doc, I see now that a lot of atoms code examples are shown in such way. Although some of them are shown properly (at least as I would expect it to see), for example [SfInput](https://docs.storefrontui.io/?path=/docs/components-atoms-input--common)

**Comment by DavidGolodetsky** [comment]
Ah, if you set `sf-rating__icon { --icon-color-negative: blue; }` then it works.
