### ISSUE TITLE
[FEATURE] Introduce html-validator 

### ISSUE THREAD

**Issue by DavidGolodetsky** [vuestorefront/storefront-ui#2097]
**Describe how this feature will help us improve**
Would be great if SFui components would be checked with some HTML-validator, for example, the [one](https://html-validator.nuxtjs.org/) from Nuxt

**Is your proposal related to a problem?**
Currently, we're using SFui with this Nuxt HTML-validator and we have a bunch of issues from Sfui, each affected component requires a separate issue, that I'll create if needed. It creates a lot of noise and it looks like some of them could affect SEO, so would be nice to fix them and have such a checker in the future.

**Comment by aniamusial** [comment]
Hey @DavidGolodetsky feel free to create such issues if needed - that's definitely something worth improving in SFUI :) Thank you!

**Comment by DavidGolodetsky** [comment]
Thanx, @aniamusial, I will! But in this issue I wanted to raise the topic of adding the validator checker itself at some step of SFui CI/CD. If you think it's not possible, or you don't plan to do it - feel free to close this issue:)

**Comment by DavidGolodetsky** [comment]
Related issues are:
#2103 
#2102 
#2101
