### ISSUE TITLE
[BUG] SfGallery invalid html issue

### ISSUE THREAD

**Issue by DavidGolodetsky** [vuestorefront/storefront-ui#2101]
**Describe the bug**
Nuxt html-validator throws an error on SfGallery component:
` Element <div> is not permitted as content in <button>`

**How to reproduce**
You can try to put the output of the component to the [W3C validator](https://validator.w3.org/#validate_by_input+with_options)

**Expected behavior**
The SfGallery component would be restructured in a way that HTML would be valid

**Actual behavior**
The SfImage component is wrapped inside a div tag (which is not allowed inside a button tag), in the SfGallery component we wrap each SfImage component in a button (for a11y purposes as I understand)

**Screenshots**
![image](https://user-images.githubusercontent.com/32278933/141148207-93a20be8-f2d5-4503-9556-72f2219e6148.png)

**Additional context**
Related to #2097

A possible workaround would be to use `span` as a wrapping tag for SfImage component. It doesn't seem to cause any validation issues, but it looks messy

**Comment by justyna-13** [comment]
Hi @DavidGolodetsky - what version of SFUI do you have? 
There was a fix for this issue in the newest version https://github.com/vuestorefront/storefront-ui/issues/1939

**Comment by DavidGolodetsky** [comment]
Fixed in #2062

**Comment by DavidGolodetsky** [comment]
@justyna-13 indeed, it was fixed already. I'm using `0.11.0` so we need to upgrade
