### ISSUE TITLE
[BUG] Empty links in SfLink

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2105]
**Describe the bug**
The default value for a link shouldn't be empty string - with this approach value can be empty what isn't good for a11y

**How to reproduce**
1. Go to SfLink
2. Leave link prop empty

**Expected behavior**
SfLink shouldn;t allow on empty links

**Comment by ymaheshwari1** [comment]
I'm interested.

**Comment by aniamusial** [comment]
@ymaheshwari1 please go ahead :)

**Comment by ymaheshwari1** [comment]
@aniamusial Yes working it.
