### ISSUE TITLE
[BUG] image loading on Safari 

### ISSUE THREAD

**Issue by farukSRKNT** [vuestorefront/storefront-ui#2109]
**Describe the bug**
Images are not loading on Safari unless the page is resized.
Related to #1873 

**How to reproduce**
1. Go to [(https://shopware-pwa.storefrontcloud.io/JEANS/?p=1)](https://shopware-pwa.storefrontcloud.io/JEANS/)
2. See error

**Expected behavior**
load images.

**Actual behavior**
Images are not loading.

**Screenshots**

https://user-images.githubusercontent.com/15245894/141935887-2eaa2042-ea08-4143-bc60-6ce3bc30e75b.mov

**Devices (please complete the following information):**
 - Device: MacBook Pro
 - OS: macOs Big Sur
 - Browser: Safari Version 15.0 (16612.1.29.41.4, 16612)

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by aniamusial** [comment]
Cannot reproduce on our demo. It may be connected to https://github.com/vuestorefront/storefront-ui/issues/1570, so it will be implemented in 0.12. @farukSRKNT do you set width and height to the images? WebKit browsers like Safari may cause such issues without it.

**Comment by nicoanders** [comment]
This is still a problem at least in Safari 15.3
