### ISSUE TITLE
[BUG] Mutating prop errors on Storybook components 

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2128]
**Describe the bug**
Mutating prop errors appearing in console like this:
![Screenshot from 2021-11-24 07-53-23](https://user-images.githubusercontent.com/32042425/143193855-d9799939-5147-4545-bcca-f5502b3c7104.png)

Components to fix and prop causing error: 

- SfAddressPicker - selected
- SfAddToCart - qty
- SfColorPicker - isOpen
- SfComponentSelect - selected
- SfDropdown - isOpen
- SfCheckbox - selected 
- SfPagination - current 
- SfContentPages - active

**How to reproduce**
1. go to the Storybook 
2. open component and try to make some actions
3. see the error in console

**Expected behavior**
No errors appearing.

**Actual behavior**
What actual happened.

**Code examples**
Add data property to pass the prop and use it in component. 

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by peoray** [comment]
Can I get this issue?

**Comment by justyna-13** [comment]
@peoray sure :)
