### ISSUE TITLE
[FEATURE]: Storefront UI Rating Input Component

### ISSUE THREAD

**Issue by sabasayer** [vuestorefront/storefront-ui#2129]
**Describe how this feature will help us improve**
There is a Rating component at the Storefront UI library but it is not an input.
For product review previews it is useful but when user is adding a review like below example rating selection needed.
I used select input for now.

![image](https://user-images.githubusercontent.com/45066901/142627686-e72a8d37-a033-4ca9-87c9-d325bcbee0b8.png)

![image](https://user-images.githubusercontent.com/45066901/142627517-c507ee2b-4061-46c7-8430-bbecf8b84637.png)

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
Create a selectable rating input component

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-18) by [Unito](https://www.unito.io)

**Comment by ztickm** [comment]
@sabasayer @aniamusial Can I get this issue assigned to me?
