### ISSUE TITLE
[BUG] yarn dev does not purge css from node_modules

### ISSUE THREAD

**Issue by factormaarten** [vuestorefront/storefront-ui#2145]
**Describe the bug**
When running `yarn dev` the css in node_modules does not get purged. While in `yarn build` it does get purged. This causes for friction during development.

**How to reproduce**
1. Create a new component, for example o-top-bar.vue (instead of sf-top-bar.vue)
2. Use the class sf-top-bar__container in your custom component
3. Replace SfTopBar with the new OTopBar
4. Remove any reference to SfTopBar
5. Run `yarn dev`

**Expected behavior**
sf-top-bar__container class should not be rendered in the css, as it is not used in the project anywhere

**Actual behavior**
sf-top-bar__container class does get rendered

**Comment by aniamusial** [comment]
Hey @factormaarten this is not SFUI issue, but VueStorefronts - we do not use purge css in the lib. Feel free the report this ticket in repository here: https://github.com/vuestorefront/vue-storefront
