### ISSUE TITLE
[FEATURE] Docs: Switch tabs order in docs

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2149]
**Describe how this feature will help us improve**
Change tabs order to have docs first and move `Css Custom Properties` addon next to `Controls` to be more available for users.  
![image](https://user-images.githubusercontent.com/32042425/144999738-ba9197d3-d591-4a22-9157-af1461d0d2d9.png)

![image](https://user-images.githubusercontent.com/32042425/144999765-7719093a-c32f-47bf-9348-7a6c20f2390b.png)

Issue connected with  #2040.

**Is your proposal related to a problem?**
No.

**Describe the solution you'd considered**

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by ymaheshwari1** [comment]
I'm interested in working on this.

**Comment by AdamPawlinski** [comment]
Hi, are you still interested in this task @ymaheshwari1, if so I can assign it to you?

**Comment by ymaheshwari1** [comment]
> Hi, are you still interested in this task @ymaheshwari1, if so I can assign it to you?

Yes

**Comment by ymaheshwari1** [comment]
@AdamPawlinski I have explored this, but we can't move `CSS custom properties` just after controls, but we can move it after actions or before controls, the reason being, controls and actions are part of storybook/addon-essentials, so we can't add it between them.
To make it possible we need to remove the usage of addon-essentials and use specific addons.

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 I'm sorry I've missed your answer. You are right, so let's move it next to actions tab. Would you be able to prepare the PR for this?

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 I'm sorry I've missed your answer. You are right, so let's move it next to actions tab. Would you be able to prepare the PR for this?

Sure

**Comment by AdamPawlinski** [comment]
So, I assigned it to you. Thanks in advance :)

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 I reopen it and you can add your PR regarding switching `canvas` and `docs` to this task.
