### ISSUE TITLE
[FEATURE] Enabling the use of image compression in components with SfImage

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2155]
**Describe how this feature will help us improve**
Using image compression has influence on page performance and it can significantly improve core web vitals scores. 

**Is your proposal related to a problem?**
Poor core web vitals score because of uncompressed images. 

**Describe the solution you'd considered**
I suggest taking following steps:
- Identify components which needs to be refactored to allow using image compression (preferably [nuxt-image](https://image.nuxtjs.org/))
- investigate how to use nuxt-image with SfImage component in live projects
- investigate using SfCimage as the option in molecules or organisms which already use SfImage
- apply refactors in components and test it

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by AdamPawlinski** [comment]
For now the best solution it would be to use nuxt-image module because of many providers that can be used. 
So we got to possibilities to consider: 
- add this module on VSF side using $img variable which will generate transformed image https://image.nuxtjs.org/api/$img, it can be done faster and will be good for fixing performance results on demo, but in my opinion it won't be great for users (need development on their side),
- other option is to implement nuxt-image on SFUI side by adding new component or refactoring SfImage component - add possibility to change it to nuxt-img element by prop similarly like in SfLink component. But after this change other components using Sfimage should also be refactored to allow passing props to this new component. Components that needs refactoring, in my opinion are:
- SfBanner - doesn't utilize SfImage
- SfCard 
- SfGallery
- SfTile  - doesn't utilize SfImage 
- SfCollecteProduct 
- SfGroupedProduct 
- SfHero - doesn't utilize SfImage 
- SfProductCard
- SfProductCardHorizontal 
Components which don't use SfImage will have to include the same props as new component (with nuxt-mage) to preserve consistency across whole lib. The second approach, I think is better for users but need lots of work. So it can be done in two steps: first SfImage,  SfGallery, SfProductCard and SfProductCardHorizontal  as the most used components and in the next the rest. Let me know what you think about this solutions.

**Comment by AdamPawlinski** [comment]
Regarding optimization image providers for demo purposes, we can use default one - ipx which is open-source and self-hosted so we would have to maintain it somehow. Otherwise we can use paid solutions like cloudinary or imgix but their free plans are limited, so probably we would have to pay for it.

**Comment by aniamusial** [comment]
<img width="1426" alt="Zrzut ekranu 2021-12-29 o 14 10 52" src="https://user-images.githubusercontent.com/41487496/147665934-cf65aa40-6e25-4556-abf8-333d9978b89e.png">

validation bug appears on nuxt project
