### ISSUE TITLE
[BUG] SfProductCardHorizontal wishlist prop and action is now working

### ISSUE THREAD

**Issue by sabasayer** [vuestorefront/storefront-ui#2161]
**Describe the bug**
SfProductCardHorizontal wishlist prop and action is now working.

**How to reproduce**
1. Just render a SfProductCardHorizontal component with isInWishlist = true and try to catch the event.

**Expected behavior**
if IsInWishlist prop is true 'save for later' text should change.
clicking to 'save for later' button should trigger @click:wishlist event

**Actual behavior**
IsInWishlist prop and @click:wishlist event now working

**Code examples**

In the below code example prop and event now working

```
//Write code here
```
<SfProductCardHorizontal
   ...
    :isInWishlist="isInWishlist({product})"
    @click:wishlist="toggleWishlist({ product })"
    ...
  >

**Screenshots**

![image](https://user-images.githubusercontent.com/45066901/145802231-65e2eb64-cefd-42e5-ab8d-1044cddcac4f.png)

**Devices (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All

**Comment by aniamusial** [comment]
Hey @sabasayer isWishlist prop is working only for the smartphone version with heart icon. You can add some logic for "Save for later" button using "actions" slot. Hope that helps :)
