### ISSUE TITLE
[BUG]  <button> is missing required "type" attribute

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/storefront-ui#2168]
**Describe the bug**
`SfButton` component does not pass HTML validation because there is a missing `type` attribute. It should be a type `button` by default. Other available options are: `submit` and `reset`

**How to reproduce**
1. Inspect any page that contains SfButton component
2. Observer the errors
![Screenshot 2021-12-15 at 13 49 12](https://user-images.githubusercontent.com/11998249/146189464-7c4c7e1d-db54-41e8-ad1e-6c6babee122c.png)

**Expected behavior**
SfButton component should pass HTML validation.

**Actual behavior**
SfButton fails HTML validation.

u would like to add but was not sure which section it fits. For example tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by JohnAntonios** [comment]
Hi I'm interested in picking up this bug.

**Comment by justyna-13** [comment]
@JohnAntonios  It's yours :)
