### ISSUE TITLE
[BUG] SfTextarea in Form - too big on mobile view

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2175]
**Describe the bug**
There is a SfTextarea in Form template. On mobile view, SfTextarea is too big and too close to another component. It should be adjusted to mobile screen and has a bigger top margin

**How to reproduce**
1. Go to Templates > Form
2. Change on mobile view
3. Scroll down to SfTextarea

**Expected behavior**
SfTextarea dimensions should be adjusted to mobile screens 

**Actual behavior**
SfTextarea is too big for mobile screens and it's too close to SfRating component 

**Screenshots**
![Screenshot from 2021-12-21 10-11-48](https://user-images.githubusercontent.com/46591755/147044976-f1812cee-bd46-4b05-bcf1-4229056a89c0.png)

**Comment by ejgonzalez17** [comment]
Hello, I would like to contribute by making this issue

**Comment by justyna-13** [comment]
HI @ejgonzalez17 :) great! This task is yours

**Comment by ejgonzalez17** [comment]
Hello, I already made the Pull Request for this issue, I am attentive to your comments and corrections
