### ISSUE TITLE
[DOCS] Components with cloudinary images don't display images on docs tab

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2176]
**Describe the bug**
Components with cloudinary images don't display images on docs tab. These components are:

- SfBanner
- SfBannerGrid
- SfHero

**How to reproduce**
1. Go to SfBanner
2. Click on docs
3. Scroll down to last example with cloudinary image

**Expected behavior**
Images are displayed in canvas and in docs tabs

**Actual behavior**
Images are displayed only in canvas tab

![146736053-d9c05a77-5944-4dca-a4ee-5ce8c0d70aa4](https://user-images.githubusercontent.com/46591755/147082504-c53167cf-d538-4823-b193-b4ceaca9fd4e.png)

**Comment by AdamPawlinski** [comment]
Looks like all this components have proper CImages added, so we can close it, right @justyna-13 ?
