### ISSUE TITLE
[BUG] SFProductCard component showAddToCartButton prop is not working

### ISSUE THREAD

**Issue by sabasayer** [vuestorefront/storefront-ui#2184]
**Describe the bug**
SFProductCard component showAddToCartButton prop is not working. 
It always visible.

**How to reproduce**
1. Set showAddToCartButton prop to false
2. It still shows the button

**Expected behavior**
showAddToCartButton prop should show button by its value

**Actual behavior**
showAddToCartButton prop is not working

**Screenshots**

https://user-images.githubusercontent.com/45066901/147737703-fc4a80cb-ead6-456d-ba25-7281944554ef.mov

**Devices (please complete the following information):**
 - Device: Desktop
 - OS: Macos
 - Browser: Chrome

**Comment by lucadido06** [comment]
i can work on this
