### ISSUE TITLE
[BUG] Add .history file in .gitignore

### ISSUE THREAD

**Issue by ymaheshwari1** [vuestorefront/storefront-ui#2186]
**Describe the bug**
When having Git history extension it generates a history file which is a local file and should not be pushed to git.

**How to reproduce**

**Expected behavior**
.history file should be ignored when pushing to remote

**Actual behavior**
We can push .history file to git 

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by ymaheshwari1** [comment]
I'm interested in working on this.

**Comment by aniamusial** [comment]
Hey @ymaheshwari1 thank you for reporting, feel free to work on this one :)
