### ISSUE TITLE
[BUG] SfGallery glitching when redirecting from a page

### ISSUE THREAD

**Issue by DavidGolodetsky** [vuestorefront/storefront-ui#2190]
**Describe the bug**
When I use the SfGalley component on a page and then redirect away from (inner routes) gallery is glitching for a split of a second and shows me a row of images that I have in it. 

**Additional context**
I checked the code of the SfGallery component and it seems like it's caused by this part:
```
  beforeDestroy() {
    if (this.glide) {
      this.glide.destroy();
    }
  }
```
I wonder if we need it in the first place? Is there an actual memory leak without destroying glide instance?

**Comment by DavidGolodetsky** [comment]
Adding setTimeout fixes the problem, what do you think of this fix?
```
beforeDestroy() {
    if (this.glide) {
      setTimeout(() => this.glide.destroy(), 0);
    }
  }
```
ut the question remains - do we need to destroy Glide instance at all?

**Comment by AdamPawlinski** [comment]
@DavidGolodetsky Hi, could you please help me reproduce this behavior? I checked it in a few implementations without result. Maybe it is a question of the version of SFUI, you use.

**Comment by DavidGolodetsky** [comment]
Also, it seems to be related to this [issue](https://github.com/vuestorefront/storefront-ui/issues/2193) about Glide.js. Overall my impression is that the lib is unreliable and the project looks abandoned. Is there any chance to review this dependency?

**Comment by DavidGolodetsky** [comment]
Couldn't reproduce either, maybe it's something on our side. I guess we can close it in such case

**Comment by AdamPawlinski** [comment]
Ok, thanks for checking. If it happens again, please let me know.
