### ISSUE TITLE
[BUG]  SfBottomNavigation is hidden for screen resolutions 1024 x 1366 (IPad Pro)

### ISSUE THREAD

**Issue by RafalDobrowolski** [vuestorefront/storefront-ui#2192]
**Describe the bug**
Currently on mobile view (screen resolutions 1024 x 1366) `SfBottomNavigation`  component is not shown.

**How to reproduce**
1. Go to `mobile view`
2. Select `IPad Pro device - screen resolutions 1024 x 1366`

**Expected behavior**
 On mobile view (screen resolutions 1024 x 1366) `SfBottomNavigation`  component should be shown.

<img width="520" alt="Screenshot 2022-01-05 at 14 48 31" src="https://user-images.githubusercontent.com/9588193/148228178-d04172e3-1522-4c58-974c-e504e730f59a.png">

**Actual behavior**
 On mobile view (screen resolutions 1024 x 1366) `SfBottomNavigation` component is not shown.

<img width="475" alt="Screenshot 2022-01-05 at 14 41 08" src="https://user-images.githubusercontent.com/9588193/148228733-382f2a54-1d44-4d34-b8e7-ef831e7b11c0.png">
.

**Comment by justyna-13** [comment]
SfBottomNavigation component has `.smartphone-only` class that causes this problem. Can be solved in your own project after removing this class and adding own break points
