### ISSUE TITLE
[BUG] Tablet - Navigation menu has unexpected behavior when the device is being rotated from portrait to landscape

### ISSUE THREAD

**Issue by scernisevs** [vuestorefront/storefront-ui#2195]
**Describe the bug**
Navigation menu has unexpected behavior when the device is being rotated from portrait to landscape

**How to reproduce**
1. Go to https://demo-ct.vuestorefront.io/ on an device with a view port of 768px (iPad / iPad mini)
2. Click on Menu
3. Rotate the device
4. Notice that the menu is still in the modal and it can't be closed even after navigation to another page

**Expected behavior**
The modal should no longer be visible in landscape mode

**Actual behavior**
The menu is still in the modal and it can't be closed even after navigation to another page

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**
![image](https://user-images.githubusercontent.com/73180534/148397672-ad8bd110-8f1d-4570-98e6-f9d7bd9f9ae4.png)

![image](https://user-images.githubusercontent.com/73180534/148397643-078fb622-4bce-42ce-97b8-1885ef796558.png)

**Devices (please complete the following information):**
 - Device: iPad Mini 2019 
 - OS: iOS 13.4
 - Browser: Safari

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-14) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
Hi @scernisevs I suppose it is connected with this issue #2196 so if you implement it utilizing SfMegaMenu it should work correctly.

**Comment by FRSgit** [comment]
Hi @scernisevs!

Has answer by @AdamPawlinski resolved your issue? If yes - please close it, if not - please write what happened when you've tried it.

FYI: As a part of SFUI1 [being LTS](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page) I'm making some repo housekeeping and marking this issue as stale. It will be closed after a week without response.

Thanks!

**Comment by FRSgit** [comment]
Hey,

As a part of LTS housekeeping I'm closing this issue. Please open new issue if you think it still persist or don't hesitate to reach out to us on [Vue Storefront discord channel](https://discord.com/invite/vuestorefront)!
