### ISSUE TITLE
[BUG] Mobile - The Menu is not being closed automatically after the navigation has been done

### ISSUE THREAD

**Issue by scernisevs** [vuestorefront/storefront-ui#2196]
**Describe the bug**
The Menu is not being closed automatically after the navigation has been done
It looks like it is not responding, the only way for the user to continue browsing the app is to close the menu by clicking on the "Menu" button at the bottom of the page, then it can also be seen that the navigation to the page did occur.

**How to reproduce**
1. Go to https://demo-ct.vuestorefront.io/ on a mobile device
2. Click on Menu
3. Press on Mens or Womens
4. See that no visual changes occur and it seems that nothing has happened

**Expected behavior**
The menu should expand as there is a chevron indicating subcategories
The menu should be closed after the user has navigated to the relevant page of the menu item

**Actual behavior**
The navigation to the relevant page does happen but the menu obscures it and doesn't close. It can seem for the user that nothing is happening or that the click to the menu item is not being registered.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**
![image](https://user-images.githubusercontent.com/73180534/148398427-90ae06d5-0086-4661-9b9b-0dd1ec9c69ec.png)

**Devices (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS v15.1
 - Browser: Safari

**Comment by ymaheshwari1** [comment]
Hi, @scernisevs, I think this issue is specific for the [commerce-tools template](https://github.com/vuestorefront/template-commercetools).

**Comment by scernisevs** [comment]
hi @ymaheshwari1 , thank you for responding! 

I believe this would be related to Storefront UI, as the issue was reproduced on a custom integration cloned from the [boilerplate](https://github.com/vuestorefront/ecommerce-integration-boilerplate) 

Please let me know if there will be any other question, I will be happy to assist in reproduction of the bug.

cc: @WojtekTheWebDev

**Comment by AdamPawlinski** [comment]
Hi @scernisevs  I'm sorry for responding so late. I believe it is question of implementation rather than SFUI. If you cloned it from boilerplate, you can see that there is only one level of menu applied in HeaderNavigation component and it uses SfModal to display content. 
But we have SfMegaMenu component for such purposes so you can base on our storybook example to build similar multilevel mobile menu. http://localhost:6006/?path=/story/components-organisms-megamenu--common Please let me know if it was helpful.
