### ISSUE TITLE
[FEATURE] Mobile - Category (PLP) - Add to Cart CTA

### ISSUE THREAD

**Issue by scernisevs** [vuestorefront/storefront-ui#2197]
**Describe how this feature will help us improve**
Currently there is no way to add a product to cart from PLP, users must go to the PDP page. This results in an extra page load, increased time for the checkout and could result in conversion drop

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
Adding an Add to Cart CTA to mobile

![image](https://user-images.githubusercontent.com/73180534/148528854-c9b7c3ae-4672-4bb0-bca5-ca5b33b65d50.png)

**Comment by aniamusial** [comment]
Hey @scernisevs this was done on purpose - the biggest ecommerce services are not recommending to use such buttons on mobile, when the tiles are close together.
