### ISSUE TITLE
[BUG] Double mounting of carousel component on PDP

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2204]
**Describe the bug**
SfCarousel component is mounted twice upon entering PDP. It is somehow related to composable `useProduct` being twice used for product and related products data. Both are searched in `onSSR`.

SfCarousel is also wrapped by SfLoader. Removing SfLoader is making carousel to mount once. Changing `loading` prop from one that is coming from `useProduct` to one that is from `useCart` (just is other than `useProduct`) is also making to mount carousel once (with SfLoader not removed).

**Comment by aniamusial** [comment]
Closing as it is not SFUI related
