### ISSUE TITLE
[FEATURE] Add slot for image to SfImage component

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/storefront-ui#2206]
**Describe how this feature will help us improve**
Creating a slot for image opens possibility to use custom components to render images. For example if you create a Nuxt App, you would use a `<nuxt-img>` component to render images instead of default `<img>` tag. 

**Is your proposal related to a problem?**
Wrap `<img>` tags by slot

**Describe the solution you'd considered**
Wrap this by slot and bind all necessary props: 
```
<img
      :loading="loading"
      v-bind="$attrs"
      :src="src"
      :srcset="srcset"
      :sizes="sizes"
      :class="classes"
      :width="width"
      :height="height"
      :alt="alt"
      @load="onLoad"
      v-on="$listeners"
    />
    <img
      :class="{ 'display-none': loaded || (loaded && placeholder) }"
      class="sf-image--placeholder"
      :src="placeholder"
      alt="Placeholder"
      :width="width"
      :height="height"
    />
```

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by AdamPawlinski** [comment]
There is already the issue for this topic https://github.com/vuestorefront/storefront-ui/issues/2155. It allows adding nuxt-image by setting prop `image-tag` and configure it by `nuxtImgConfig` prop. It will be added in 0.12.0. Wdyt about it @Frodigo ?

**Comment by Frodigo** [comment]
Hi @AdamPawlinski, looks good to me! When do you plan to release 0.12.0 version?

**Comment by AdamPawlinski** [comment]
The plan is for today, but we'll see :)

**Comment by AdamPawlinski** [comment]
@Frodigo there is new version already released so you can try it, but it has many breaking changes so need quite a lot of manual work to update everything properly.

**Comment by Frodigo** [comment]
Thanks, @AdamPawlinski, we park it in our backlog. Closing this one.
