### ISSUE TITLE
[BUG] Attribute "srcset" has invalid value ""

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2216]
**Describe the bug**
Img tag shouldn't have empty srcset attribute.

**How to reproduce**
1. Go to Error page (just one example. It's on every page)
2. Inspect image 
3. See img tag attributes

**Expected behavior**
If there's no value for secret attribute then it shouldn't be added

**Actual behavior**
Empty srcset is added

Error page example
<img width="439" alt="Screenshot 2022-01-26 at 11 09 16" src="https://user-images.githubusercontent.com/46591755/151144415-76f349c6-400d-4ffd-9c9b-6fd939fa88c9.png">

Home page example
<img width="564" alt="Screenshot 2022-01-26 at 11 02 49" src="https://user-images.githubusercontent.com/46591755/151144440-034922d3-46ef-47bb-a434-08d466724a79.png">

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-12) by [Unito](https://www.unito.io)

**Comment by shatanov** [comment]
Hi, I think I can solve this problem)

**Comment by justyna-13** [comment]
Great :) I'm assigning it to you

**Comment by shatanov** [comment]
Hi, I think I can solve this problem)
