### ISSUE TITLE
[BUG] "/Detailed Cart": This page could not be found

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2217]
**Describe the bug**
Wrong link to Detailed Card view in nuxt project located in `packages/nuxt`. 

**How to reproduce**
1. Run nuxt project located in `packages/nuxt`
2. Click on Detailed Cart in header
3. See error

**Expected behavior**
Detailed Cart page exists

**Actual behavior**
Page couldn't be found
<img width="1180" alt="Screenshot 2022-01-26 at 11 33 48" src="https://user-images.githubusercontent.com/46591755/151149175-2ce39926-2570-4749-aa46-330240788001.png">

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-11) by [Unito](https://www.unito.io)

**Comment by JohnAntonios** [comment]
Hi @justyna-13 , can I take this issue?

Thanks!

**Comment by justyna-13** [comment]
Sure @JohnAntonios  :)
