### ISSUE TITLE
[BUG] Class "sf-arrow" duplicated in SfHero

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2218]
**Describe the bug**
In SfHero component there are two SfArrow components. Both have `sf-arrow` classes. This class is added in SfArrow component so it is duplicated in SfHero component. Both `sf-arrow` classes in SfHero component should be removed

**How to reproduce**
1. Go to SfHero component 
2. Scroll down to SfArrow components
3. See `sf-arrow` class

**Expected behavior**
No duplicated classes 

**Actual behavior**
Duplicated classes 
<img width="382" alt="Screenshot 2022-01-26 at 13 20 30" src="https://user-images.githubusercontent.com/46591755/151162007-9f59a705-ae3f-4ea3-b44b-d34eb06f0ba8.png">

**Comment by shatanov** [comment]
Hi, I would like to fix this bug and send PR. Nobody cares about this problem?

**Comment by justyna-13** [comment]
Hi @shatanov, this task is yours :)
