### ISSUE TITLE
[BUG] Product Image is not displaying properly with cart preview panel

### ISSUE THREAD

**Issue by lukasborawski** [vuestorefront/storefront-ui#2233]
**Describe the bug**
Something is not right with the product image displayed along with the Card preview panel. The amount selector is covering it.

**How to reproduce**
1. Add some product to the Card.
2. Open preview panel.

**Expected behavior**
The image should be fully visible.

**Actual behavior**
![Zrzut ekranu 2022-02-1 o 12 20 25](https://user-images.githubusercontent.com/1003999/151959992-8ae7b5b0-997a-41f3-8b7b-eda2327543c5.png)

**Devices (please complete the following information):**
 - Version: `0.11.5` 
 - Device: MacMini
 - MacOS: Big Sur
 - Browser: Chrome (Wersja 97.0.4692.99 (Oficjalna wersja) (arm64))

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-9) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I'm wondering if this is more of an image preparation issue or a component design issue. For now, SfQuantitySelector can be changed to transparent utilizing the CSS modifier class: `.sf-quantity-selector--tranmsparent`, but it doesn't look good, as well.
![Screenshot from 2022-02-01 14-39-54](https://user-images.githubusercontent.com/32042425/151979145-4b092eee-1c68-4af6-9c12-f4d5364a1c1f.png)
