### ISSUE TITLE
[BUG] SfCollectedProduct - more-actions - class is being added to <template> tag which is incorrect and results in unexpected behavior

### ISSUE THREAD

**Issue by scernisevs** [vuestorefront/storefront-ui#2239]
**Describe the bug**
SfCollectedProduct - more-actions - class is being added to <template> tag which is incorrect and results in unexpected behavior.

As a result passing the prop hasMoreActions as false doest do anything and three dots are still displayed

**How to reproduce**
1. Pass hasMoreActions prop as false to SfCollectedProduct
2. Observe that the dots are still visible

**Expected behavior**
The dots should not be visible if hasMoreActions has been passed as false.

The class binding doesnt work on <template> tag, it can be moved to a wrapper <div> 

**Actual behavior**
Dots are being visible when the relevant prop is being passed.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
    <slot name="more-actions" v-bind="{ actionsHandler }">
      <template :class="{ 'display-none': !hasMoreActions }">```

**Comment by shatanov** [comment]
Hi, I would like to deal with this problem, I think I know how to solve this bug)
