### ISSUE TITLE
[FEATURE] nuxt-module update

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2251]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
A concise description of your preferred solution. Things to address include:

  - Details of the technical implementation
  - Tradeoffs made in design decisions
  - Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.

**Additional context**
Anything you would like to add but was not sure which section it fits.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-67) by [Unito](https://www.unito.io)

**Comment by dkacper** [comment]
After StorefrontUI v2 release we are not going to implement new feature for the v1.
