### ISSUE TITLE
[BUG] SfColorPicker: color items are outside of the overlay

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2258]
**Describe the bug**
In SfColorPicker when in a vertical position, the color items are displayed outside of the overlay. 
 
![Screenshot from 2022-02-09 14-27-51](https://user-images.githubusercontent.com/32042425/153213120-416bb8c2-1973-47e9-a7ad-03523472cc93.png)

**How to reproduce**

**Expected behavior**

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-70) by [Unito](https://www.unito.io)

**Comment by ymaheshwari1** [comment]
Hi, I am interested in working on this.

**Comment by justyna-13** [comment]
Ok @ymaheshwari1 :)

**Comment by ymaheshwari1** [comment]
Thank You @justyna-13 
Do we need to make it scrollable or do we need to increase the height of the overlay?

**Comment by justyna-13** [comment]
@ymaheshwari1 here you can find our designs for color picker https://www.figma.com/file/RwtFNOcNyrnV74BGKAUUcq/Storefront-UI-%7C-Design-System---v21?node-id=4392%3A15778 
If there are more colors it increases its size :)

**Comment by AdamPawlinski** [comment]
I've checked if this is only a Storybook issue, and after adding a vertical color picker to the product card it looks like that:
![Screenshot from 2022-02-10 12-18-21](https://user-images.githubusercontent.com/32042425/153396836-6284159f-001a-46f1-aba9-5209faa7f5d2.png)
So it definitely needs to be fixed :)

**Comment by ymaheshwari1** [comment]
> I've checked if this is only a Storybook issue, and after adding a vertical color picker to the product card it looks like that: ![Screenshot from 2022-02-10 12-18-21](https://user-images.githubusercontent.com/32042425/153396836-6284159f-001a-46f1-aba9-5209faa7f5d2.png) So it definitely needs to be fixed :)

So we are on the same page that when having more colors we will be increasing the size.

**Comment by AdamPawlinski** [comment]
Not necessarily, now we've got this 5 items limit when an additional button displays "+5". So maybe just change the limit for this case only on mobile?

![Screenshot from 2022-02-10 12-29-24](https://user-images.githubusercontent.com/32042425/153400553-20f2ab50-32a3-4c8b-a01d-faacd1184f74.png)
![Screenshot from 2022-02-10 12-29-33](https://user-images.githubusercontent.com/32042425/153400586-55378d7b-6df6-450e-9100-cd2a4ccae550.png)

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 Hi, how is it going? Will you be able to finish this one, or maybe you need some help, please let us know. Thanks :)

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 Hi, how is it going? Will you be able to finish this one, or maybe you need some help, please let us know. Thanks :)

I am on it, just got some other urgent thing.

**Comment by ymaheshwari1** [comment]
@AdamPawlinski I am able to make the color picker align to the center, but I am quite confused about the count `+5` thing, as I have looked up the code, I found that the logic to display the count is present in the SfProductCard component and not in SfColorPicker component, have I missed something?

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 Yes, you are right I mixed two things here and I'm sorry for that. I think it should be divided into two tasks, in SfColorPicker the overlay should be stretched to be a background for every color, and the issue in SfProductCard should be a separate task in order to manage too many colors in this component, wdyt @justyna-13?

**Comment by justyna-13** [comment]
@AdamPawlinski yes, they should be separated :)

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 Yes, you are right I mixed two things here and I'm sorry for that. I think it should be divided into two tasks, in SfColorPicker the overlay should be stretched to be a background for every color, and the issue in SfProductCard should be a separate task in order to manage too many colors in this component, wdyt @justyna-13?

So, right now should I only handle the first part i.e. the overlay should be stretched for SfColorPicker?
@justyna-13 @AdamPawlinski

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 Yes, that's right You can take care of this part for now. Thanks once again and sorry for this misunderstanding :)

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 Yes, that's right You can take care of this part for now. Thanks once again and sorry for this misunderstanding :)

Thanks, @AdamPawlinski and @justyna-13, and no problem :)
