### ISSUE TITLE
[FEATURE] Configurable aria-label attributes

### ISSUE THREAD

**Issue by MarcinSulowski** [vuestorefront/storefront-ui#2261]
**Describe how this feature will help us improve**
To improve accessibility across different locales we need to be able to modify the values of aria-label attributes.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-71) by [Unito](https://www.unito.io)

**Comment by shatanov** [comment]
Hi, could you describe the task in more detail, then I would be able to take charge of its implementation?

**Comment by MarcinSulowski** [comment]
Yes. Currently, If you want to use a component that has the `aria-label` attribute, such as SfBreadcrumbs, the value of the `aria-label` attribute is fixed and there's no way to change this. Aria-label attributes need to contain text in the proper language of the page, so if the site is in Spanish, then the aria-label attribute text should also be in Spanish for the sake of screen readers. In order to make that happen, we need to allow for modification of that attribute (that is, if a component has that attribute) for example with props:

`SfBreadcrumbs.vue simplified`
![Screenshot 2022-02-11 at 16 49 39](https://user-images.githubusercontent.com/34214733/153623422-90f73f7a-b8e4-4f6a-b3c7-234d003d8fe1.png)

`Usage`
![Screenshot 2022-02-11 at 16 47 36](https://user-images.githubusercontent.com/34214733/153622971-d3721eb5-da18-473a-8452-3af15696fb81.png)

**Comment by shatanov** [comment]
thanks for the explanation, I think I can solve this problem) @justyna-13, please assign this problem to me)

**Comment by shatanov** [comment]
I determined that the changes will need to be made in the files/components:
`Component/Pages`:
        SfButton -> index.vue
	SfBreadcrumbs.vue
	SfBullets.vue
	SfButton -> SfInput.vue
	SfQuantitySelector -> SfAddToCart.vue
	SfButton -> SfBar.vue
	SfCircleIcon,SfButton -> SfBottomModal.vue
	SfButton -> SfColorPicker.vue
	SfComponentSelect.vue
	SfButton -> SfGallery.vue
	SfButton -> SfNotification.vue
	SfPagination
	SfButton -> SfSlidingSection.vue
	SfCircleIcon,SfButton -> SfBottomNavigationItem.vue
	SfArrow -> SfCarousel.vue
	SfCircleIcon,SfButton -> SfCollectedProduct.vue	
	SfQuantitySelector -> SfGroupedProductItem.vue
	SfSearchBar,SfButton -> SfHeader.vue
	SfArrow -> SfHero.vue	
	SfCircleIcon,SfButton -> SfProductCard.vue	
	SfButton -> SfProductCardHorizontal.vue
	SfCircleIcon -> SfSidebar.vue
	SfIcon -> SfStoreLocator.vue
	SfButton -> Category.vue
	SfButton -> Home.vue
	SfColor -> Product.vue

`Stories file`:
        SfArrow.stories.js
	SfCircleIcon.stories.js
	SfColor.stories.js
	SfQuantitySelector.stories.js
	SfButton -> SfBottomModal.stories.js
	SfSearchBar.stories.js
