### ISSUE TITLE
SfInput label references the wrong input in some cases

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/storefront-ui#2262]
The `for` attribute of the label in SfInput uses the `name` prop, but the id of the input element is the calculated value `idWithoutWhitespace`, which is calculated from the name prop but can be different from the name prop of course. This would lead to the label referencing a not existent input-id ;) 

https://github.com/vuestorefront/storefront-ui/blob/fcbddb150822605ac243718d4ea859659be97948/packages/vue/src/components/atoms/SfInput/SfInput.vue#L28

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-72) by [Unito](https://www.unito.io)

**Comment by shatanov** [comment]
Hi, can you please give an example of such an error?

**Comment by niklaswolf** [comment]
Sure, it's quite simple:
```javascript
<SfInput name="with whitespace"/>
```
The `id` attribute will be `withwhitespace`, the `for`-attribute will remain `with whitespace`.

**Comment by shatanov** [comment]
OK, now I understand what you meant) initially I didn't quite understand the problem. I'll take care of it)

**Comment by shatanov** [comment]
@justyna-13, please assign this problem to me)

**Comment by justyna-13** [comment]
@shatanov done :)
