### ISSUE TITLE
[BUG] SfImage ignores width and height when use nuxt-img

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/storefront-ui#2277]
**Describe the bug**
When I want to use `SfImage` component with `image-tag="nuxt-img"` prop,  rendered image does not have width and height attributes.

**How to reproduce**
1. Add SfImage width `image-tag` prop equals `nuxt-img`, width, and height
2. Open browser
3. Open dev tools
4. Inspect image
5. Observe that I'm age does not have width and height

**Expected behavior**
Rendered image has `witdh` and `height` attributes.

**Actual behavior**
Image is rendered without with and height. 

**Code examples**
```
<SfImage
          image-tag="nuxt-img"
          :src="https://res-4.cloudinary.com/dnozky7on/image/upload/f_auto,q_auto/media/catalog/product/m/s/msh12-red_main_1.jpg"
          :alt="image"
          width="216"
          height="268"
        />
```

**Screenshots**
![Screenshot 2022-02-21 at 09 24 48](https://user-images.githubusercontent.com/11998249/154916064-6d25984a-8ad3-45c8-944f-3062279838a2.png)

**Devices (please complete the following information):**
 - Device: MacBook
 - OS: macOS Monterey 12.0.1
 - Browser: Chrome 98.0.4758.80

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-74) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
@Frodigo When you use nuxt-img, you can pass width and height props by 
```
:nuxtImgConfig="{
        width: 20, 
        height: 20
}"
```
But of course, it should be possible in the normal way, so I'll check it.

**Comment by Frodigo** [comment]
Hey @AdamPawlinski ,

Thanks for the information!

it would be great if this works in the "normal" way because people who have already used images and want to use nuxtImg need to change the way of passing width and height in all places where SFImage is used. 

Thanks,
Marcin
