### ISSUE TITLE
[FEATURE] Change icons to webp format

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2283]
**Describe how this feature will help us improve**
Icons kept in package as svg are very heavy and are slowing down the library. We should change them to webp format.

**Additional context**
Possible breaking change

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-75) by [Unito](https://www.unito.io)

**Comment by RafalDobrowolski** [comment]
It doesn't make sense create new component for handling webp format. Instead of we can use SfImage component.
