### ISSUE TITLE
[BUG] SfImage placeholder is causing layout shift

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2284]
**How to reproduce**
How to reproduce: 

1. Measure how page loads images with low internet connection fe. using web tools, lighthouse.
1. See the error about layout shift

**Describe the solution you'd considered**
Setting up strict width and height?

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-76) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
@aniamusial According to me it's a matter of properly setting the image sizes. I did tests on CT locally with the latest version of SFUI and image sizes set on the Category page and it looks like this: 
![image_placeholder_CLS](https://user-images.githubusercontent.com/32042425/155511914-12af7fbc-9f28-4629-b461-98135e087807.gif)
And lighthouse results are not good but CLS is okay:
![Screenshot from 2022-02-24 11-58-05](https://user-images.githubusercontent.com/32042425/155512074-887bb940-e6e2-431e-b8ac-5256b778cb77.png)
