### ISSUE TITLE
[BUG] Lazy loaded animations are not working

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2287]
**Describe the bug**
We want to lazy load some of not needed components, but after lazy loading them, animations stopped working.

**How to reproduce**
Components in CT repo: [https://github.com/vuestorefront/commercetools/pull/154 - Połącz podgląd](https://github.com/vuestorefront/commercetools/pull/154)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-77) by [Unito](https://www.unito.io)

**Comment by FRSgit** [comment]
Closing as a part of going into [LTS mode](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page). Please open new issue if the problem still persists.
