### ISSUE TITLE
[FEATURE] Implement Lighthouse CI in Github actions

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2288]
**Describe how this feature will help us improve**
This will help us effectively measure performance on each new PR.
https://web.dev/lighthouse-ci/

**Describe the solution you'd considered**

* Integrate for nuxt Homepage and PLP.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-82) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
@aniamusial I think we have it for homepage and we can add test for PLP.
 
![Screenshot from 2022-02-24 12-09-06](https://user-images.githubusercontent.com/32042425/155513403-bd07882b-c152-4f59-87ef-7d68eb06c10f.png)
