### ISSUE TITLE
the link is over the add to cart button [BUG] 

### ISSUE THREAD

**Issue by samberrry** [vuestorefront/storefront-ui#2291]
**Describe the bug**
title link is over the add to cart button 

**How to reproduce**
choose a long title for your cart

**Screenshots**
![1](https://user-images.githubusercontent.com/20775532/155810256-7270ed7e-7dac-4856-bf1e-4106feb1af9c.jpg)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-80) by [Unito](https://www.unito.io)

**Comment by justyna-13** [comment]
Thanks @samberrry :) would you like to fix this issue?

**Comment by samberrry** [comment]
please check the PR. 
Thanks
