### ISSUE TITLE
[FEATURE] Dynamic imports of components

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2300]
**Describe how this feature will help us improve**
This will help us improve the performance of the lib. This should be tested with before/after and in projects. We should chceck which components can be imported like that. (not everything needs to be lazy loaded)
https://vuedose.tips/dynamic-imports-in-vue-js-for-better-performance

**Is your proposal related to a problem?**
No

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-84) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
There was already a task connected with lazy-loaded components, and I made some research about it. I took into consideration a situation when the user can decide what and in what order should be loaded on a page https://github.com/vuestorefront/storefront-ui/issues/1759. There is the proposition of helper function which utilizes intersection observer to discover when a component should be loaded. Also, we can use webpack prefetching to change the order of loading components. So please @aniamusial take a look if sth can be applied to our current situation. But for now, I suppose we should consider sth simpler only to use dynamic loading in templates or organisms.

**Comment by aniamusial** [comment]
@AdamPawlinski agreed, I'll close this one for now
