### ISSUE TITLE
[BUG] SfAccordion story - Property or method "change" is not defined

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2340]
**Describe the bug**
There is an error in console for SfAccordion story. `Property or method "change" is not defined...`

**How to reproduce**

1. Go to SfAccordion
1. See error in console

**Expected behavior**
Story without errors in console

**Actual behavior**
Story with errors in console

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-101) by [Unito](https://www.unito.io)

**Comment by ymaheshwari1** [comment]
Hi, I am interested in working on this.
