### ISSUE TITLE
[BUG] Load only images that are needed at the time of usage

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2346]
**Describe the bug**
There is a problem with hero mobile and desktop banners.
On desktop everything is ok, but on mobile there are 2 images downloaded (for desktop and for mobile) even if one of them is not used.

This has real impact on perf on mobile because we are downloading unnecessary big images (if there are 3 items in hero there are additional 3 images).

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-102) by [Unito](https://www.unito.io)

**Comment by FRSgit** [comment]
Closing this issue as a part of SFUI1 going [LTS](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page). Please open new issue if you think that this is a critical bug 👀
