### ISSUE TITLE
[BUG] Release section in storybook is not organized

### ISSUE THREAD

**Issue by ymaheshwari1** [vuestorefront/storefront-ui#2348]
**Describe the bug**
Having multiple folder for same release and having multiple latest tags

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**
Release section should be organized

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.

```
//Write code here
```

Or add code snippets (Code sandbox)

**Screenshots**
![Screenshot (178)](https://user-images.githubusercontent.com/41404838/159472486-6da0083e-7f1a-4fcd-ac78-1f2003e742a2.png)

**Devices (please complete the following information):**

* Device: [e.g. iPhone6, Desktop]
* OS: [e.g. iOS8.1]
* Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-103) by [Unito](https://www.unito.io)

**Comment by ymaheshwari1** [comment]
I'm interested in making it organized.

**Comment by aniamusial** [comment]
@ymaheshwari1 go ahead :)
