### ISSUE TITLE
[BUG] Link in storybook docs is broken

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2361]
**Describe the bug**
The link in the `Who is using Storefront UI?` section directing to Vintageria is broken:
![Screenshot from 2022-04-06 13-09-13](https://user-images.githubusercontent.com/32042425/161961949-1c44634a-a393-4e78-aa1c-434f0d3a694b.png)

**How to reproduce**

**Expected behavior**

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.

```
//Write code here
```

Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**

* Device: [e.g. iPhone6, Desktop]
* OS: [e.g. iOS8.1]
* Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-111) by [Unito](https://www.unito.io)

**Comment by justyna-13** [comment]
@ymaheshwari1 yes, we should check all links and remove broken ones.

**Comment by ymaheshwari1** [comment]
> and remove broke

Sure
