### ISSUE TITLE
[FEATURE] Create FAQ section

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2363]
**Describe how this feature will help us improve**
We should extend our FAQ section with new questions and answers.

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-113) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
We already have one, but we need to update it and maybe linked it with the components which are mentioned in them.
https://docs.storefrontui.io/?path=/docs/getting-started-development-guide-faqs--page

**Comment by dkacper** [comment]
We are not going to introduce any new features for v1.
