### ISSUE TITLE
[FEATURE] Upgrade babel presets to new version

### ISSUE THREAD

**Issue by RafalDobrowolski** [vuestorefront/storefront-ui#2364]
**Describe how this feature will help us improve**
 Now we use `@vue/app` presets. It's related with @vue/cli-service in version 3. For version 4 is recommended `@vue/cli-plugin-babel/preset`.

https://cli.vuejs.org/migrations/migrate-from-v3.html#vue-cli-plugin-babel-vue-babel-preset-app

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-114) by [Unito](https://www.unito.io)

**Comment by FRSgit** [comment]
Babel has been upgraded and will be released in `0.14`
