### ISSUE TITLE
[BUG] Remove $parent and $children handlers

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2374]
**Describe the bug**
Using this.$parent and this.$children for operating on the dom is considered a bad practice and is not working for most of the website builders. We should remove it from following components:

* SfTabs
* SfAccordion
* SfComponentSelectOption
* SfToastItem
* SfContentCategory
* SfContentPage
* SfFooterColumn
* SfTab

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-125) by [Unito](https://www.unito.io)

**Comment by shatanov** [comment]
Hi, @aniamusial, I would like to take this issues, but we need to discuss what to replace $parents and $children with. as it seems to me, this.$parent can be replaced with provide/inject, and this.$children on refs, what do you think?

**Comment by shatanov** [comment]
> Hi @shatanov, I can assign this task to you if you're still interested in it :) when it comes to your question about of solving this, I think it's important to get rid of $parent and $children and the exact solution will be checked when PR is done :)

OK, I can try)

**Comment by justyna-13** [comment]
@shatanov great :) it's yours

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
