### ISSUE TITLE
[BUG] Storybook Molecules SearchBar console shows error

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2376]
**Describe the bug**
Console/Devtools shows error when search bar in molecules section is visited.

**Steps to reproduce the behavior:**

1. Go to Storybook
1. Open devtools/console with F12
1. Clean Console
1. Go to Molecules section and choose SearchBar

**Expected behavior**
Console is clear

**Actual behavior**
Error is provided on console

**Screenshots**
![Molecules Search Bar error on console](https://user-images.githubusercontent.com/103260041/164212326-9a08fabb-a7f7-41dc-b06b-51cb64b0e553.png)

**Devices (please complete the following information):**

* Device: [,Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-126) by [Unito](https://www.unito.io)

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 I'm sorry I did this by mistake. I didn't notice that you are already working on this. Could you please make the CR? There are lots of other fixes and we would be grateful for your engagement. Thanks.

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 I'm sorry I did this by mistake. I didn't notice that you are already working on this.
No problem @AdamPawlinski.

> Could you please make the CR?
But as you already created the CR, should I make it again?
