### ISSUE TITLE
[BUG] Storybook Molecules Banner color picker provides error

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2377]
**Describe the bug**
When you try to change color using color picker with dot to move on color chart error is provided on the console and color is not changed

**How to reproduce**

1. Go to Storybook
1. Open Console/Devtools
1. Clean console
1. Go to Molecules section and choose banner
1.  Scroll down to props -> background 
1. Open color picker and change color using dot to move on the color pallete

**Expected behavior**
Color can be and is changed no error is provided

**Actual behavior**
Color is not changed, it autopicks black and provides error on console

**Screenshots**

![Molecules Banner Color picker error](https://user-images.githubusercontent.com/103260041/164225959-e6ced203-1c01-4312-b823-e551eebc41d6.png)
![Molecules Banner Color picker](https://user-images.githubusercontent.com/103260041/164225964-76f987fe-de67-4f85-898e-4dcc2457f305.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-127) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
