### ISSUE TITLE
[BUG] Storybook Organisms Accordion Opening section provides error in the console

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2387]
**Describe the bug**
Opening section on the storybook provides error on the console

**How to reproduce**

1. Go to Storybook
1. Open console/Dev tools
1. Clean console
1. Go to Organisms/Accordion

**Expected behavior**
Everything is good to go you can use section

**Actual behavior**
Console is providing error.

**Screenshots**
![Organisms Accordion Opening section provides error in the console](https://user-images.githubusercontent.com/103260041/165265288-7ad5d270-8f73-40c4-81e6-67909425fcbd.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-135) by [Unito](https://www.unito.io)

**Comment by RafalDobrowolski** [comment]
@MaciejWolowski  @AdamPawlinski  @aniamusial  this issue is closed
