### ISSUE TITLE
[BUG] Storybook Templates Form you can put letter 'e' to the numbers only boxes

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2396]
**Describe the bug**
You can put letter "e" to the boxes zip code and phone number which should be numbers only

**How to reproduce**

1. Go to Storybook
1. Open Section Templates-> Form
1.  Try to put every letter to the Box named "Zip code" and "Phone number"

**Expected behavior**
Nothing happens those boxes are numbers only

**Actual behavior**
You can put letter "e" to the boxes "Phone Number" and "Zip code"

**Screenshots**
![Templates Form you can put letter 'e' to the numbers only boxes](https://user-images.githubusercontent.com/103260041/165544229-91098a55-ed16-4df1-ad74-90074000bfc1.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-138) by [Unito](https://www.unito.io)

**Comment by RafalDobrowolski** [comment]
@MaciejWolowski  There is possibility put only `e` letter. The number input can accept [floating-point numbers], including negative symbols and the e or E character - https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in. After typing `e` letter still is validation error, so validation works :). In my opinion I could leave this solution as we have. WDYT @AdamPawlinski  @aniamusial  @justyna-13 ?
