### ISSUE TITLE
[BUG] Add to Wishlist and Remove from Cart links alignment problem on mobile

### ISSUE THREAD

**Issue by mbelter** [vuestorefront/storefront-ui#2404]
Add to Wishlist and Remove from Cart links colide with each other on mobile devices

![e5b3414e-6506-4950-ab34-c819bb934fe6](https://user-images.githubusercontent.com/93545550/167428347-aeced233-1e60-421b-8e3e-14e86b8192bf.png)
![88527edf-241a-4872-ac89-ff4590e2566d](https://user-images.githubusercontent.com/93545550/167428359-6203058d-e00d-44cd-b846-80bf3b61bf3a.png)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-143) by [Unito](https://www.unito.io)

**Comment by aniamusial** [comment]
This relates to 0.12.2
