### ISSUE TITLE
[BUG] GlideJS sliders memory leak (SfHero and SfCarousel)

### ISSUE THREAD

**Issue by michaelKurowski** [vuestorefront/storefront-ui#2405]
**Describe the bug**
SfHero and SfCarousel don't destroy the glidejs instance which results in HTML elements passed as slots not being cleared by the garbage collector. We've found that glide.destroy is not being called when these components are being destroyed which seem to be the root cause.

**How to reproduce**

1. Go to a page that has a slider
1. Take heap snapshot
1. Go to another page
1. Take heap snapshot
1. Turn on comparison view between both snapshots
1. Find detached HTML elements with positive delta.

**Expected behavior**
HTML elements should be cleared when not needed

**Actual behavior**
SfHero and SfCarousel produce new detached HTML elements while not cleaning the old ones.

**Code examples**

**Screenshots**
![](https://user-images.githubusercontent.com/2772942/168076259-952a53a2-1b07-42ba-b8af-0d53417aa914.png)

**Devices (please complete the following information):**

* Device: MacBook Pro
* OS: MacOS 12.2.1
* Browser: Google Chrome 100.0.4896.127 (Official Build) (arm64)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-144) by [Unito](https://www.unito.io)

**Comment by WojtekTheWebDev** [comment]
More insights, I used tool `fuite` to check memory leaks and I tried it on my app with `SfHero` and `SfCarousel` components, without them and a test where I added `beforeDestroy () { this.glide.destroy() }`. Test results attached. TLDR: when glide instance is destroyed, there are anyway memory leaks related with `glide`. There are no memory leaks in case where there are no components added
[main.txt](https://github.com/vuestorefront/storefront-ui/files/8679721/main.txt)
[main_without_components.txt](https://github.com/vuestorefront/storefront-ui/files/8679722/main_without_components.txt)
[main_with_fix.txt](https://github.com/vuestorefront/storefront-ui/files/8679724/main_with_fix.txt)
.

**Comment by FRSgit** [comment]
Destroying of the glide instance was just added to all affected components (SfCarousel, SfGroupedProduct, SfHero) in #2871.

That fix will be released under version 0.14 - let's see if that help with that problem. If the issue will occur again - please open new issue with a reproduction 👀
