### ISSUE TITLE
[BUG] Storybook Atoms Bullets Do not work properly on Iphone

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2409]
**Describe the bug**
Using Iphone 8+ on Atoms bullets, when you zoom screen you cannot move the screen. It can be an issue when someone want to zoom and read something.

**How to reproduce**

1. Go to Storybook on your Iphone using safari
1. Go to Atoms bullets
1. Zoom screen to the maximum
1. Try to move the screen to see the bullets

**Expected behavior**
You can move the screen whenever you want and inspect whole page

**Actual behavior**
Screen is locked and is going back to the initial position after zoom.

**Screenshots**
![280875544!UNITO-UNDERSCORE!3303406133222180!UNITO-UNDERSCORE!5336642959970589472!UNITO-UNDERSCORE!n](https://user-images.githubusercontent.com/103260041/168846088-820a6772-8888-4773-ace7-6975b80a8059.jpg)
![281367677!UNITO-UNDERSCORE!509141730958481!UNITO-UNDERSCORE!205584719794080500!UNITO-UNDERSCORE!n](https://user-images.githubusercontent.com/103260041/168846339-d56b0e83-293d-4487-bfbe-ff960a34adbb.jpg)
https://user-images.githubusercontent.com/103260041/168846370-f0fcc379-9259-457e-8446-77cc45d5cdf8.mp4

**Devices (please complete the following information):**

* Device: [Iphone 8+]
* OS: [IOS 15.4.1]
* Browser: [Safari 15.4.1]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-147) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
