### ISSUE TITLE
[BUG] Demo Quantity Selector positioning is not good looking on the photos

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2417]
**Describe the bug**
After adding items in the store to the shopping cart. Going to shoping cart quantity selector component size is covering the photos of the product.

**How to reproduce**

1. Using your phone go to SFUI 1 Demo
1. Add few different products to your shopping cart
1. go to your shopping cart
1. inspect quantity selector

**Expected behavior**
Size of the quantity selector component do not cover the product photo or is placed next to it.

**Actual behavior**
Quantity selector component is covering the product photo, if the product is small you cannot see it from under the component

**Screenshots**
![281947601!UNITO-UNDERSCORE!1753957884947539!UNITO-UNDERSCORE!4070855461904212405!UNITO-UNDERSCORE!n](https://user-images.githubusercontent.com/103260041/169539847-b90faaad-6328-4184-8b61-cb549f439dc0.jpg)

https://user-images.githubusercontent.com/103260041/169539812-8028644b-aa2b-436b-92b1-77fe26ace891.mp4

**Devices (please complete the following information):**

* Device: [Xiaomi Redmi note 8 pro/desktop]
* OS: [Newest Android]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-153) by [Unito](https://www.unito.io)

**Comment by justyna-13** [comment]
https://github.com/vuestorefront/storefront-ui/issues/2233 - design issue
