### ISSUE TITLE
[BUG] Button elements are missing type

### ISSUE THREAD

**Issue by bensinca** [vuestorefront/storefront-ui#2430]
HTML validations is failing because of incorrect use of `button `elements, also particular browsers assumes the type of a button if not specified which could cause further bugs. The HTML guidelines suggests that one should _"[...] always specify the type attribute for the `<button>` element. Different browsers may use different default types for the `<button>` element"_

More info : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

Quick way to check the HTML validation is to install @nuxtjs/html-validator

In the SfButton component, I added a `type` attribute to the component:
` type="$options.setType(props.type, props.link)"`
that is using the `setType` option that simply checks the `props.link` and `props.type` if they return null e.g:

``` 
setType(type, link) {
    if (type === null && !link) {
      return 'button'
    } else {
      return type;
    }
 },

Not sure if this is the most efficient idea to check.



┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-170) by [Unito](https://www.unito.io)

**Comment by justyna-13** [comment]
Hi @bensinca there is a possibility to add a type to button component by adding needed value to prop type

**Comment by bensinca** [comment]
@justyna-13 thank you!
