### ISSUE TITLE
[BUG] Storybook Atoms Color Selected view and option works only on mobile and small resolution

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2432]
**Describe the bug**
Selected view and option works only on mobile and small resolution

**How to reproduce**

1. Go to Storybook
1. Go to Components -> Atoms -> Color
1. Change Selected and hasBadge to True
1. Check look of the component at the top and in the example of Selected Stories in High and low resolution on desktop and in mobile

**Expected behavior**
On every device and resolution component looks the same and has white tick on it.

**Actual behavior**
On high resolution using desktop component is missing white tick on it. Check screenshots provided below.

**Screenshots**
![atoms color resolution](https://user-images.githubusercontent.com/103260041/172446257-b3466b21-090c-4044-93f8-27aed153054f.png)
![Atoms Color resolution 2](https://user-images.githubusercontent.com/103260041/172446351-ef014169-d99d-4b77-8e8b-bee329e6b67b.png)
![atoms color res 4](https://user-images.githubusercontent.com/103260041/172446619-a6fceac4-fc4c-454b-ae31-50f96de89dbf.png)
![atoms color res 3](https://user-images.githubusercontent.com/103260041/172446442-3ed8ab83-50d1-40f1-a635-5519059d7903.png)

**Devices (please complete the following information):**

* Device: [Desktop and Mobile]
* OS: [Windows 11]
* Browser: [Chrome and LT Browser]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-174) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
@MaciejWolowski According to Figma there shouldn't be any white tick on the desktop. So if it's ok for you I'll close this task.
![Screenshot from 2022-06-13 08-45-51](https://user-images.githubusercontent.com/32042425/173295527-f8cdfc3a-6118-4c08-b7be-60d9488ae891.png)
