### ISSUE TITLE
[BUG] aria-labels props can't override default component values 

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2433]
**Describe the bug**
SfButton has a new prop aria-label with its default value which will override a text passed by slot. 
An example is on SfButton but the rest of the components also need to be checked. 

**How to reproduce**

1. Go to SfButton
1. See prop aria-label with default value

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-180) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
