### ISSUE TITLE
[FEATURE] Reduce size of images in assets 

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#2447]
**Describe how this feature will help us improve**
We can change .png and .jpg on .webp and reduce size of images

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-196) by [Unito](https://www.unito.io)

**Comment by dkacper** [comment]
@justyna-13  thank you for this suggestion. We released StorefrontUI v2 recently. We still provide support for v1, but unfortunately, we are not going to introduce any new features.
