### ISSUE TITLE
[BUG] Storybook Molecules Bottom Modal component not responsive to changing options

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2457]
**Describe the bug**
BottomModal component is not responsive to changing any options in the storybook which should correspond with component view. Everything is working in canvas section.

**How to reproduce**

1. Open Storybook
1. Go to components -> molecules -> BottomModal
1. Go to canvas section
1. Try to change every option you can find in Controls (increase/decrease size, change content, change isOpen selection, change title)
1. Everything working correctly
1. Go back to Docs section
1. Refresh website
1. Repeat step 4

**Expected behavior**
verything is working correctly and you can see the changing different options changes the component view.

**Actual behavior**
Nothing happens.

**Screenshots**
![Molecules Bottom Modal component not responsive to changing options](https://user-images.githubusercontent.com/103260041/174858653-dd272e18-d031-42a1-b5cf-61611c28e558.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-208) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I see similar errors in other components (SfDropdown or SfModal) which have `inlineStories: false` set in stories settings. Without that setting, they have a broken layout, but now the reactivity in the docs tab is turned off. I found a similar problem in storybook repo https://github.com/storybookjs/storybook/issues/11244 but it considers decorators and was already resolved. I'll look further for the solution.

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
