### ISSUE TITLE
[FEATURE] SfMegaMenu top bar content can't be changed, also no way to listen SfBar: close event

### ISSUE THREAD

**Issue by isntlazy** [vuestorefront/storefront-ui#2460]
**Describe how this feature will help us improve**
To have the flexibility of rewriting content of SfMegaMenu bar content it makes sense to add a new slot there, also it makes sense to have support for new `click:close` event from SfBar

**Is your proposal related to a problem?**
The issue is that I want to have possibility to change content and structure at that place

**Describe the solution you'd considered**
Solution is - adding new named slot to the component and adding listener for SfBar `click:close` event

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-219) by [Unito](https://www.unito.io)

**Comment by dkacper** [comment]
@isntlazy thank you for this suggestion. We released StorefrontUI v2 recently. We still provide support for v1, but unfortunately, we are not going to introduce any new features.
