### ISSUE TITLE
[BUG] Error: Failed to resolve import "../../molecules/SfMenuItem/SfMenuItem" on Vite.js

### ISSUE THREAD

**Issue by runyasak** [vuestorefront/storefront-ui#2481]
**Describe the bug**
I have initiated project, Vue 3 with Vite.js, and try to import some components, such as `SfProductCard`.
Perhaps, the error appear that `Failed to resolve import "../../molecules/SfMenuItem/SfMenuItem" ...`.

**How to reproduce**

1. Initiate project with Vue 3, Vite.js, and TypeScript
1. Install dependencies and @storefront-ui
1. Import `SfProductCard` and implement on `App.vue`
1. Error appear

**Expected behavior**
This error should not appear when import and implement on `App.vue`

**Actual behavior**
The error appear: `Failed to resolve import "../../molecules/SfMenuItem/SfMenuItem" ...`.

**Code examples**

* App.vue

```vue
<script setup>
import { RouterView } from "vue-router";
import { SfProductCard } from "../node_modules/@storefront-ui/vue";
</script>

<template>
  <SfProductCard image="https://picsum.photos/200/300" />
  <RouterView />
</template>
```

* vite.config.ts

```ts
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { join } from "node:path";

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: [
      {
        find: /~(.+)/,
        replacement: join(process.cwd(), "node_modules/$1"),
      },
      {
        find: /@\//,
        replacement: join(process.cwd(), "./src") + "/",
      },
    ],
  },
});
```

**Git repository**
https://github.com/runyasak/my-storefront-ui

**Screenshots**
![image](https://user-images.githubusercontent.com/6861191/184529086-ef1c1d1a-e989-4d1f-9a4d-0fb107a05714.png)

**Devices:**

* Device: Desktop
* OS: macOS Monterey [12.3.1]
* Browser: Chome [104.0.5112.79]

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-240) by [Unito](https://www.unito.io)

**Comment by ymaheshwari1** [comment]
@runyasak Have you tried directly importing storefront-ui components from `@storefront-ui/vue`?

**Comment by runyasak** [comment]
> @runyasak Have you tried directly importing storefront-ui components from `@storefront-ui/vue`?

Yes, I have imported directly from `@storefront-ui/vue`.

You can checkout on my code:
https://github.com/runyasak/my-storefront-ui/blob/main/src/App.vue

Actually, this error is appeared in `@storefront-ui/vue` from `node_modules`.
I'm not sure that my code or configuration work properly or not.

**Comment by ymaheshwari1** [comment]
> properly

https://github.com/runyasak/my-storefront-ui/blob/main/src/App.vue#L3
Can you change the import to `import { SfProductCard } from "@storefront-ui/vue";`

**Comment by runyasak** [comment]
> https://github.com/runyasak/my-storefront-ui/blob/main/src/App.vue#L3 Can you change the import to `import { SfProductCard } from "@storefront-ui/vue";` and check whether if it also throws some error?

I have updated to `import { SfProductCard } from "@storefront-ui/vue";`.
But still got the same error.

**Comment by runyasak** [comment]
However, I have tried on Vue 3 with Webpack from Vue CLI.
There don't have errors with the resolving path.
But errors with `<template functional>` for some Vue 3 syntax breaking changes, like this issue: #2454.
You can check out my demo repo: https://github.com/runyasak/demo-storefront-ui

By the way, we should migrate components to support Vue 3.
And then, fix for resolving the path on Vite.js.

This is just my opinion for discussing.
If I have missed some parts or want to give me some suggestions, please let me know. 😁
