### ISSUE TITLE
[BUG] Storybook Organisms BottomNavigation props options do not work

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2485]
**Describe the bug**
All the options to customise bottomnavigation in the storybook do not work.

**How to reproduce**

1. Go to storybook
1. open section components -> organisms -> BottomNavigation
1. Try to customise component using props on the bottom

**Expected behavior**
Options selected do not work and changes nothing in the component.

**Actual behavior**
You can customise component with options provided.

**Screenshots**
![Storybook Organisms BottomNavigation props options do not work](https://user-images.githubusercontent.com/103260041/187481425-68aae31c-716d-4479-9981-5567f361b8c2.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-254) by [Unito](https://www.unito.io)

**Comment by justyna-13** [comment]
There are listed props for internal components but they aren't connected with a component. It's just as additional information what props will be needed. I can add a shot note that changes in these fields won't affect data in this component :) what do you think about it?

**Comment by MaciejWolowski** [comment]
Good idea

pon., 31 paź 2022, 14:05 użytkownik Justyna ***@***.***>
napisał:

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
