### ISSUE TITLE
[BUG] Storybook Organisms CollectedProduct regular price do not allow you provide currency

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2486]
**Describe the bug**
Prop in component regular price that should allow you to set price do not let you provide currency. In other places you cannot also set currency.

**How to reproduce**

1. Go to storybook
1. open section components -> organisms -> CollectedProduct
1. scroll down to regular price prop
1. write down some number and try to change currency.

**Expected behavior**
You can change price and currency. Or set price in one prop and currency in other.

**Actual behavior**
Price changes to just number without currency.

**Screenshots**

![Storybook Organisms CollectedProduct screen 1](https://user-images.githubusercontent.com/103260041/187674866-013496ba-e72d-4e40-9349-1f27e1a8cf62.png)

![Storybook Organisms CollectedProduct regular price do not allow you provide currency](https://user-images.githubusercontent.com/103260041/187674883-46fd6b14-31d9-4060-8c73-10d7514c213c.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [chrome]

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-257) by [Unito](https://www.unito.io)

**Comment by justyna-13** [comment]
This problem is caused by chosen number field in storybook for this value. There is a possibility to add number or string to component prop. In storybook we can have text field but then it will be possible to write anything not only add a desired currency to a number
