### ISSUE TITLE
[BUG] Storybook Organisms Footer console issue after writing -1 in prop

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2487]
**Describe the bug**
You can set console to show issue by writing -1 in the prop.

**How to reproduce**

1. Go to storybook
1.  Open console or devtools in browser
1. Go to section components -> organisms -> footer
1. Scroll down to column prop
1. Write inside or set up -1
1. Check console

**Expected behavior**
You cannot write or set up -1 and there is no issues

**Actual behavior**
You can see issue on the console and you can set negative number of the column.

**Screenshots**

![Storybook Organisms Footer console issue after writing -1 in prop](https://user-images.githubusercontent.com/103260041/187942596-22c2fb8b-eba7-42e0-8402-ae662c6de7ea.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-259) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
