### ISSUE TITLE
[BUG] Storybook Organisms Header some props do not work

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2488]
**Describe the bug**
When you try to customize Header props: searchValue, wishlistitemsQty, cartitemsQty do not work.

**How to reproduce**

1. Go to storybook
1. Go to section components-> organisms-> header
1. scroll down to props
1. try to use props: searchValue, wishlistitemsQty, cartitemsQty
1. Check if component changes view

**Expected behavior**
Using this props you can customise component.

**Actual behavior**
Nothing happens.

**Screenshots**
![Storybook Organisms Header some props do not work](https://user-images.githubusercontent.com/103260041/188450345-b551ea33-4e5a-4589-8e3d-12f2e01ea653.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [chrome]

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-263) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
