### ISSUE TITLE
[BUG] Storybook Organisms MegaMenu Props and events do not work

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2489]
**Describe the bug**
After opening MegaMenu component customisation using props and trying to create events do not work.

**How to reproduce**

1. Go to storybook
1. Open section components -> organisms -> MegaMenu
1. Scroll down for components and try to customise and create event

**Expected behavior**
You can customise component and you can create events using the component.

**Actual behavior**
Nothing happens.

**Screenshots**
![Storybook Organisms MegaMenu Props and events do not work](https://user-images.githubusercontent.com/103260041/188634391-3d855816-5ddd-4839-9f9e-5a5ef2804725.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [chrome]

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-266) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
