### ISSUE TITLE
[BUG]  Storybook Organisms Tabs props do not work

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2492]
**Describe the bug**
Storybook Organisms Tabs props do not work

**How to reproduce**

1. Go to Storybook
1. Go to section components -> organisms -> tabs
1. Scroll down for props
1. Use props and check component view

**Expected behavior**
You can customise component using props

**Actual behavior**
Props do not work, nothng happens.

**Screenshots**

![Storybook Organisms Tabs props do not work](https://user-images.githubusercontent.com/103260041/190976227-31cdeae2-b1ca-4711-ac92-e49309f1e859.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [chrome]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-273) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
