### ISSUE TITLE
[BUG]: glidejs cause error

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2494]
**Describe the bug**
When trying to run project with SFUI 0.13.3 version this bug appears:
![Screenshot from 2022-09-29 08-13-10](https://user-images.githubusercontent.com/32042425/192953247-9931095e-d2f2-41c3-a5c9-ad1984db3c0e.png)

Probably downgrading glidejs version should help.

**How to reproduce**

1. run project with SFUI 0.13.3
1. see the error

**Expected behavior**
App runs normally.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.

```
//Write code here
```

Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**

* Device: [e.g. iPhone6, Desktop]
* OS: [e.g. iOS8.1]
* Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-282) by [Unito](https://www.unito.io)

**Comment by tm0e83** [comment]
This is actually happening after running the `shopware/cli dev` command. I couldn't solve it so far. Does anyone know what to do here?

**Comment by cdeclerck** [comment]
The only solution I found for the moment is to put a resolution of the glidejs module in version 3.6.0 and to change the import of the module from "@glidejs/glide" to "@glidejs/glide/dist/glide.modular.esm"

**Comment by tm0e83** [comment]
> 

glideJS isn't imported anywhere. I couldn't find a reference.

**Comment by chrisalexqm** [comment]
> > Yep, getting this on VSF Magento 1.0.2 as well.
> > GlideJS 3.6.0 changelog says:
> > > Add package.json "type" field by @julienchazal in [glidejs/glide#623](https://github.com/glidejs/glide/pull/623)
> 
> downgrading to 3.5.2 works.

How are you downgrading, I am use Vue Storefront? Help me please, I tried override on package.json

**Comment by bensinca** [comment]
> The only solution I found for the moment is to put a resolution of the glidejs module in version 3.6.0 and to change the import of the module from "@glidejs/glide" to "@glidejs/glide/dist/glide.modular.esm"

@chrisalexqm use `resolutions` e.g:

`
  "resolutions": {
    "@glidejs/glide": "3.5.2"
  }
  `

**Comment by rcpfuchs** [comment]
Just copy pasted the string from the image so the error can be found using search 

`require() of ES Module /Users/myuser/projects/vuestorefront/node_modules/@glidejs/glide/dist/glide.js from /Users/myuser/projects/vuestorefront/node_modules/vue-server-renderer/build.dev.js not supported. glide.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules. Instead rename glide.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/myuser/projects/vuestorefront/node_modules/@glidejs/glide/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead). `

**Comment by cdeclerck** [comment]
If you do your init with this command "npx @shopware-pwa/cli@canary init" it should work (this version corresponds to the latest version under development which patches this problem)

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
