### ISSUE TITLE
[BUG] Storybook Organisms Sidebar props do not work

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2507]
**Describe the bug**
Storybook Organisms Sidebar props do not work

**How to reproduce**

Go to Storybook
Go to section components -> organisms -> Sidebar
Scroll down for props
Use props and check component view

**Expected behavior**
You can customise component using props

**Actual behavior**
Props do not work, nothng happens.

Screenshots

Devices (please complete the following information):

Device: [Desktop]
OS: [Windows 11]
Browser: [chrome]

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-310) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
Closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page)
