### ISSUE TITLE
[FEATURE] SfAccordionItem 

### ISSUE THREAD

**Issue by samberrry** [vuestorefront/storefront-ui#2512]
**Describe how this feature will help us improve**
SfAccordionItem component:
https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfAccordion/_internal/SfAccordionItem.vue

I think it would be better to control Chevron in Item component instead of getting parent, 
```
showChevron: $parent.showChevron,
```

This way we can hide chevron if there is not any sub-item.

**Comment by samberrry** [comment]
I could not use SfAccordionItem, created new one:
https://github.com/vuestorefront-community/prestashop/blob/feat/sub-menu/packages/theme/components/AccordionItem.vue

**Comment by samberrry** [comment]
https://github.com/vuestorefront-community/prestashop/blob/develop/packages/theme/components/AccordionItem.vue

**Comment by dkacper** [comment]
@samberrry thank you for this suggestion. We released StorefrontUI v2 recently. We still provide support for v1, but unfortunately, we are not going to introduce any new features.
