### ISSUE TITLE
[Bug]: SfProductCard typo error 

### ISSUE THREAD

**Issue by Daewon25** [vuestorefront/storefront-ui#2514]
### Describe the Bug

` isAddedToCart: {
      type: Boolean,
      deafult: false,
    },`

There is typo in isAddedToCart props in default key. 

### Expected behavior

Key should be **default** instead of **deafult**

### What version of Vue Storefront are you using?

2.7.1

### What version of Node.js are you using?

16.17.0

### What browser (and version) are you using?

Chrome 107.0.5304.87

### What operating system (and version) are you using?

MasOS Monterrey 12.6 (21G115)

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peoray** [comment]
Is this still open for contribution? @filrak

**Comment by AdamPawlinski** [comment]
@peoray If you would like to take it, let me know. Also it would be nice if you could take a look on our [new version of SFUI](https://docs-stg.storefrontui.io/v2/). We would be grateful for feedback or any feature ideas.

**Comment by FRSgit** [comment]
@peoray FYI: this bug was just fixed by @ymaheshwari1 (see the link above).

Thank you all for your contributions!

**Comment by peoray** [comment]
@AdamPawlinski why does the link ask for a username and password?

**Comment by ymaheshwari1** [comment]
> @AdamPawlinski why does the link ask for a username and password?

Which link?
