### ISSUE TITLE
[QUESTION] How to animate an accordion with transition?

### ISSUE THREAD

**Issue by Beethoven** [vuestorefront/storefront-ui#2561]
### What is your question / Please describe your issue

 How to animate an accordion with transition? Vue transition, like the example on Drawer transition.

### What package and version of StorefrontUI are you using?

    "@storefront-ui/vue": "^2.0.0",

### What framework does your application use?

Nuxt

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FRSgit** [comment]
Hello @Beethoven 👋 

To elaborate further on @mattmaribojoc response:
I've prepared a [sample implementation of `AnimatedAccordionItem` component](https://stackblitz.com/edit/sfui-vue-v82wyq?file=src%2FApp.vue,src%2Fcomponents%2FAnimatedAccordionItem.vue) for you.

It is built around the idea that the [`open` attribute of native `<details>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#attributes) should be removed **only after the "leaving" transition has ended** (when accordion is being closed). We can achieve it by:
- creating separate `isOpen` ref which will handle `open` state of native `<details>` element,
- setting `isOpen` to false only after `after-leave` event is emitted by [`<transition>` component](https://vuejs.org/guide/built-ins/transition.html#javascript-hooks),
- setting `isOpen` to true immediately right after outside state change.

Adding to that - I've proposed a sample collapse behaviour based on CSS-only `max-height` transition. It's not perfect (with sample implementation accordionItem content shouldn't be bigger than `300px`), but I hope you can tweak it to your needs.

Do our two responses answer your question?

BTW. 
Nice to see that you're exploring our library - we are eagerly waiting for further feedback from you 😁

**Comment by Beethoven** [comment]
Yes!! Thanks!
It would be really cool to see this example in the docs.
