### ISSUE TITLE
[Bug]: `SfSelect` reset chevron on focus out

### ISSUE THREAD

**Issue by roiLeo** [vuestorefront/storefront-ui#2569]
### Describe the Bug

https://user-images.githubusercontent.com/9987732/229819688-2ee7654f-2018-4dc0-bbb5-9bb4588e258a.mov

### Current behavior

After selecting a value from the list, the chevron is not returned to its original position.

### Expected behavior

When user click to an option it should reset default icon to chevron-down

### Steps to reproduce

See video

### What package and version of StorefrontUI are you using?

@storefront-ui/vue@^2.0.0

### What framework does your application use?

Nuxt

### What version of Node.js are you using?

16

### What browser (and version) are you using?

Firefox

### What operating system (and version) are you using?

OSX

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkacper** [comment]
Hi, @roiLeo! Thank you for reporting this bug. We added it to out list and will be working on the fix soon.

**Comment by runyasak** [comment]
Hi, @dkacper.
I've created the PR to resolve this issue.
Please, review my PR: #2574
