### ISSUE TITLE
Next Image tag vs HTML img tag

### ISSUE THREAD

**Issue by skirianov** [vuestorefront/storefront-ui#2573]
### Provide a description of requested docs changes

Hey, in the docs we have a misaligned usage of Next `Image` tag and HTML `img` tag in Blocks section:

E.g.

NavBarTop - https://docs.storefrontui.io/v2/react/blocks/NavbarTop.html#navbartop-with-white-background

```
<a href="/" aria-label="SF Homepage" className="inline-block text-primary-700">
    <img src={brandLogo.src} alt="Sf Logo" className="hidden lg:block mr-10 w-[12.5rem] h-[1.75rem]" />
     <img src={brandLogoSign.src} alt="Sf Logo" className="block w-8 h-8 mr-4 md:w-10 md:h-10 lg:hidden" />
</a>
```

ProductCard - https://docs.storefrontui.io/v2/react/blocks/ProductCard.html#productcard-vertical

```
<SfLink href="#">
          <Image
            src={productImage.src}
            alt="Great product"
            className="object-cover h-auto rounded-md aspect-square"
            width={300}
            height={300}
          />
        </SfLink>
```

I believe we should decide on what to use. IMO, we should stick with HTML `img` tag, since not all users are using Next.js

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkacper** [comment]
Hi, @skirianov!
Thanks for bringing this topic up. You're absolutely right, we should not use any meta framework specific components. Just like you said, not everyone uses Next.js so I think we must remain meta-framework-agnostic. I'm going to push this topic with the team, and we try to unify the docs in this regards.

**Comment by runyasak** [comment]
Hi, @skirianov.
I've created a PR for this issue.
Please, review my PR: #2575

**Comment by Szymon-dziewonski** [comment]
@skirianov @runyasak I just approved PR since I believe that was initial decision of whole team, to use none meta-framework specific features, so `react` only users could also be able to use our blocks and base components. Thank you for you input and discussion :)
