### ISSUE TITLE
SfButton accessibility notes

### ISSUE THREAD

**Issue by skirianov** [vuestorefront/storefront-ui#2576]
### Provide a description of requested docs changes

In the SfButton [documentation](https://docs.storefrontui.io/v2/react/components/button.html#accessibility-notes) - Accessibility Notes we are mentioning `type="button"`, but in the `API` section and previously we use `as` prop. 

What is the correct one? 
As per the component's source code, I believe we use `as` prop. 

Has to be fixed for other instances too, if applicable

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Szymon-dziewonski** [comment]
@skirianov `as` prop is referring to component HTML tag `button` or `a` however `type` is something different, for `button` html tag you can have `type` - `button` or `submit`, so in docs its mentioned that we have set `type="button"` for HTML `button` tag, you can set `type` like any other attribute on HTML `<SfButton type="submit"/>` and it will be applied via `{...attributes}` (react), bind to root or `v-bind` (vue) . Hope my explanation answers your question.

**Comment by skirianov** [comment]
@Szymon-dziewonski got it. Closing the issue thanks
