### ISSUE TITLE
[Bug]: SfSelect placeholder not hidden

### ISSUE THREAD

**Issue by runyasak** [vuestorefront/storefront-ui#2603]
### Describe the Bug

When I passed the `placeholder`, the placeholder appears but it appears as a selectable option too.

### Current behavior

The placeholder is appeared and can be selected.

![Screen Shot 2566-04-17 at 22 30 04](https://user-images.githubusercontent.com/6861191/232540233-4a878d6d-a55b-4149-b024-7ab0382c4cdb.png)

### Expected behavior

The placeholder should not be appeared as an option and can select.

![Screen Shot 2566-04-17 at 22 30 14](https://user-images.githubusercontent.com/6861191/232540248-2ddbc654-8aa0-425c-9fa1-d79d43474ce1.png)

### Steps to reproduce

* import and create `SfSelect` component
* pass value to `placeholder` prop

### What package and version of StorefrontUI are you using?

v2.0.0

### What framework does your application use?

Vue, React

### What version of Node.js are you using?

v16.17.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aniamusial** [comment]
Hey @runyasak, thank you for reporting! We will look into this ASAP :)

**Comment by aniamusial** [comment]
@runyasak perfect, then I'm assigning it you :) Have fun coding!

**Comment by runyasak** [comment]
@aniamusial Hi, I've created a PR for this issue.
Please, check out and review my code: #2613 😁
