### ISSUE TITLE
Where are the v1 docs?

### ISSUE THREAD

**Issue by brendan-jefferis** [vuestorefront/storefront-ui#2608]
### Provide a description of requested docs changes

Could you please provide a working link to the v1 docs?

The new docs page refers me to https://storefrontui.io/v1 but that redirects to https://vuestorefront.io/storefront-ui and clicking through to documentation goes to v2 docs.

![image](https://user-images.githubusercontent.com/2459887/232968219-e27a43c0-5c66-4fc2-895f-c1c485d1caac.png)

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Szymon-dziewonski** [comment]
@brendan-jefferis Thank you for reporting this issue to us, we will look into it :)

**Comment by ymaheshwari1** [comment]
https://docs.storefrontui.io/v1
