### ISSUE TITLE
[DOCS] SfRadio with label example

### ISSUE THREAD

**Issue by runyasak** [vuestorefront/storefront-ui#2617]
# Description

Some labels in some [SfRadio examples](https://docs.storefrontui.io/v2/vue/components/radio.html#radio-with-trailing-control) are far from the radio box.
I'm not sure that it would be good practice for radio.
You can see from the screenshot below:

![Screen Shot 2566-04-20 at 19 51 12](https://user-images.githubusercontent.com/6861191/233372962-2a315aa6-f919-4b59-aa5d-fb00bc04bc6e.png)

# Expected Result
The label should stay near with label, like in the screenshot below.

![Screen Shot 2566-04-20 at 19 51 02](https://user-images.githubusercontent.com/6861191/233372957-4cdae662-4f52-4e52-ad49-746a16cf0367.png)

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aniamusial** [comment]
Hey @runyasak :) Can you tell us how to reproduce this bug adn which browser/system do you use?

**Comment by aniamusial** [comment]
Hey @runyasak - this is a designed behavior for leading variant of radio group. You can resize the preview window to see how it adjusts to full width. Is it more readable now? Let me know if you think we can somehow improve the docs for this component, so its clear for everyone :)

**Comment by runyasak** [comment]
I have one more question about SfRadio.

Should we have `label` prop for SfRadio?

I think that it would be easier than creating with label manually.

`label` prop could be optional.

**Comment by runyasak** [comment]
> @runyasak we are thinking about form elements, which means embedding label inside Radio, Checkbox or Input or any other form control component will hold us back with particular HTML structure which isn't good for customizability. People might use `SfRadio` in different way so fixing one solution isn't good DX. Base components should be a light and customizable as possible. We are not planning to extend `SfRadio` with label, but there might be some wrappers for label, errors components in future. Hope that clear a little bit context here :)

Oh, that would be better than passing label to `SfRadio`.
Thank you for discussing this with me. 😁

**Comment by Szymon-dziewonski** [comment]
@runyasak no worries, glad I could help out :)
