### ISSUE TITLE
[Bug]: SfDrawer does not support open={true} initial state

### ISSUE THREAD

**Issue by skirianov** [vuestorefront/storefront-ui#2639]
### Describe the Bug

When setting SfDrawer `open` prop to `true` it results in error in Next.js

```
<SfDrawer
    open={false}
>
```

this works well, but

```
<SfDrawer
    open={true}
>
```

results in error (screenshot attached)
<img width="1055" alt="Screenshot 2023-04-27 at 17 23 43" src="https://user-images.githubusercontent.com/74229951/234931141-22c912fd-9e4b-4fa8-9ee0-805b050a43b2.png">

### Current behavior

Breaking client app

### Expected behavior

Should work well if we want to set Drawer open by default

### Steps to reproduce

Import `SfDrawer`
Set `open` prop to `true`
Open client

### What package and version of StorefrontUI are you using?

2.1.0

### What framework does your application use?

Next.js

### What version of Node.js are you using?

16

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

MacOS

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkacper** [comment]
Thank you @skirianov. We believe this bug has been already fixed by our team and the fix should be released as a part of the 2.2 release soon. We're going to double check though.

**Comment by skirianov** [comment]
Awesome, thanks a lot @dkacper! We can close the issue then
