### ISSUE TITLE
[BUG] Cannot set width and height to SfGallery images and thumbnails

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#2798]
### Describe the Bug

Sizes passed via props to imageHeight and imageWidth, alongside thumbnailWidth and thumbnailHeight are not working - sizes are not changing on the images.

### Expected behavior

Width and height of images are changing.

### Steps to reproduce

1. Go to Storybook
2. Go to SfGallery
3. Change imageWidth/imageHeight prop to 200.
4. See the error

### SFUI version

@storefront-ui/vue@0.13.6

### Framework

Vue, Nuxt

### Node version

16.17.0

### Browser

Chrome

### OS

macOs

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdamPawlinski** [comment]
It's a valid bug, in my opinion, custom properties responsible for setting the sizes don't work properly. Need to be fixed.

**Comment by FRSgit** [comment]
@AdamPawlinski This should be added to our SLA board then, right?

**Comment by FRSgit** [comment]
This issue got fixed in #2919, and will be released in `0.14`
