### ISSUE TITLE
Install Setup for vuestorefront V2 with magento2

### ISSUE THREAD

**Issue by bhagvanp** [vuestorefront/storefront-ui#2963]
### Describe the Bug

I have started setup for Vue storefront V2 with magento2 but facing below issue any idea how we resolve issue. please help me for setup project.

I have used below versions for install.

"@storefront-ui/vue": "^2.5.0"

"@nuxtjs/tailwindcss": "^6.8.0",

![image](https://github.com/vuestorefront/storefront-ui/assets/143793264/ed8d0400-d457-48d8-bf18-900e23989ec3)

### Expected behavior

"@storefront-ui/vue": "^2.5.0"

### SFUI version

"@storefront-ui/vue": "^2.5.0"

### Framework

Vuejs

### Node version

v16.20.2

### Browser

Chrome

### OS

linux

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by justyna-13** [comment]
Hi @bhagvanp is this issue duplicated here- https://github.com/vuestorefront/storefront-ui/issues/2969?

**Comment by FRSgit** [comment]
Hey @bhagvanp,
We didn't got any response for 2 weeks so as a part of housekeeping I'm marking this issue as stale. Please respond if you feel that something should be done here. Without any response - we'll close this issue next week.

**Comment by Szymon-dziewonski** [comment]
Closing this issue in favor of https://github.com/vuestorefront/storefront-ui/issues/2969 , conversation should be continued there. Thanks :)
