### ISSUE TITLE
[Bug]: Missing `typography-hint-xs` class

### ISSUE THREAD

**Issue by lukaszjedrasik** [vuestorefront/storefront-ui#2981]
### Describe the Bug

I see there is no `typography-hint-xs` class in the [list](https://docs.storefrontui.io/v2/react/customization/typography.html#list-of-classes) but is visible in [Figma](https://www.figma.com/file/A9oevt176KzEx3aWDyLCZq/%F0%9F%9B%A0-SFUI-2-%7C-Demo-v.1.1-(development)?type=design&node-id=18593-112027&mode=design&t=HpAMbGv5MtHWF5jW-0).

### Expected behavior

I can use `typography-hint-xs` in my project.

### SFUI version

@storefront-ui/react@2.5.0

### Framework

React, Next.js

### Node version

v20.4.0

### Browser

Chrome

### OS

macOS

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Szymon-dziewonski** [comment]
Hello @lukaszjedrasik thanks for ticket, it will be resolved within this [PR](https://github.com/vuestorefront/storefront-ui/pull/3006)

**Comment by Szymon-dziewonski** [comment]
PR were merged, release will be around next monday! Thanks  :)
