### ISSUE TITLE
[ Mobile / Desktop ] SfCollectedProductList

### ISSUE THREAD

**Issue by filrak** [vuestorefront/storefront-ui#332]
This issue requires some components that are not there yet so I'm leaving it like this to keep in mind and wait for https://github.com/DivanteLtd/storefront-ui/pull/315
Also API needs to be figured out (and how we reuse those components)
desktop
![image](https://user-images.githubusercontent.com/15185752/64817515-56dd2180-d5aa-11e9-9280-ed118aefe8fb.png)

mobile
![image](https://user-images.githubusercontent.com/15185752/64817285-ce5e8100-d5a9-11e9-9868-d2fc83f2d5ba.png)

**Comment by aniamusial** [comment]
@RakowskiPrzemyslaw how its going? Any PR soon? :)
