### ISSUE TITLE
[REFACTOR] Remove v-html behaviour from SfSelect

### ISSUE THREAD

**Issue by pspaczek** [vuestorefront/storefront-ui#664]
Acceptance Criteria
- SfSelect can be disabled #533
- SfSelect don't use `v-html` 
- SfSelect [Mobile] should work with SfContentPages #618

**Comment by Baroshem** [comment]
As far as I understand (this is rather an old issue) the main idea was to remove v-html from SfSelect. I checked this component and it no longer contains v-html. I am closing the issue. If needed, it can be reopened.
