### ISSUE TITLE
[FEATURE] Implement SfRange

### ISSUE THREAD

**Issue by martaradziszewska** [vuestorefront/storefront-ui#852]
According to the new design, we need to implement new component SfScale

![image](https://user-images.githubusercontent.com/34887212/75978014-e4585900-5edd-11ea-9eea-88de44cd96a7.png)

Design: https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=187%3A336

**Comment by aniamusial** [comment]
Maybe we can call it SfRangeSlider, IMO its more generic - WDYT? :)

**Comment by martaradziszewska** [comment]
Yup, SfRange sounds better :)
