### ISSUE TITLE
[FEATURE] Implement SfColorPicker in SfProductCard

### ISSUE THREAD

**Issue by martaradziszewska** [vuestorefront/storefront-ui#881]
**Describe how this feature will help us improve**
This issue is blocked by https://github.com/DivanteLtd/storefront-ui/issues/851
With new design, we need to implement SfColorPicker in SfProductCard

**Additional context**
Mobile: https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=264%3A566
Desktop: https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=771%3A306

**Comment by pspaczek** [comment]
related #949

**Comment by EduardDopler** [comment]
(Unblocked because #851 is implemented now (merged with PR #1012))
