### ISSUE TITLE
[REFACTOR] SfSearchbar - replace <input> with SfInput

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#882]
**Describe how this feature will help us improve**
Replace <input> with SFUI SfInput to keep the atomic approach.

Blocked by #849

**Comment by peoray** [comment]
@aniamusial Hi. Can I go ahead with this? Just checked and the block PR is merged.

**Comment by aniamusial** [comment]
Sorry, it awaits #819 as well :( You can take care of the other tasks you are assigned to :)

**Comment by pspaczek** [comment]
@peoray you can improve SfInput to SfSearch

**Comment by peoray** [comment]
@pspaczek I can't find SfSearch amongst the components

**Comment by pspaczek** [comment]
@peoray it's `SfSearchBar` now
