### ISSUE TITLE
[FEATURE]Product listing- add button '+ Colors' on mobile

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/storefront-ui#950]
**Describe how this feature will help us improve**
Easy and quick way of choosing color of product

**Describe the solution you'd considered**
Add button '+ Colors' on mobile on product listing as below:
<img width="174" alt="+Color" src="https://user-images.githubusercontent.com/57936972/74730100-d5b74400-5245-11ea-8c6e-b7f2f5a071fb.png">

After pressing the '+ Colors' button a list of available colors of the product appears as below:
<img width="181" alt="+Color1" src="https://user-images.githubusercontent.com/57936972/74730161-f1bae580-5245-11ea-9975-5cf117998f9b.png">
After pressing color, the choice is remembered. Then if user adds the product to the cart, the product is added with chosen color.

**Acceptance criteria**

- [ ]   the '+ Colors' button is added to the product listing on mobile
- [ ]  after pressing the '+ Color' a list of available colors appears
- [ ] chosen color is remembered as long as the user is on that product listing
- [ ] pressing any spot other than color square closes the list of available colors
- [ ] after choosing the color, when user adds the product to the cart, it is added with tat chosen color

**Comment by akrajna** [comment]
related link https://github.com/DivanteLtd/shopware-pwa/issues/406

**Comment by pspaczek** [comment]
related: #881
